### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by jjeaton** [ChrisRM/material-theme-jetbrains#10]
I'm running PHPStorm 9.0.2
Build #PS-141.2462
JRE: 1.6.0_65-b14-468-11M4828a x86_64
OS X 10.10.5

and I get this message after installing the plugin and restarting:

```
Plugin 'com.chrisrm.idea.MaterialTheme4' failed to initialize and will be disabled.  Please restart PhpStorm.

com.intellij.diagnostic.PluginException: com/chrisrm/idea/MTColorScheme : Unsupported major.minor version 52.0 [Plugin: com.chrisrm.idea.MaterialTheme4]
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:427)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:417)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:403)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:108)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:481)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:62)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.UnsupportedClassVersionError: com/chrisrm/idea/MTColorScheme : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
    ... 30 more
```

**Comment by walkerstone** [comment]
Same issue
PhpStorm 8.0.2

**Comment by ryanwinchester** [comment]
try with JRE 1.8

**Comment by B-iggy** [comment]
For me it works with the newest jre / jdk, too. I had similar error messages with old a jre.

**Comment by jjeaton** [comment]
@ryanwinchester @B-iggy thanks. Can I just upgrade to 1.8 or do I need to download the PHPStorm version that bundles it? https://www.jetbrains.com/phpstorm/download/ I previously had not done that due to the message on that page:

> This alternative PhpStorm 9 distribution bundles JDK 1.8 customized by the JetBrains team for better performance. Please note this non-default option may contain some issues.

**Comment by ryanwinchester** [comment]
I just use the bundled one. I've only ever come across 1 issue (that I've noticed, and not sure if related), when I have multiple PHPStorm windows open the [Contexts window switcher app](https://contexts.co/) doesn't register all of them in the sidebar.

**Comment by B-iggy** [comment]
I downloaded the new version of PhpStorm. Maybe you can define the path to the new jre / jdk like in eclipse also.

**Comment by jjeaton** [comment]
Thanks, that worked for me!

**Comment by ChrisRM** [comment]
I'll update the readme with the requirements. Thanks for helping out guys.

**Comment by ChrisRM** [comment]
I'll keep this open until I've checked whether its possible to support earlier versions of the JDK.

**Comment by tdlm** [comment]
Just wanted to say that this worked for me (running Homebrew w/ Cask):

```brew update && brew cask install java```

Problem solved.
