### ISSUE TITLE
Exception after continuous delay in 2018.3 

### ISSUE THREAD

**Issue by pahan35** [ChrisRM/material-theme-jetbrains#1045]
### Summary

I faced with exception after some pause in work,
```
java.lang.ClassCastException: com.chrisrm.idea.ui.MTTableHeaderUI$MTDefaultRenderer cannot be cast to com.intellij.database.run.ui.TableResultView$MyCellRenderer
	at com.intellij.database.run.ui.TableResultView$MyTableColumn.getPreferredHeaderWidth(TableResultView.java:1189)
	at com.intellij.database.run.ui.grid.DefaultGridColumnLayout.computeHeaderWidth(DefaultGridColumnLayout.java:158)
	at com.intellij.database.run.ui.grid.DefaultGridColumnLayout.doLayout(DefaultGridColumnLayout.java:93)
	at com.intellij.database.run.ui.grid.DefaultGridColumnLayout.doLayout(DefaultGridColumnLayout.java:39)
	at com.intellij.database.run.ui.TableResultView.lambda$layoutColumns$5(TableResultView.java:958)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
At first time I faced something similar in September

### Expected behavior

No exceptions

### Actual behavior

Attached exception

### Steps to reproduce (if needed)

1. Create DB data source. I use SSH tunneled connection
2. Explore any existing table with data
3. Have a dinner, go for a walk etc for 15+ minutes
4. Resume your work.

Table not necessary should be an active tab.

### Environment

PhpStorm 2018.3 EAP
Build #PS-183.4284.100, built on November 14, 2018
PhpStorm EAP User
Expiration date: December 14, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

```
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.10.6" />
    <option name="selectedTheme" value="ONE_DARK" />
    <option name="highlightColor" value="80cbc4" />
    <option name="accentColor" value="80cbc4" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="darkTitleBar" value="true" />
    <option name="compactDropdowns" value="true" />
    <option name="upperCaseButtons" value="false" />
    <option name="settingsSelectedTab" value="1" />
    <option name="userId" value="[hidden]" />
    <option name="allowDataCollection" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="isCompactMenus" value="true" />
  </component>
</application>
```

Please let me know if you need more info

**Comment by mallowigi** [comment]
That's really weird, I use tables all the time and never encountered this issue unexpectedly. This usually happens if I open the Material Theme Settings and change something there, then my tables get messed up and I have to restart (I can still use them just fine but there are some weird artifacts).

If that's the case, then it's a known bug and nothing I can do unfortunately.

**Comment by pahan35** [comment]
I that case I guess it's problem on JetBrains' side.
I sent exception report to them since I faced it the first time.
I'll create a separate ticket for it in their bug report system and link this issue in that description.
