### ISSUE TITLE
Exception on startup in 3.0.0-rc1

### ISSUE THREAD

**Issue by pahan35** [ChrisRM/material-theme-jetbrains#1061]
### Summary

I've noticed an exception after plugin update

### Expected behavior

No exceptions

### Actual behavior

```
java.lang.NoClassDefFoundError: com/intellij/psi/javadoc/PsiDocTag
	at com.chrisrm.idea.annotators.BaseAnnotator.annotate(BaseAnnotator.java:46)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:120)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:353)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:286)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:313)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:316)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:597)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:316)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:316)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:71)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:316)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:283)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:227)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.javadoc.PsiDocTag PluginClassLoader[com.chrisrm.idea.MaterialThemeUI, 3.0.0-rc1] com.intellij.ide.plugins.cl.PluginClassLoader@6993ac5d
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more
```

### Steps to reproduce (if needed)

1. Install the plugin of version **3.0.0-rc1**
2. Open PhpStorm

### Environment

```
PhpStorm 2018.3
Build #PS-183.4284.150, built on November 21, 2018
Licensed to Pavlo Zhukov
Subscription is active until May 28, 2019
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

Material Theme/Material Custom Theme configuration file.
```
<application>
  <component name="MaterialThemeConfig">
    <option name="allowDataCollection" value="true" />
    <option name="compactDropdowns" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="upperCaseButtons" value="false" />
    <option name="useMaterialFont" value="false" />
    <option name="rightTreeIndent" value="6" />
    <option name="settingsSelectedTab" value="1" />
    <option name="accentColor" value="80cbc4" />
    <option name="highlightColor" value="80cbc4" />
    <option name="selectedTheme" value="ONE_DARK" />
    <option name="userId" value="c74a82e:163eac94c2e:-7fff" />
    <option name="version" value="3.0.0-rc1" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Thanks I’ll fix it right away

**Comment by michahell** [comment]
Was about to report this. again: great work on such a great Webstorm plugin 👍 
meanwhile, I'll look into how to installing the previous version

**Comment by michahell** [comment]
Seems we can't ❓ install specific plugin **versions**
So disabling plugin for now seems to keep the awesome syntax coloring in place, at least 👍

**Comment by pahan35** [comment]
@michahell  I've submitted a [request about allowing setup specific plugin version](https://youtrack.jetbrains.com/issue/IDEA-203176) to JetBrains. Upvote on it if you need this feature
