### ISSUE TITLE
NullPointer exception in MTProgressBarUI

### ISSUE THREAD

**Issue by dcelasun** [ChrisRM/material-theme-jetbrains#1073]
### Summary
Occasionally I get a NullPointerException with the following stack trace:

```
java.lang.NullPointerException
	at com.chrisrm.idea.ui.MTProgressBarUI.paintDeterminate(MTProgressBarUI.java:170)
	at javax.swing.plaf.basic.BasicProgressBarUI.paint(BasicProgressBarUI.java:412)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1057)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5211)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1292)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5159)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4970)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:829)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:829)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:804)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:753)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:71)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1860)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Happens in Goland and IDEA 2018.3, usually when using the debugger, but not always. I can't reproduce it reliably, but it happens 10+ times a day, triggering the crash reporter.

### Expected behavior

It shouldn't happen.

### Actual behavior

It happens.

### Environment

```
GoLand 2018.3
Build #GO-183.4284.141, built on November 20, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.12-arch1-1-ARCH
```

**Plugin version:** 3.0.0-rc4

**material-theme.xml**
```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="allowDataCollection" value="true" />
    <option name="darkTitleBar" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="tabsHeight" value="50" />
    <option name="accentColor" value="80cbc4" />
    <option name="selectedTheme" value="DARKER" />
    <option name="userId" value="-5e1704a5:163f3190c65:-7fff" />
    <option name="version" value="3.0.0-pre4" />
  </component>
</application>
```

**Comment by dcelasun** [comment]
@mallowigi why did you close this? I believe I've provided all the info requested in the issue template.

**Comment by mallowigi** [comment]
It's because it will be available on the next release.

**Comment by dcelasun** [comment]
Thanks!
