### ISSUE TITLE
Critical Startup Error

### ISSUE THREAD

**Issue by rahulggk** [ChrisRM/material-theme-jetbrains#1087]
### Summary
Webstorm is experiencing critical startup. It is unable to start after installing the plugin.

### Expected behavior
Webstorm should start normally.

### Actual behavior
Throwing Plugin error and unable to start with plugin enabled.

### Steps to reproduce (if needed)

1. First step
Install Material Theme UI plugin.

2. Second step
Restart IDE.

![screenshot from 2018-12-12 17-53-18](https://user-images.githubusercontent.com/38885614/49869683-1c85fe80-fe37-11e8-8059-fff7b726cc71.png)

### Environment

WebStorm 2018.3.1
Build #WS-183.4588.66, built on December 5, 2018
Licensed to WebStorm Evaluator
Expiration date: January 11, 2019
JRE: 1.8.0_152-release-1343-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-140-generic

Material Theme Plugin v3.1.0

### Error Details

    Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart 
      WebStorm.

    java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:371)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:81)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:405)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:391)
        at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
        at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
        at java.awt.EventQueue.access$500(EventQueue.java:98)
        at java.awt.EventQueue$3.run(EventQueue.java:715)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at 
     java.security.ProtectionDomain$JavaSecurityAccessImpl.
    doIntersectionPrivilege(ProtectionDomain.java:80)
         at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
         at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:342)
         at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
        Caused by: java.lang.NullPointerException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at javassist.ClassPool.toClass2(ClassPool.java:1183)
        at javassist.ClassPool.toClass(ClassPool.java:1164)
        at javassist.ClassPool.toClass(ClassPool.java:1113)
        at javassist.ClassPool.toClass(ClassPool.java:1071)
        at javassist.CtClass.toClass(CtClass.java:1275)
        at com.chrisrm.idea.MTHackComponent.hackTitleLabel(MTHackComponent.java:213)
        at com.chrisrm.idea.MTHackComponent.<clinit>(MTHackComponent.java:50)
    ... 23 more`

**Comment by mallowigi** [comment]
It it something new or did you update?

**Comment by rahulggk** [comment]
I have a brand new installation of WebStorm.

**Comment by mallowigi** [comment]
I just tried downloading Webstorm on Ubuntu Mint and it got without any issues. What I can see in the log though is something partially related to the plugin but not really.

Can you try this? 
https://github.com/getgauge/Intellij-Plugin/issues/177#issuecomment-244883416

**Comment by mallowigi** [comment]
Can you provide me the list of plugins you use ?

**Comment by rahulggk** [comment]
Maybe this will help you.

`2018-12-17 18:46:46,047 [   3500]   INFO - llij.ide.plugins.PluginManager - Plugin 'IntelliJ Configuration Script' can't be loaded because: Plugin does not include any module dependency tags in its plugin.xml therefore is assumed legacy and can be loaded only in IntelliJ IDEA 
2018-12-17 18:46:46,108 [   3561]   INFO - llij.ide.plugins.PluginManager - 60 plugins initialized in 273 ms 
2018-12-17 18:46:46,108 [   3561]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: ASP (0.1), AngularJS (183.4886.15), CSS Support (183.4886.15), CoffeeScript (183.4886.15), Copyright (8.1), Cucumber.js (0.1), Dart (183.4886.15), Docker integration (183.4886.15), EJS (183.4886.15), EditorConfig (183.4886.15), File Watchers (183.4886.15), Gherkin (999.999), Git Integration (8.1), GitHub (183.4886.15), HTML Tools (2.0), HTTP Client (183.4886.15), Haml (183.4886.15), Handlebars/Mustache (183.4886.15), IDE Settings Sync (183.4886.15), IDEA CORE (183.4886.15), IntelliLang (8.0), Java Server Pages (JSP) Integration (1.0), JavaScript Debugger (1.0), JavaScript Intention Power Pack (0.9.4), JavaScript Support (1.0), Karma (183.4886.15), Less support (183.4886.15), LiveEdit (183.4886.15), Markdown support (183.4886.15), Mercurial Integration (10.0), Meteor (183.4886.15), Node.js Remote Interpreter (183.4886.15), NodeJS (183.4886.15), Performance Testing (183.4886.15), PhoneGap/Cordova Plugin (183.4886.15), Polymer & Web Components (999.999), Prettier (183.4886.15), Pug (ex-Jade) (183.4886.15), Refactor-X (2.01), Remote Hosts Access (0.1), SSH Remote Run (0.1), Sass support (183.4886.15), Settings Repository (183.4886.15), Spy-js (183.4886.15), Stylus support (999.999), Subversion Integration (1.1), Task Management (1.0), Terminal (0.1), TextMate bundles support (183.4886.15), Time Tracking (1.0), UML Support (1.0), Vagrant (183.4886.15), Vue.js (183.4886.15), W3C Validators (2.0), XPathView + XSLT Support (4), YAML (183.4886.15), Yeoman (183.4886.15), tslint (183.4886.15) 
2018-12-17 18:46:46,108 [   3561]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Material Theme UI (3.2.0) 
2018-12-17 18:46:46,108 [   3561]   INFO - llij.ide.plugins.PluginManager - Disabled plugins: IntelliJ Configuration Script (183.4886.15) 
2018-12-17 18:46:46,216 [   3669]   INFO - napi.wm.impl.WindowManagerImpl - jawt failed to load 
java.lang.UnsatisfiedLinkError: Native Library /home/ggku3sys114/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/183.4886.15/jre64/lib/amd64/libjawt.so already loaded in another classloader
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1907)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.intellij.openapi.wm.impl.WindowManagerImpl.<clinit>(WindowManagerImpl.java:64)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:374)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:81)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:391)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
	at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:342)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-12-17 18:46:46,363 [   3816]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin com.chrisrm.idea.MaterialThemeUI 
java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin com.chrisrm.idea.MaterialThemeUI
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:215)
	at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:342)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin com.chrisrm.idea.MaterialThemeUI
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:253)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:390)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:81)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:391)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
	... 16 more
Caused by: com.intellij.diagnostic.PluginException:  [Plugin: com.chrisrm.idea.MaterialThemeUI]
	... 23 more
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:371)
	... 20 more
Caused by: java.lang.NullPointerException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javassist.ClassPool.toClass2(ClassPool.java:1183)
	at javassist.ClassPool.toClass(ClassPool.java:1164)
	at javassist.ClassPool.toClass(ClassPool.java:1113)
	at javassist.ClassPool.toClass(ClassPool.java:1071)
	at javassist.CtClass.toClass(CtClass.java:1275)
	at com.chrisrm.idea.MTHackComponent.hackTitleLabel(MTHackComponent.java:213)
	at com.chrisrm.idea.MTHackComponent.<clinit>(MTHackComponent.java:50)
	... 23 more
2018-12-17 18:46:46,364 [   3817]  ERROR - llij.ide.plugins.PluginManager - WebStorm 2018.3.2 EAP  Build #WS-183.4886.15 
2018-12-17 18:46:46,364 [   3817]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_152-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2018-12-17 18:46:46,364 [   3817]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
`

**Comment by rahulggk** [comment]
You can see that apart from default plugins I have only material plugin installed.

**Comment by mallowigi** [comment]
WebStorm 2018.3.1
Build #WS-183.4588.66, built on December 5, 2018
Licensed to Material Theme Jetbrains / Elior Boukhobza
Subscription is active until October 3, 2019
For non-commercial open source development only.
JRE: 1.8.0_152-release-1343-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-42-generic

**Comment by mallowigi** [comment]
Sorry, I have no idea how to fix your case, it doesn't happen on my end.

**Comment by Vahelnir** [comment]
Hi, i also have the same error.
![error material theme](https://user-images.githubusercontent.com/9640068/50539760-e3af8e80-0b85-11e9-9fda-28aa4aaad69b.png)
After closing this window, Intellij Idea just disable the plugin and everything is working as expected.
When enabling the plugin again, it can, sometimes, start without crashing.

Environment :
IntelliJ IDEA 2018.3.2 (Ultimate Edition)
Build #IU-183.4886.37, built on December 17, 2018
Subscription is active until December 5, 2019
For educational use only.
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.19.8-arch1-1-ARCH

<details>
  <summary>Error details</summary>
 
```
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.ExceptionInInitializerError
    at sun.misc.Unsafe.ensureClassInitialized(Native Method)
    at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
    at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
    at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
    at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
    at java.lang.reflect.Field.set(Field.java:764)
    at com.chrisrm.idea.utils.StaticPatcher.setFinalStatic(StaticPatcher.java:75)
    at com.chrisrm.idea.utils.StaticPatcher.setFinalStatic(StaticPatcher.java:56)
    at com.chrisrm.idea.UIReplacer.patchOnMouseOver(UIReplacer.java:90)
    at com.chrisrm.idea.UIReplacer.patchUI(UIReplacer.java:82)
    at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:399)
    at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:356)
    at com.chrisrm.idea.schemes.MTThemesComponent.activateTheme(MTThemesComponent.java:69)
    at com.chrisrm.idea.schemes.MTThemesComponent.initComponent(MTThemesComponent.java:58)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:486)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:447)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:471)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:405)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:391)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
    at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:342)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.jdom.JDOMException: ParseError at [row,col]:[6,2]
Message: The content of elements must consist of well-formed character data or markup.
    at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:229)
    at com.intellij.openapi.util.JDOMUtil.load(JDOMUtil.java:287)
    at com.intellij.util.JdomKt.loadElement(jdom.kt:49)
    at com.intellij.configurationStore.SchemeDataHolderImpl.read(SchemeManagerImpl.kt:678)
    at com.intellij.openapi.keymap.impl.KeymapImpl.getActionIdToShortcuts(KeymapImpl.kt:68)
    at com.intellij.openapi.keymap.impl.KeymapImpl.getMutableShortcutList(KeymapImpl.kt:431)
    at com.intellij.openapi.keymap.impl.KeymapImpl.getShortcuts(KeymapImpl.kt:422)
    at com.intellij.openapi.keymap.KeymapUtil.getActiveKeymapShortcuts(KeymapUtil.java:225)
    at com.intellij.ide.actions.Switcher.<clinit>(Switcher.java:94)
    ... 43 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[6,2]
Message: The content of elements must consist of well-formed character data or markup.
    at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:596)
    at com.intellij.openapi.util.SafeStAXStreamBuilder.processElementFragment(SafeStAXStreamBuilder.java:138)
    at com.intellij.openapi.util.SafeStAXStreamBuilder.build(SafeStAXStreamBuilder.java:95)
    at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:222)
    ... 51 more
```
</details>

**Comment by mallowigi** [comment]
For this you need to remove your material_theme.xml configuration file and reinstall the plugin

**Comment by ForsakenHarmony** [comment]
Great fix..

**Comment by ForsakenHarmony** [comment]
<details>
<summary>Here's the error I get</summary>

```
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart WebStorm.

java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.util.IconLoader.getReflectiveIcon(IconLoader.java:124)
    at com.intellij.openapi.util.IconLoader.findIcon(IconLoader.java:202)
    at com.intellij.openapi.util.IconLoader.findIcon(IconLoader.java:190)
    at com.intellij.openapi.util.IconLoader.findIcon(IconLoader.java:185)
    at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:154)
    at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:117)
    at com.chrisrm.idea.icons.tinted.TintedIconsService.getIcon(TintedIconsService.java:158)
    at com.chrisrm.idea.icons.IconReplacer.replaceIcons(IconReplacer.java:65)
    at com.chrisrm.idea.icons.IconReplacer.replaceIcons(IconReplacer.java:86)
    at com.chrisrm.idea.plugins.MTPluginDatagrip.initComponent(MTPluginDatagrip.java:39)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:486)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:447)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:471)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:405)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:391)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
    at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:342)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalStateException: @NotNull method com/intellij/openapi/util/IconLoader.getIcon must not return null
    at com.intellij.openapi.util.IconLoader.$$$reportNull$$$0(IconLoader.java)
    at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:158)
    at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:117)
    at com.chrisrm.idea.icons.tinted.TintedIconsService.getAccentIcon(TintedIconsService.java:166)
    at icons.MTIcons$DataGrip.<clinit>(MTIcons.java:172)
    ... 41 more
```
</details>

Something about an icon
