### ISSUE TITLE
Exception when starting Idea

### ISSUE THREAD

**Issue by octavz** [ChrisRM/material-theme-jetbrains#1089]
### Summary

I have an exception in the status bar:
```
org.jdom.JDOMException: ParseError at [row,col]:[2666,25]
Message: Element type "option" must be followed by either attribute specifications, ">" or "/>".
	at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:229)
	at com.intellij.openapi.util.JDOMUtil.load(JDOMUtil.java:287)
	at com.intellij.util.JdomKt.loadElement(jdom.kt:49)
	at com.intellij.configurationStore.SchemeDataHolderImpl.read(SchemeManagerImpl.kt:678)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$1EditorColorSchemeProcessor.createScheme(EditorColorsManagerImpl.java:86)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$1EditorColorSchemeProcessor.createScheme(EditorColorsManagerImpl.java:77)
	at com.intellij.configurationStore.LazySchemeProcessor.createScheme$default(scheme-impl.kt:69)
	at com.intellij.configurationStore.SchemeManagerImpl.loadScheme$intellij_platform_configurationStore_impl(SchemeManagerImpl.kt:327)
	at com.intellij.configurationStore.SchemeManagerImpl.loadSchemes(SchemeManagerImpl.kt:196)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.<init>(EditorColorsManagerImpl.java:146)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:85)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:62)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:45)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:210)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:52)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:26)
	at com.intellij.openapi.editor.colors.EditorColorsManager.getInstance(EditorColorsManager.java:36)
	at com.chrisrm.idea.MTThemeManager.switchScheme(MTThemeManager.java:410)
	at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:375)
	at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:355)
	at com.chrisrm.idea.schemes.MTThemesComponent.activateTheme(MTThemesComponent.java:69)
	at com.chrisrm.idea.schemes.MTThemesComponent.initComponent(MTThemesComponent.java:58)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:486)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:471)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:391)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
	at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:342)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[2666,25]
Message: Element type "option" must be followed by either attribute specifications, ">" or "/>".
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:596)
	at com.intellij.openapi.util.SafeStAXStreamBuilder.processElementFragment(SafeStAXStreamBuilder.java:138)
	at com.intellij.openapi.util.SafeStAXStreamBuilder.build(SafeStAXStreamBuilder.java:95)
	at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:222)
	... 57 more
```

### Expected behavior

No exception

### Actual behavior

Exception

### Steps to reproduce (if needed)

Start IDE

### Environment

IntelliJ IDEA 2018.3.1 (Community Edition)
Build #IC-183.4588.61, built on December 4, 2018
JRE: 1.8.0_152-release-b1213 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-39-generic

Material version v3.1.0

Where is Material configuration file?

**Comment by mallowigi** [comment]
https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs
