### ISSUE TITLE
EAP 2019.1 breaks plugin

### ISSUE THREAD

**Issue by planetf1** [ChrisRM/material-theme-jetbrains#1114]
After upgrading to EAP 2019.1 the following crash occurs... Thought it may be useful info... it's unclear if it's an intellij issue or theme- or just an unfortunate incompatability

MacOS 10.14.3

Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NullPointerException
    at com.chrisrm.idea.MTApplicationComponent.initAnalytics(MTApplicationComponent.java:54)
    at com.chrisrm.idea.MTApplicationComponent.initComponent(MTApplicationComponent.java:50)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:486)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:451)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:475)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:409)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:395)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
    at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:322)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mallowigi** [comment]
Which version of the plugin did you download?

**Comment by FelicityHughes** [comment]
I had the same issue when JetBrains Toolbox updated several IDEs to 2019.1 this morning - completely froze all IDEs (GoLand, IntelliJ, PyCharm & WebStorm) at the splash screen.  As with OP, using MacOS 10.14.3.  Had to Force Quit the IDEs, then follow the directions at https://intellij-support.jetbrains.com/hc/en-us/articles/206544519 to remove the Material Theme.

However, went back into Plugins and downloaded version 3.5 from the Marketplace in IntelliJ IDEA and after reconfiguration, it is now fine.  Will report back if I don't get the same result in GoLand, PyCharm or WebStorm.

**Comment by mallowigi** [comment]
Yes for some reason when they updated the idea, since the plugin was configured to run for 2018.* only, the plugin wasn’t available to download, however in the repository a very old version was available, probably because at the time i didn’t specify an upper limit for the version. So you were downloading an old version that isn’t at all compatible with 2019
