### ISSUE TITLE
Cannot access several destinations from the welcome screen

### ISSUE THREAD

**Issue by eserdk** [ChrisRM/material-theme-jetbrains#1248]
### Summary

Trying to click any button being at PyCharm welcome screen - have nothing to happen.
Also I cannot turn Material Design UI off now.

#### LEFT COLUMN
Clicking on a button leads to a project editing.

#### RIGHT COLUMN
Create new project  -> frameworks appears at left column -> **you may set up at the right side them to start your work**;
Configure -> Plugins/Preferences/Run configuration templates for new projects/Manage License -> **Works**

#### LEFT COLUMN
Clicking on a button does nothing.

#### RIGHT COLUMN
Create new project  -> frameworks appears at left column -> **nothing to display in right column**;
Configure -> Plugins/Preferences/Run configuration templates for new projects/Manage License -> **Nothing happens.**

You can also add Screenshots for a better understanding.

### Environment
PyCharm 2019.1.3 (Professional Edition)
Build #PY-191.7479.30, built on May 29, 2019
Licensed to Eugene Serdyuk
Subscription is active until December 31, 2019
For educational use only.
JRE: 11.0.2+9-b159.60 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5

```
<application>
  <component name="MaterialThemeConfig">
    <option name="isCompactMenus" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="overrideAccentColor" value="true" />
    <option name="settingsSelectedTab" value="6" />
    <option name="accentColor" value="42a5f5" />
    <option name="selectedTheme" value="ARC_DARK" />
    <option name="userId" value="612b86d9:1673f72aede:-8000" />
    <option name="version" value="3.10.0" />
  </component>
</application>%
```

**UPDATE**
Occasionally could open IDE fatal errors page while was writing this report:
```
java.lang.NoSuchMethodError: com.intellij.util.ui.JBUI.scale(Lcom/intellij/util/ui/JBScalableIcon;)Lcom/intellij/util/ui/JBScalableIcon;
	at com.chrisrm.idea.ui.MTCheckBoxUI.<clinit>(MTCheckBoxUI.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at sun.reflect.misc.Trampoline.invoke(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/sun.reflect.misc.MethodUtil.invoke(Unknown Source)
	at java.desktop/javax.swing.UIDefaults.getUI(Unknown Source)
	at java.desktop/javax.swing.UIManager.getUI(Unknown Source)
	at java.desktop/javax.swing.JCheckBox.updateUI(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.init(Unknown Source)
	at java.desktop/javax.swing.JToggleButton.<init>(Unknown Source)
	at java.desktop/javax.swing.JCheckBox.<init>(Unknown Source)
	at java.desktop/javax.swing.JCheckBox.<init>(Unknown Source)
	at com.intellij.application.options.editor.EditorOptionsPanel.$$$setupUI$$$(EditorOptionsPanel.java)
	at com.intellij.application.options.editor.EditorOptionsPanel.<init>(EditorOptionsPanel.java:110)
	at com.intellij.application.options.editor.EditorOptionsTopHitProvider.getConfigurable(EditorOptionsTopHitProvider.java:17)
	at com.intellij.ide.ui.ConfigurableOptionsTopHitProvider.getOptions(ConfigurableOptionsTopHitProvider.java:127)
	at com.intellij.ide.ui.OptionsTopHitProvider.lambda$getCachedOptions$0(OptionsTopHitProvider.java:51)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at com.intellij.ide.ui.OptionsTopHitProvider.getCachedOptions(OptionsTopHitProvider.java:51)
	at com.intellij.ide.ui.OptionsTopHitProvider.access$400(OptionsTopHitProvider.java:37)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.cache(OptionsTopHitProvider.java:172)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.lambda$cacheAll$0(OptionsTopHitProvider.java:159)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by mallowigi** [comment]
please update to latest version
