### ISSUE TITLE
NullPointerException in 2019.2 EAP

### ISSUE THREAD

**Issue by extesy** [ChrisRM/material-theme-jetbrains#1263]
### Summary

This exception pops up periodically in the latest version of plugin and IntelliJ:
```
java.lang.NullPointerException
	at com.intellij.vcs.commit.ChangesViewCommitPanel$commitButton$1.isDefaultButton(ChangesViewCommitPanel.kt:101)
	at com.intellij.ui.components.BasicOptionButtonUI$BaseButton.isDefaultButton(BasicOptionButtonUI.kt:314)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaButtonUI.isDefaultButton(DarculaButtonUI.java:54)
	at com.chrisrm.idea.ui.MTButtonUI.installDefaults(MTButtonUI.java:117)
	at java.desktop/javax.swing.plaf.basic.BasicButtonUI.installUI(BasicButtonUI.java:105)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.AbstractButton.setUI(AbstractButton.java:1753)
	at java.desktop/javax.swing.JButton.updateUI(JButton.java:141)
	at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2136)
	at java.desktop/javax.swing.JButton.<init>(JButton.java:131)
	at java.desktop/javax.swing.JButton.<init>(JButton.java:85)
	at com.intellij.ui.components.BasicOptionButtonUI$BaseButton.<init>(BasicOptionButtonUI.kt:312)
	at com.intellij.ui.components.BasicOptionButtonUI$MainButton.<init>(BasicOptionButtonUI.kt:324)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaOptionButtonUI$createMainButton$1.<init>(DarculaOptionButtonUI.kt:34)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaOptionButtonUI.createMainButton(DarculaOptionButtonUI.kt:34)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaOptionButtonUI.createMainButton(DarculaOptionButtonUI.kt:19)
	at com.intellij.ui.components.BasicOptionButtonUI.installButtons(BasicOptionButtonUI.kt:95)
	at com.intellij.ui.components.BasicOptionButtonUI.installUI(BasicOptionButtonUI.kt:64)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.AbstractButton.setUI(AbstractButton.java:1753)
	at java.desktop/javax.swing.JButton.updateUI(JButton.java:141)
	at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2136)
	at java.desktop/javax.swing.JButton.<init>(JButton.java:131)
	at java.desktop/javax.swing.JButton.<init>(JButton.java:85)
	at java.desktop/javax.swing.JButton.<init>(JButton.java:116)
	at com.intellij.ui.components.JBOptionButton.<init>(JBOptionButton.kt:21)
	at com.intellij.vcs.commit.ChangesViewCommitPanel$commitButton$1.<init>(ChangesViewCommitPanel.kt:92)
	at com.intellij.vcs.commit.ChangesViewCommitPanel.<init>(ChangesViewCommitPanel.kt:268)
	at com.intellij.openapi.vcs.changes.ChangesViewManager.updateCommitWorkflow(ChangesViewManager.java:199)
	at com.intellij.vcs.commit.CommitWorkflowManager.updateWorkflow(CommitWorkflowManager.kt:37)
	at com.intellij.vcs.commit.CommitWorkflowManager.access$updateWorkflow(CommitWorkflowManager.kt:24)
	at com.intellij.vcs.commit.CommitWorkflowManager$subscribeToChanges$3$$special$$inlined$runInEdt$1.run(actions.kt:74)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:782)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:731)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:396)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:707)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Steps to reproduce (if needed)

1. Install IntelliJ 2019.2 EAP
2. Install material theme plugin

### Environment

```
IntelliJ IDEA 2019.2 EAP (Ultimate Edition)
Build #IU-192.5281.24, built on June 19, 2019
IntelliJ IDEA EAP User
Expiration date: July 19, 2019
Runtime version: 11.0.3+12-b304.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 3.10.0-514.55.4.el7.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 18083M
Cores: 16
Registry: debugger.click.disable.breakpoints=true, diff.patience.alg=true, git.explicit.commit.renames.prohibit.multiple.calls=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, Shifter, String Manipulation, com.arcticicestudio.nord.jetbrains, com.intellij.bigdecimal-folding, com.linkedin.intellij.dust, com.linkedin.intellix.intellix, com.linkedin.pegasus-intellij-plugin.pegasusplugin, com.thvardhan.gradianto, de.ax.powermode, mobi.hsz.idea.gitignore, org.jetbrains.plugins.rest, BashSupport, org.jetbrains.kotlin, com.chrisrm.idea.MaterialThemeUI, com.dmarcotte.handlebars, com.wix.eslint, org.intellij.scala, org.jetbrains.plugins.go, org.jetbrains.plugins.vue, Pythonid, org.nik.presentation-assistant, org.rust.lang, training
```

**Comment by mallowigi** [comment]
Already fixed in 4.0.5
