### ISSUE TITLE
Can't enable

### ISSUE THREAD

**Issue by danielgsims** [ChrisRM/material-theme-jetbrains#13]
Howdy, this theme looks fantastic, but I'm getting this error while enabling:

Plugin 'com.chrisrm.idea.MaterialTheme4' failed to initialize and will be disabled.  Please restart PhpStorm.
```
com.intellij.diagnostic.PluginException: com/chrisrm/idea/MTColorScheme : Unsupported major.minor version 52.0 [Plugin: com.chrisrm.idea.MaterialTheme4]
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
   ...
```

Any idea why?

**Comment by danielgsims** [comment]
Nevermind, I suppose it's because I'm on PHPStorm 8.

**Comment by B-iggy** [comment]
@danielgsims see https://github.com/ChrisRM/material-theme-jetbrains/issues/11 and https://github.com/ChrisRM/material-theme-jetbrains/issues/10
