### ISSUE TITLE
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled. ( HEAD@master builds )

### ISSUE THREAD

**Issue by talios** [ChrisRM/material-theme-jetbrains#131]
Under todays IntelliJ Community HEAD@master ( 6503efdf587eb91800e428bc05feb03758feb857 ) the L&F now fails to start.

The exception looks like it's caused _by_ IntelliJ - however the normal look and feels continue to work.

(yes, I'm running bleeding edge builds of IntelliJ - heh ). Treat this as maybe a heads up that something may change...  I'll report back if later builds resolve the issue.

    Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

    java.lang.ExceptionInInitializerError
        at sun.misc.Unsafe.ensureClassInitialized(Native Method)
        at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
        at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
        at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
        at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
        at java.lang.reflect.Field.get(Field.java:393)
        at com.chrisrm.idea.utils.IconReplacer.replaceIcons(IconReplacer.java:20)
        at com.chrisrm.idea.utils.IconReplacer.replaceIcons(IconReplacer.java:42)
        at com.chrisrm.idea.MTIconReplacer.initComponent(MTIconReplacer.java:24)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:522)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
        at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:90)
        at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:496)
        at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
        at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:505)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:454)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:446)
        at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
        at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
    Caused by: java.lang.IllegalStateException: @NotNull method com/intellij/openapi/util/IconLoader.getIcon must not return null
        at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:180)
        at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:146)
        at com.intellij.icons.AllIcons$Windows.<clinit>(AllIcons.java:1225)
        ... 39 more

**Comment by ChrisRM** [comment]
Thanks for this, there have some problems on the stable releases as well, so I'll see if I can reproduce and fix this.

**Comment by talios** [comment]
This all seems to work again under current HEAD@master builds so will close this particular ticket.
