### ISSUE TITLE
Exception when Changing Accent Color 

### ISSUE THREAD

**Issue by gamedaddydaniel** [ChrisRM/material-theme-jetbrains#1320]
I have nothing kotlin related installed.
Rider 2019.2 (192.5895.1069)
MacOs X 10.14.2
 
This may be related to [Rider: Internal IDE error #1229](https://github.com/ChrisRM/material-theme-jetbrains/issues/1229)

I have nothing kotlin related installed.  However, changes to the Custom Accent Color on the Material Theme Preferences page throws this exception:
 
kotlin.KotlinNullPointerException
	at com.intellij.ui.components.BasicOptionButtonUI.getOptionButton(BasicOptionButtonUI.kt:44)
	at com.intellij.ui.components.BasicOptionButtonUI$BaseButton.getBackground(BasicOptionButtonUI.kt:315)
	at java.desktop/javax.swing.JComponent.setBackground(JComponent.java:2751)
	at com.chrisrm.idea.utils.ColorCycle.lambda$new$0(ColorCycle.java:49)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:405)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:404)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by gamedaddydaniel** [comment]
I am not seeing any exceptions in WebStorm when I change theme settings.

**Comment by gamedaddydaniel** [comment]
GoLand is clear too!  No Exceptions.

**Comment by gamedaddydaniel** [comment]
IntelliJ clear as well ... 
... Looks like only Rider is affected.

**Comment by mallowigi** [comment]
Meh. If Rider does things differently so it's too bothersome to fix. It works either way so I'll just close this issue.
