### ISSUE TITLE
Crash when startup

### ISSUE THREAD

**Issue by SettingDust** [ChrisRM/material-theme-jetbrains#1328]
### Summary
IDEA crash behind update this plugin to 4.4.0

### Expected behavior
Normally

### Actual behavior
```
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.AssertionError
    at org.xmlpull.v1.XmlPullParserFactory.<init>(XmlPullParserFactory.java:43)
    at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:221)
    at com.thoughtworks.xstream.io.xml.XppDriver.createParser(XppDriver.java:57)
    at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:54)
    at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:65)
    at com.thoughtworks.xstream.io.AbstractDriver.createReader(AbstractDriver.java:66)
    at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1412)
    at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1359)
    at com.chrisrm.idea.icons.IconPatchersFactory.create(IconPatchersFactory.java:61)
    at com.chrisrm.idea.icons.MTIconReplacerComponent.<init>(MTIconReplacerComponent.java:51)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:88)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:481)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$7(ApplicationImpl.java:414)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:414)
    at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:150)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:377)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

### Steps to reproduce (if needed)

1. Update to 4.4.0 & IDEA 2019.2.1 RC
2. Restart
3. CRASH

### Environment
```
IntelliJ IDEA 2019.2.1 (Community Edition)
Build #IC-192.6262.41, built on August 15, 2019
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1971M
Cores: 8
Registry: ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: CMD Support, Lombook Plugin, YAML/Ansible support, de.netnexus.camelcaseplugin, mobi.hsz.idea.gitignore, com.demonwav.minecraft-dev, com.codota.csp.intellij, org.jetbrains.plugins.hocon, MavenRunHelper, org.zalando.intellij.swagger
```

Material Theme UI is 4.4.0

**Comment by mallowigi** [comment]
Try version 4.4.4

**Comment by SettingDust** [comment]
> Try version 4.4.4

Sry, IDEA update to 4.4.0 suddenly. And cannot update to 4.4.4. I reinstall the plugin and it's ok.
