### ISSUE TITLE
Error when enabling Material Theme v4.5 in phpStorm 2019.2.1

### ISSUE THREAD

**Issue by filliph** [ChrisRM/material-theme-jetbrains#1365]
### Summary

Error on startup

### Expected behavior

It actually working :P 

### Actual behavior

It does not.

### Steps to reproduce (if needed)

1. Enable theme
2. ???
3. Not profit

You can also add Screenshots for a better understanding.

### Environment

```
PhpStorm 2019.2.1
Build #PS-192.6262.66, built on August 22, 2019
Licensed to Fillip H.
Subscription is active until January 17, 2020
Runtime version: 11.0.3+12-b304.39 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation, name.kropp.intellij.makefile, org.intellij.RegexpTester, com.dmarcotte.handlebars, de.espend.idea.php.annotation, org.psliwa.idea.composer, ru.adelf.idea.dotenv, zielu.gittoolbox
```

```
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.NoClassDefFoundError: com/intellij/ui/tabs/newImpl/SingleHeightTabs
    at com.chrisrm.idea.UIReplacer.patchTabs(UIReplacer.java:247)
    at com.chrisrm.idea.UIReplacer.patchUI(UIReplacer.java:61)
    at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:446)
    at com.chrisrm.idea.MTThemeManager.activateWithColorScheme(MTThemeManager.java:395)
    at com.chrisrm.idea.schemes.MTThemesComponent.activateTheme(MTThemesComponent.java:84)
    at com.chrisrm.idea.schemes.MTThemesComponent.initComponent(MTThemesComponent.java:60)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$7(ApplicationImpl.java:414)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:414)
    at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:150)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:377)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.intellij.ui.tabs.newImpl.SingleHeightTabs PluginClassLoader[com.chrisrm.idea.MaterialThemeUI, 4.5] com.intellij.ide.plugins.cl.PluginClassLoader@6b527ba5
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    ... 30 more
```

**Comment by TriangularCube** [comment]
Seconded, just hit me all of a sudden today.

**Comment by cdnrg-rt** [comment]
Same issue

![image](https://user-images.githubusercontent.com/18314457/64569944-d1404400-d313-11e9-93e5-16e72f5bd1e2.png)

**Comment by mallowigi** [comment]
Can any of you check with another ide ? I think PS issued an update today.

**Comment by mallowigi** [comment]
Never mind, this is a version issue. Can you upgrade to the latest EAP? If not please redownload v4.4.6

**Comment by JMNKLS** [comment]
Same with WebStorm. Uninstalled and re-installed WebStorm, then re-installed Material Theme and still same problem.

**Comment by tkashkin** [comment]
Same with AppCode 2019.2.1. It worked before latest theme update.

```
AppCode 2019.2.1
Build #OC-192.6262.61, built on August 21, 2019
Runtime version: 11.0.3+12-b304.39 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15
GC: ParNew, ConcurrentMarkSweep
Memory: 2487M
Cores: 8
Registry: ide.mac.allowDarkWindowDecorations=true, ide.mac.touchbar.use=FALSE, ide.mac.file.chooser.native=false, max.suggested.heap.size=8192, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: AwesomeKotlin, com.intellij.kotlinNative.platformDeps, com.jetbrains.edu, com.intellij.plugins.watcher, org.jetbrains.kotlin.native.appcode
```

**Comment by terrdavis** [comment]
Since I don't want to try EAP version, I downgraded to 4.4.6 to fix.
https://plugins.jetbrains.com/plugin/8006-material-theme-ui/versions

**Comment by Atulin** [comment]
Same with Golang 2019.2.1

**Comment by Bruno7kp** [comment]
Same with Pycharm 2019.2.1

**Comment by phamductri** [comment]
hi, it also happened to my Webstorm on Mac. Webstorm 2019.2.1, Mac version

**Comment by zjslqshqz** [comment]
me too

**Comment by yumere** [comment]
Same issue with `Pycharm 2019.2.1` on macOS (Mojave)

**Comment by M-Porter** [comment]
Same error on `Ubuntu 18.04.3` with `PhpStorm 2019.2.1`

**Comment by Bohr-H** [comment]
AppCode 2019.2.1/MacOS Mojave 
<img width="859" alt="image" src="https://user-images.githubusercontent.com/29001268/64577736-dc48b200-d3af-11e9-9c80-278b69072722.png">

**Comment by mallowigi** [comment]
fixed. Sorry for the troubles.

**Comment by JMNKLS** [comment]
Still there.

**Comment by mallowigi** [comment]
Which version are you on?

--
Elior

**Comment by JMNKLS** [comment]
It works, I'm good. I just had to uninstall and re-install it to get the new update. Thank you.
