### ISSUE TITLE
Crash on WebStorm Startup: NoClassDefFoundError

### ISSUE THREAD

**Issue by taylorgoolsby** [ChrisRM/material-theme-jetbrains#1367]
![image](https://user-images.githubusercontent.com/14286600/64641396-f63ec080-d3c0-11e9-9bc0-28eed3358b3f.png)

```
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart WebStorm.

java.lang.NoClassDefFoundError: com/intellij/ui/tabs/newImpl/SingleHeightTabs
    at com.chrisrm.idea.UIReplacer.patchTabs(UIReplacer.java:247)
    at com.chrisrm.idea.UIReplacer.patchUI(UIReplacer.java:61)
    at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:446)
    at com.chrisrm.idea.MTThemeManager.activateWithColorScheme(MTThemeManager.java:395)
    at com.chrisrm.idea.schemes.MTThemesComponent.activateTheme(MTThemesComponent.java:84)
    at com.chrisrm.idea.schemes.MTThemesComponent.initComponent(MTThemesComponent.java:60)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$7(ApplicationImpl.java:414)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:414)
    at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:150)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:377)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.intellij.ui.tabs.newImpl.SingleHeightTabs PluginClassLoader[com.chrisrm.idea.MaterialThemeUI, 4.5] com.intellij.ide.plugins.cl.PluginClassLoader@57881a45
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    ... 30 more

```

**Comment by taylorgoolsby** [comment]
Nvm duplicate #1365
