### ISSUE TITLE
NullPointerExceptions on MacOS

### ISSUE THREAD

**Issue by Slaviusz** [ChrisRM/material-theme-jetbrains#1415]
### Summary
Frequent repeating crashes on MacOS.

kotlin.KotlinNullPointerException
	at com.intellij.ui.components.BasicOptionButtonUI.getOptionButton(BasicOptionButtonUI.kt:44)
	at com.intellij.ui.components.BasicOptionButtonUI$BaseButton.getBackground(BasicOptionButtonUI.kt:315)
	at java.desktop/javax.swing.JComponent.setBackground(JComponent.java:2751)
	at com.chrisrm.idea.utils.ColorCycle.lambda$new$0(ColorCycle.java:49)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

...

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce (if needed)

You can also add Screenshots for a better understanding.
![image](https://user-images.githubusercontent.com/30972602/67588866-ac2e5600-f746-11e9-9518-5bf531520a1a.png)

### Environment

JetBrains Rider 2019.2.3
Build #RD-192.7317.11, built on October 16, 2019
Licensed to slavius

Runtime version: 11.0.4+10-b304.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 8
Registry: ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.borderless.title.product=false, performance.watcher.unresponsive.interval.ms=1000, ide.tooltip.initialDelay.highlighter=0, search.everywhere.settings=true, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, ide.mac.allowDarkWindowDecorations=true, ide.scratch.in.project.view=false, ide.borderless.title.project.path=false, actionSystem.fix.alt.gr=false, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=600, ide.borderless.title.classpath=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0, ide.require.transaction.for.model.changes=false, rider.enable.designer.winForms=false
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, mobi.hsz.idea.gitignore, izhangzhihao.rainbow.brackets

Material Theme UI 4.5.2

[Settings.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3773004/Settings.zip)

**Comment by mallowigi** [comment]
Can you tell me the steps to reproduce?

**Comment by Slaviusz** [comment]
Actually there is nothing specific to trigger it. I just open Rider or DataGrip and in few seconds after startup the report exception window pops up with this error.
