### ISSUE TITLE
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled. Please restart PhpStorm.

### ISSUE THREAD

**Issue by MasterHK** [ChrisRM/material-theme-jetbrains#142]
I get this error every time i want try to install it, after restart (needed first restart).
I've even reinstalled my phpstorm (someone siad this can fix that bug) but no any changes occurred.
And i've tested with both 0.1.7 and master branch and it wasn't useful again.
This is the error:

```
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled. Please restart PhpStorm. 

java.lang.ClassNotFoundException: com.chrisrm.idea.MTColorScheme PluginClassLoader[com.chrisrm.idea.MaterialThemeUI, 0.1.7] 
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
at java.lang.Class.forName0(Native Method) 
at java.lang.Class.forName(Class.java:348) 
at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:408) 
at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:454) 
at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:446) 
at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194) 
at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:63) 
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) 
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) 
at java.awt.EventQueue.access$500(EventQueue.java:97) 
at java.awt.EventQueue$3.run(EventQueue.java:709) 
at java.awt.EventQueue$3.run(EventQueue.java:703) 
at java.security.AccessController.doPrivileged(Native Method) 
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) 
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) 
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:360) 
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) 
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) 
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) 
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) 
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by MasterHK** [comment]
plus I'm using PhpStorm 10.0.1 build143.382.
thanks in advance.

**Comment by MasterHK** [comment]
It's fixed by manually extracting Material Theme.jar from 'Material Theme.zip' into the 'lib' directory.
So i close this.
Thanks for your great plugin, Chris!
