### ISSUE TITLE
Intellij freeze when replacing svg icons

### ISSUE THREAD

**Issue by dev311k** [ChrisRM/material-theme-jetbrains#1427]
Intellij freeze when replacing some svg icons. (not specific icon maybe?)
It's some part of idea log file.

```
2019-11-05 09:54:02,606 [ 205737]   INFO - tellij.openapi.util.IconLoader - replace '/toolwindows/toolWindowRun.svg' with '/icons/toolwindows/toolWindowRun.svg' 
2019-11-05 09:54:02,619 [ 205750]   INFO - tellij.openapi.util.IconLoader - replace '/toolwindows/toolWindowDebugger.svg' with '/icons/toolwindows/toolWindowDebugger.svg' 
2019-11-05 09:54:04,921 [ 208052]   INFO - tellij.openapi.util.IconLoader - replace '/runConfigurations/invalidConfigurationLayer.svg' with '/icons/runConfigurations/invalidConfigurationLayer.svg' 
2019-11-05 09:54:06,287 [ 209418]   INFO - tellij.xml.Html5SchemaProvider - HTML5_SCHEMA_LOCATION = com.intellij.openapi.util.AtomicNotNullLazyValue$1@6a8552f 
2019-11-05 09:54:09,461 [ 212592]   INFO - tellij.openapi.util.IconLoader - replace '/ide/notification/expand.svg' with '/icons/ide/notification/expand.svg' 
2019-11-05 09:55:03,878 [ 267009]   WARN - pl.local.NativeFileWatcherImpl - Watcher terminated with exit code 1 
2019-11-05 09:55:03,879 [ 267010]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: C:\Program Files\JetBrains\IntelliJ IDEA 2019.1\bin\fsnotifier64.exe 
2019-11-05 09:55:03,880 [ 267011]   INFO - .server.BuildMessageDispatcher - ȶg ߬ѡ: ࠸ѝ ȣݺƮߡ GȘ Эf؎ ӷѥހՏՙ 
java.io.IOException: ȶg ߬ѡ: ࠸ѝ ȣݺƮߡ GȘ Эf؎ ӷѥހՏՙ
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1140)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

sometimes it starts with, 

```
2019-11-05 09:57:19,198 [ 102361]   INFO - tellij.openapi.util.IconLoader - replace '/general/inspectionsError.svg' with '/icons/general/inspectionsError.svg' 
```
```
2019-11-05 10:04:37,249 [ 177819]   INFO - tellij.openapi.util.IconLoader - replace '/actions/realIntentionBulb.svg' with '/icons/actions/realIntentionBulb.svg' 
```

and same IOException.

Disabling the 'Material UI Icons' from Settings helped me. 

I'm on 
Windows 10 64bit
IntelliJ 2019.2.4

**Comment by dev311k** [comment]
I think it's intelliJ issue. 
I'll check it to jetbrains for now.
