### ISSUE TITLE
Build 5.0 doesn't work right in 2020.1 EAP

### ISSUE THREAD

**Issue by alins** [ChrisRM/material-theme-jetbrains#1520]
the project structure tree doesn't seem to be themes anymore. i use "Material Darker" theme.

I see this exception:

java.lang.IllegalArgumentException: Missing extension point: com.mallowigi.idea.MaterialThemeUI.bundledTheme in container Application (containerState=ACTIVE) 
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:229)
	at com.intellij.openapi.extensions.BaseExtensionPointName.getPointImpl(BaseExtensionPointName.java:30)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:37)
	at com.mallowigi.idea.MTBundledThemesManager.loadBundledThemes(MTBundledThemesManager.java:94)
	at com.mallowigi.idea.MTLafComponent.initComponent(MTLafComponent.java:114)
	at com.mallowigi.idea.MTLafComponent.appFrameCreated(MTLafComponent.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:554)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:139)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:472)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:432)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:420)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:404)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:243)
	at com.sun.proxy.$Proxy44.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:103)
	at com.intellij.idea.ApplicationLoader$startApp$8.run(ApplicationLoader.kt:220)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by alins** [comment]
screenshot to better show what "doesn't work right" means

<img width="2098" alt="Screen Shot 2020-02-19 at 11 42 15 AM" src="https://user-images.githubusercontent.com/1194699/74869519-f26a7f00-530c-11ea-8260-8587c4447e29.png">

**Comment by mallowigi** [comment]
OK, I don't understand what happened but I'll look into it. I've removed the version 5.0 for now, please reinstall 4.13.1 thanks.
