### ISSUE TITLE
java.lang.IllegalStateException in PhpStorm 2020.1 EAP build 201.5616.33

### ISSUE THREAD

**Issue by comanche** [ChrisRM/material-theme-jetbrains#1527]
### Summary

Getting a java.lang.IllegalStateException right after installing Materials Theme UI 5.0.0 and restarting in PhpStorm 2020.1 EAP build 201.5616.33.  As soon as PhpStorm restarts, the error notification happens.

### Expected behavior

No exception.

### Actual behavior

Exception happens after installing Materials Theme UI 5.0.0 on startup.

This is the error:

```
java.lang.IllegalStateException: The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 3,4,Idea Thread Group]
    at com.intellij.openapi.ui.DialogWrapper.ensureEventDispatchThread(DialogWrapper.java:2143)
    at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:287)
    at com.intellij.ide.customize.CustomizeIDEWizardDialog.<init>(CustomizeIDEWizardDialog.java:50)
    at com.intellij.ide.customize.CustomizeIDEWizardDialog.<init>(CustomizeIDEWizardDialog.java:45)
    at com.mallowigi.idea.wizard.MTWizardDialog.<init>(MTWizardDialog.java:54)
    at com.mallowigi.idea.MTApplicationComponent.initWizard(MTApplicationComponent.java:53)
    at com.mallowigi.idea.MTApplicationComponent.initComponent(MTApplicationComponent.java:69)
    at com.mallowigi.idea.MTApplicationComponent.welcomeScreenDisplayed(MTApplicationComponent.java:77)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:554)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:139)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:472)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:432)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:420)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:404)
    at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:243)
    at com.sun.proxy.$Proxy34.welcomeScreenDisplayed(Unknown Source)
    at com.intellij.idea.IdeStarter$showWizardAndWelcomeFrame$showWelcomeFrame$1.run(IdeStarter.kt:172)
    at com.intellij.idea.IdeStarter.showWizardAndWelcomeFrame(IdeStarter.kt:199)
    at com.intellij.idea.IdeStarter.main(IdeStarter.kt:108)
    at com.intellij.idea.ApplicationLoader$startApp$8.run(ApplicationLoader.kt:220)
    at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

### Steps to reproduce (if needed)

1. Clean install PhpStorm 2020.1 EAP build 201.5616.33.
2. Start PhpStorm.
3. Install Materials Theme UI 5.0.0
4. Restart PhpStorm
5. Exception happens

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

```
PhpStorm 2020.1 EAP
Build #PS-201.5616.33, built on February 20, 2020
PhpStorm EAP User
Expiration date: March 21, 2020
Runtime version: 11.0.6+8-b722.15 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 12
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI
```

`material_theme.xml` contents:

```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="highContrast" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="accentColor" value="ff9800" />
    <option name="selectedTheme" value="DARKER" />
    <option name="userId" value="59f5da36:170780168a8:-8000" />
    <option name="version" value="1.3.0" />
  </component>
</application>
```

**Comment by BobBenBan** [comment]
Also happening on Intellij IDEA Ultimate 2020.1 EAP.

**Comment by mallowigi** [comment]
fixed
