### ISSUE TITLE
IDEA 2020.1 Material Theme Fails

### ISSUE THREAD

**Issue by 9526xu** [ChrisRM/material-theme-jetbrains#1548]
### Summary

After upgrading to IDEA 2020.1 Material Themes ceased to work :(，like this：
![image](https://user-images.githubusercontent.com/15943801/78950890-c6949a00-7b02-11ea-876d-5dc1903e0173.png)

this icon is not visible。

this error msg：

```log
java.lang.Throwable: Icon cannot be found in 'AllIcons.Mac.Tree_white_right_arrow', aClass='class com.chrisrm.idea.icons.tinted.TintedIconsService'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:206)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:167)
	at com.chrisrm.idea.icons.tinted.TintedIconsService.getIcon(TintedIconsService.java:96)
	at com.chrisrm.idea.icons.tinted.TintedIconsService.getIcon(TintedIconsService.java:88)
	at com.chrisrm.idea.utils.PropertiesParser.parseValue(PropertiesParser.java:116)
	at com.chrisrm.idea.MTLaf.parseValue(MTLaf.java:60)
	at com.intellij.ide.ui.laf.darcula.DarculaLaf.loadDefaults(DarculaLaf.java:322)
	at com.intellij.ide.ui.laf.darcula.DarculaLaf.initIdeaDefaults(DarculaLaf.java:221)
	at com.intellij.ide.ui.laf.darcula.DarculaLaf.getDefaults(DarculaLaf.java:133)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:592)
	at com.chrisrm.idea.MTTheme.activate(MTTheme.java:72)
	at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:334)
	at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:314)
	at com.chrisrm.idea.schemes.MTThemesComponent.activateTheme(MTThemesComponent.java:54)
	at com.chrisrm.idea.schemes.MTThemesComponent.initComponent(MTThemesComponent.java:46)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:46)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:261)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$5(ApplicationImpl.java:334)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:334)
	at com.intellij.idea.ApplicationLoader$startApp$6$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:184)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:416)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Expected behavior

Continued workage

### Actual behavior

Non-workage

### Steps to reproduce (if needed)

1. Have Material Theme UI installed on an older version of IDEA
2. Upgrade to IDEA 2020.1
3. Cry
You can also add Screenshots for a better understanding.

### Environment

idea infos：
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Licensed to dengfei yang
Subscription is active until February 17, 2021
For educational use only.
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: bigger.font.in.project.view=true, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: AceJump, JettyRunner-GK, Key Promoter X, Shifter, Statistic, String Manipulation, YAML/Ansible support, carbon-now-sh, co.notime.intellijPlugin.backgroundImagePlus, com.alayouni.ansiHighlight, com.daylerees.rainglow, jclasslib, GenerateSerialVersionUID, com.ppolivka.gitlabprojects, GrepConsole, GsonFormat, Lombook Plugin, MyBatisLog, SequenceDiagram, Struts Navigator Plugin, zielu.svntoolbox, VisualVMLauncher, com.github.shiraji.emoji, com.thoughtworks.gauge, com.intellij.ideolog, com.jetbrains.jbre.bintray.downloader, com.intellij.plugins.watcher, com.jlh.plugin.idea.mybatis.generator, com.madfish.ide.readhub, com.wakatime.intellij.plugin, de.netnexus.camelcaseplugin, mobi.hsz.idea.gitignore, io.github.biezhi.plugins.gitmoji, krasa.CpuUsageIndicator, MavenRunHelper, cn.wuzhizhan.plugin.mybatis, izhangzhihao.rainbow.brackets, cn.yiiguxing.plugin.translate, com.bruce.intellijplugin.generatesetter, com.zhaow.restful.toolkit, training, org.nik.presentation-assistant

**material theme ui version**
1.3.1.173.3655.1

**Comment by dominikaaaa** [comment]
Can confirm. Updated IDEA and updated theme plugin, updating plugin didn't fix anything
![image](https://user-images.githubusercontent.com/17222512/78952358-4b4fcb80-7aa3-11ea-9cea-3c90215595fb.png)
Material theme UI 5.1.2

**Comment by mallowigi** [comment]
From you screen I can see it working fine... Try to select a Material Theme (you currently have Darcula)

**Comment by 9526xu** [comment]
when I select a Material Themem,the icons disappear.@mallowigi

**Comment by mallowigi** [comment]
http://www.material-theme.com/docs/configuration/icons-settings/#atom-material-icons-plugin

**Comment by dominikaaaa** [comment]
@mallowigi as you can see, only part of IDEA is being themed by the material theme :/
