### ISSUE TITLE
Theme being reset on relaunch of Rider 2020.1

### ISSUE THREAD

**Issue by trevorsmiley** [ChrisRM/material-theme-jetbrains#1579]
### Summary

Theme being reset on relaunch of Rider. This looks to be the same issue that was fixed in Idea.

### Expected behavior

Theme is unchanged on relaunch of Rider

### Actual behavior

Theme is reset on relaunch of Rider

### Steps to reproduce (if needed)

1. Go through the wizard to setup a theme
2. Quit and launch Rider
3. Theme is reset

### Environment

JetBrains Rider 2020.1.0
Build #RD-201.6668.197, built on April 14, 2020
Licensed to [...]
Subscription is active until [...]
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
.NET Core 3.1.3
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 12
Registry: debugger.new.debug.tool.window.view=true, ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.tooltip.showAllSeverities=true, show.diff.preview.as.editor.tab=true, ide.borderless.title.product=false, ide.title.debug=true, performance.watcher.unresponsive.interval.ms=1000, ide.tooltip.initialDelay.highlighter=0, search.everywhere.settings=true, show.diff.preview.as.editor.tab.with.single.click=true, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, vcs.log.show.diff.preview.as.editor.tab=true, ide.borderless.title.debug=true, ide.borderless.title.project.path=false, actionSystem.fix.alt.gr=false, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.borderless.title.classpath=false, ide.balloon.shadow.size=0, ide.require.transaction.for.model.changes=false
Non-Bundled Plugins: com.microsoft.vso.idea, org.intellij.plugins.markdown, com.chrisrm.idea.MaterialThemeUI, com.mallowigi, name.kropp.intellij.makefile, izhangzhihao.rainbow.brackets, aws.toolkit

* Material Theme Plugin version - 5.3.0.2

**Comment by Jamesking56** [comment]
I'm getting the same issue in PHPStorm 2020.1

**Comment by mendax47** [comment]
com.intellij.diagnostic.PluginException: action with the ID "MTDarkerTheme" was already registered. Action being registered is  (); Registered action is Darker Theme (Material darker) Plugin: Material Theme UI Lite [Plugin: com.mallowigi.idea]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:394)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:389)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerChameleon(ActionManagerImpl.java:1244)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.addToMap(ActionManagerImpl.java:1217)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1188)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerOrReplaceActionInner(ActionManagerImpl.java:694)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionElement(ActionManagerImpl.java:667)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processGroupElement(ActionManagerImpl.java:803)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionsChildElement(ActionManagerImpl.java:1084)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.java:507)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:158)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:645)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:54)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:396)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:379)
	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:28)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame.lambda$prepareToShow$0(WelcomeFrame.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

On Every IDE.

**Comment by mallowigi** [comment]
@mendax47 You have Material Theme Lite and Material Theme Full enabled together. You need to disable one.

@trevorsmiley please make sure you're not using Sync Settings.

**Comment by trevorsmiley** [comment]
> @trevorsmiley please make sure you're not using Sync Settings.

@mallowigi sync settings are off. I stopped using it a while ago because it had too many issues.

**Comment by trevorsmiley** [comment]
This looks to have been fixed for me with plugin version 5.3.2.1

**Comment by mallowigi** [comment]
Duplicate
