### ISSUE TITLE
IDE Fatal Error on PHPStorm 2020.1

### ISSUE THREAD

**Issue by dpassola** [ChrisRM/material-theme-jetbrains#1582]
### Summary
When I'm working in PHPStorm, appears at bottom right, an alert with a IDE Fatal Error.
When I click to see the detail of error appears this:
`hould be called at least in the state COMPONENTS_REGISTERED, the current state is: LAF_INITIALIZED
Current violators count: 1

java.lang.Throwable
	at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:56)
	at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:52)
	at com.intellij.openapi.util.registry.Registry.getInstance(Registry.java:131)
	at com.intellij.openapi.util.registry.Registry.get(Registry.java:38)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:54)
	at com.intellij.ui.tabs.impl.JBTabsImpl.<clinit>(JBTabsImpl.java:65)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.chrisrm.idea.MTHackComponent.hackTabs(MTHackComponent.java:84)
	at com.chrisrm.idea.MTHackComponent.<clinit>(MTHackComponent.java:51)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:288)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:194)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:157)
	at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:93)
	at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt:379)
	at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
	at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:376)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.MainImpl$1.proceed(MainImpl.java:104)
	at com.intellij.ide.a.b.T.proceed(T.java:90)
	at com.intellij.ide.a.b.aC.b(aC.java:260)
	at com.intellij.ide.a.b.aY.b(aY.java:276)
	at com.intellij.ide.a.b.aY.c(aY.java:169)
	at com.intellij.ide.a.b.aY.a(aY.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.MainImpl.start(MainImpl.java:96)
	at com.intellij.idea.StartupUtil.lambda$startApp$5(StartupUtil.java:277)
	at com.intellij.util.ui.EdtInvocationManager.executeWithCustomManager(EdtInvocationManager.java:73)
	at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:272)
	at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:239)
	at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:45)
	at java.base/java.lang.Thread.run(Thread.java:834)`

### Steps to reproduce (if needed)
it appears randomly

You can also add Screenshots for a better understanding.
![image](https://user-images.githubusercontent.com/33066266/80616674-79d91a80-8a41-11ea-9ac4-b4e994e4ad79.png)

### Environment

PhpStorm 2020.1
Build #PS-201.6668.153, built on April 13, 2020
Licensed to ESOLVO GLOBAL SL / David Passola
Subscription is active until February 24, 2021
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4059M
Cores: 8
Registry: ide.windowSystem.autoShowProcessPopup=true, search.everywhere.symbols=false, run.processes.with.pty=TRUE, ide.editor.tabs.open.at.the.end=true, search.everywhere.configurations=false, search.everywhere.actions=false, debugger.watches.in.variables=false, search.everywhere.toolwindows=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: CMD Support, DBN, OdpsStudio, Statistic, BashSupport

It should contain:
* Plugin version : 
![image](https://user-images.githubusercontent.com/33066266/80617140-05eb4200-8a42-11ea-8a45-1fd12c0a974e.png)

**Comment by mallowigi** [comment]
First of all, you have an old version. Please update to the latest version.

**Comment by dpassola** [comment]
Hi @mallowigi , i update the plugin from web (in phpstorm don't show any update).
I'll see if error appears again.
Thank you!
