### ISSUE TITLE
Plugin v5.3.2.1 preventing Intellij 2020.2.1 from starting

### ISSUE THREAD

**Issue by lukeic** [ChrisRM/material-theme-jetbrains#1611]
### Summary
I have a fresh install of Intellij 2020.2.1 and Material Theme UI plugin (v5.3.2.1) is preventing the IDE from starting. Starting Intellij directly from `idea.bat` and by clicking on the exe both result in Intellij staying stuck on the splashscreen. Removing the plugin directory from Intellij's %APPDATA% directory fixes the problem.

### Expected behaviour
Intellij should load without issue and not stall on the splashscreen.

### Actual behaviour
Various error messages thrown:

```
Cannot create class com.mallowigi.idea.config.MTConfigTopHitProvider [Plugin: com.chrisrm.idea.MaterialThemeUI]
com.intellij.diagnostic.PluginException: Cannot create class com.mallowigi.idea.config.MTConfigTopHitProvider [Plugin: com.chrisrm.idea.MaterialThemeUI]
        at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:652)
        at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.instantiateClass(ExtensionComponentAdapter.java:54)
        at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:132)
        at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:45)
        at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:68)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:446)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:433)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:283)
        at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:155)
        at com.intellij.ide.ui.OptionsTopHitProvider$Activity.cacheAll(OptionsTopHitProvider.java:191)
        at com.intellij.ide.ui.OptionsTopHitProvider$Activity.preload(OptionsTopHitProvider.java:172)
        at com.intellij.openapi.application.Preloader.lambda$null$1(Preloader.java:79)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
        at com.intellij.openapi.application.Preloader.lambda$null$2(Preloader.java:75)
        at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
        at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
        at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:610)
        ... 25 more
Caused by: java.util.MissingResourceException: Can't find bundle for base name messages.MaterialThemeBundle, locale en_AU
        at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
        at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:1284)
        at com.intellij.AbstractBundle.getResourceBundle(AbstractBundle.java:124)
        at com.intellij.AbstractBundle.getResourceBundle(AbstractBundle.java:103)
        at com.intellij.AbstractBundle.getResourceBundle(AbstractBundle.java:95)
        at com.intellij.AbstractBundle.getMessage(AbstractBundle.java:44)
        at com.mallowigi.idea.messages.MaterialThemeBundle.message(MaterialThemeBundle.java:51)
        at com.mallowigi.idea.config.MTConfigTopHitProvider.getText(MTConfigTopHitProvider.java:83)
        at com.mallowigi.idea.config.MTConfigTopHitProvider.<clinit>(MTConfigTopHitProvider.java:51)
        ... 30 more
Caused by: java.nio.file.NoSuchFileException: C:\Users\Luke
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:198)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:825)
        at java.base/java.util.zip.ZipFile$CleanableResource$FinalizableResource.<init>(ZipFile.java:851)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:840)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
        at java.base/sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:103)
        at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:72)
        at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:125)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155)
        at java.base/java.util.ResourceBundle$Control$1.run(ResourceBundle.java:3227)
        at java.base/java.util.ResourceBundle$Control$1.run(ResourceBundle.java:3216)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3215)
        at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1994)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1776)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
        at java.base
```

### Steps to reproduce
1. Install Intellij 2020.2.1
2. Install the Material Theme UI plugin
3. Attempt to run Intellij

### Environment
IntelliJ IDEA 2020.1.2  Build #IU-201.7846.76
JDK: 11.0.7; VM: OpenJDK Server VM; Vendor: JetBrains s.r.o
OS: Windows 10
Material Theme UI version: 5.3.2.1

**Comment by lukeic** [comment]
Sorry, it appears this issue was on my end in relation to a missing `locale en_AU` resource bundle.
