### ISSUE TITLE
java.lang.IllegalArgumentException: Zero length string passed to TextLayout constructor.

### ISSUE THREAD

**Issue by uonick** [ChrisRM/material-theme-jetbrains#1637]
### Summary
After any updates extension throws exception with message: `java.lang.IllegalArgumentException: Zero length string passed to TextLayout constructor.`
...

### Steps to reproduce (if needed)
1. Open PHPStorm
2. Use Material Theme UI 5.3.4

### Environment
PhpStorm 2020.2.1
**Build** #PS-202.6948.87, built on August 27, 2020
**Runtime version**: 11.0.8+10-b944.31 x86_64
**VM**: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
**macOS** 10.15.6
**GC**: ParNew, ConcurrentMarkSweep
**Memory**: 1981M
**Cores**: 8
**Registry**: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
**Non-Bundled Plugins**: com.chrisrm.idea.MaterialThemeUI, com.mallowigi, name.kropp.intellij.makefile, de.espend.idea.laravel, com.kalessil.phpStorm.phpInspectionsEA, ru.adelf.idea.dotenv
**Material Theme UI**: 5.3.4

#### Screenshot
<img width="1604" alt="Screen Shot 2020-08-31 at 16 08 51" src="https://user-images.githubusercontent.com/365029/91714480-4bad4800-eba5-11ea-83b2-ed44f2e6962c.png">

### Stacktrace
```
java.lang.IllegalArgumentException: Zero length string passed to TextLayout constructor.
	at java.desktop/java.awt.font.TextLayout.<init>(TextLayout.java:382)
	at java.desktop/java.awt.Font.getStringBounds(Font.java:2617)
	at java.desktop/java.awt.Font.getStringBounds(Font.java:2522)
	at java.desktop/java.awt.FontMetrics.getStringBounds(FontMetrics.java:532)
	at com.mallowigi.idea.ui.MTRootPaneUI$1.paintBorder(MTRootPaneUI.java:171)
	at java.desktop/javax.swing.JComponent.paintBorder(JComponent.java:970)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5268)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1063)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:115)
	at java.desktop/java.awt.Container.paint(Container.java:2002)
	at java.desktop/java.awt.Window.paint(Window.java:3941)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:495)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by floq-design** [comment]
+1 Same error today

**Comment by Kovah** [comment]
Should this be fixed? It still happens in 5.6.0.1 (PhpStorm) like every 20 minutes.

**Comment by mallowigi** [comment]
how to reproduce?

**Comment by Kovah** [comment]
I have no idea how to reproduce it. Are there any details I could share? What is a possible action that could lead to this issue?
