### ISSUE TITLE
Code With Me

### ISSUE THREAD

**Issue by OljaKli** [ChrisRM/material-theme-jetbrains#1647]
### Summary

S2R:
1) Start a Code With Me session. During reproducing I used the following: Mac (host) -> Win (client);
2) Install _Material Theme UI/Atom Material Icon_ plugins on the IntelliJ Client;
3) Restart IntelliJ Client;
4) Get the following exception:
```
2020-10-01 01:42:36,624 [   1608]  ERROR - llij.ide.plugins.PluginManager - java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/intellij/history/integration/ui/views/RevisionsList$MyCellRenderer 
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/intellij/history/integration/ui/views/RevisionsList$MyCellRenderer
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/intellij/history/integration/ui/views/RevisionsList$MyCellRenderer
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:476)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:481)
	at com.mallowigi.idea.MTLafComponent.initComponent(MTLafComponent.java:119)
	at com.mallowigi.idea.MTLafComponent.appFrameCreated(MTLafComponent.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:657)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:428)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:403)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:385)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:34)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:190)
	at com.sun.proxy.$Proxy33.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:104)
	at com.intellij.idea.ApplicationLoader$startApp$8.run(ApplicationLoader.kt:239)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	... 11 more
Caused by: java.lang.NoClassDefFoundError: com/intellij/history/integration/ui/views/RevisionsList$MyCellRenderer
	at com.mallowigi.idea.UIReplacer.patchLocalHistory(UIReplacer.java:142)
	at com.mallowigi.idea.UIReplacer.patchUI(UIReplacer.java:73)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.java:385)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.java:334)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.java:344)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.java:97)
	at com.mallowigi.idea.MTLafComponent.lambda$initComponent$0(MTLafComponent.java:119)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$8(ApplicationImpl.java:476)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:126)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:973)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:451)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:450)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.intellij.history.integration.ui.views.RevisionsList$MyCellRenderer PluginClassLoader[PluginDescriptor(name=Material Theme UI, id=com.chrisrm.idea.MaterialThemeUI, path=C:\Users\dryko\AppData\Roaming\JetBrains\IntelliJClient203.4245\plugins\Material Theme, version=5.4.0.1)] com.intellij.ide.plugins.cl.PluginClassLoader@a71605b
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:96)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 37 more
2020-10-01 01:42:36,630 [   1614]  ERROR - llij.ide.plugins.PluginManager - IntelliJ Client 2020.3 EAP  Build #IJC-203.4245 
2020-10-01 01:42:36,631 [   1615]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.8; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-10-01 01:42:36,631 [   1615]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2020-10-01 01:42:36,631 [   1615]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Material Theme UI version: 5.4.0.1 
2020-10-01 01:42:36,631 [   1615]  ERROR - llij.ide.plugins.PluginManager - Last Action:  
2020-10-01 01:44:11,080 [  96064]   INFO - ntellij.idea.ApplicationLoader - External Windows command received 
2020-10-01 01:44:11,096 [  96080]   INFO - ellij.ide.CommandLineProcessor - External command line:
Dir: C:\Users\dryko\AppData\Local\JetBrains\IntelliJClient\IntelliJClient-203.4245-windows-x64\bin
thinClient
https://code-with-me.jetbrains.com/0zIuBlrw18WSnlc7a4ONPA#fp=F13830C40EEC68E4125BD840DF929FAEBFF02983BC34B7B37927B2CB4F4B3298
----- 
2020-10-01 01:44:11,097 [  96081]   INFO - ellij.ide.CommandLineProcessor - Processing command with com.jetbrains.thinclient.ThinClientStarter@70c5f010 
2020-10-01 01:44:11,099 [  96083]  ERROR - nsions.impl.ExtensionPointImpl - Local ClientId is not overridden 
java.lang.IllegalArgumentException: Local ClientId is not overridden
	at com.jetbrains.thinclient.ThinClientStarter.processExternalCommandLineAsync(ThinClientStarter.kt:36)
	at com.intellij.ide.CommandLineProcessor.lambda$processExternalCommandLine$2(CommandLineProcessor.java:158)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:55)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.java:57)
	at com.intellij.ide.CommandLineProcessor.processExternalCommandLine(CommandLineProcessor.java:151)
	at com.intellij.idea.ApplicationLoader$addActivateAndWindowsCliListeners$2$1.run(ApplicationLoader.kt:352)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$8(ApplicationImpl.java:476)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:126)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:973)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:451)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:450)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
5) Client IDE doesn't run until the plugins folder is cleaned.

Reproduced with the following version (not yet released):
IntelliJ IDEA 2020.3 Snapshot (Ultimate Edition)
Build #IU-203.4245, built on September 30, 2020
IntelliJ IDEA EAP User
Expiration date: October 30, 2020
Runtime version: 11.0.8+10-b1108.1 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Non-Bundled Plugins: com.jetbrains.codeWithMe, name.kropp.intellij.makefile, org.intellij.scala, nl.rubensten.texifyidea

But user reports the same problem with 2020.2
Original issue in YouTrack issue tracker:
https://youtrack.jetbrains.com/issue/CWM-1015

**Comment by mallowigi** [comment]
fixed
