### ISSUE TITLE
NullPointerException from PyCharm 2020.3 on MacOS 11.0.1

### ISSUE THREAD

**Issue by PythonCoderAS** [ChrisRM/material-theme-jetbrains#1665]
### Summary

Material Theme threw a NullPointerException during normal use.

### Expected behavior

The above to not happen.

### Actual behavior

A NPE is thrown randomly during normal use.

### Steps to reproduce (if needed)

I am unaware of what caused it to happen.

```
java.lang.NullPointerException: MacUtil.findWindowFromJavaWindow(this.window) must not be null
	at com.intellij.ui.messages.MessageInfo.<init>(MacMessageManagerImpl.kt:55)
	at com.intellij.ui.messages.NativeMacMessageManager.showMessageDialog(MacMessageManagerImpl.kt:138)
	at com.intellij.ui.messages.NativeMacMessageManager.showYesNoDialog(MacMessageManagerImpl.kt:95)
	at com.intellij.openapi.ui.MessageDialogBuilder$YesNo.show(MessageDialogBuilder.kt:116)
	at com.intellij.openapi.ui.MessageDialogBuilder$YesNo.ask(MessageDialogBuilder.kt:96)
	at com.intellij.find.replaceInProject.ReplaceInProjectManager.showReplaceAllConfirmDialog(ReplaceInProjectManager.java:245)
	at com.intellij.find.impl.FindPopupPanel.doOK(FindPopupPanel.java:992)
	at com.intellij.find.impl.FindPopupPanel.lambda$initComponents$10(FindPopupPanel.java:550)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at com.mallowigi.idea.ui.MTButtonUI$ButtonHighlighter.mouseReleased(MTButtonUI.java:370)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

```
PyCharm 2020.3 (Professional Edition)
Build #PY-203.5981.165, built on December 14, 2020
Licensed to <blanked>
Subscription is active until September 19, 2021
For educational use only.
Runtime version: 11.0.9+11-b1145.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: documentation.show.toolbar=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.alayouni.ansiHighlight, com.chrisrm.idea.MaterialThemeUI, com.mallowigi, man-page-viewer, net.seesharpsoft.intellij.plugins.csv, zielu.gittoolbox, com.almightyalpaca.intellij.plugins.discord, org.toml.lang, com.jetbrains.intellij.datalore, ru.adelf.idea.dotenv, ru.meanmail.plugin.requirements, mobi.hsz.idea.gitignore
```

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

Note that not providing any of the required info will result of your issue being closed.

```
<application>
  <component name="MaterialThemeConfig">
    <option name="accentMode" value="true" />
    <option name="allowDataCollection" value="true" />
    <option name="darkTitleBar" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="statusBarTheme" value="false" />
    <option name="useColoredDirectories" value="false" />
    <option name="tabsHeight" value="20" />
    <option name="accentColor" value="7e57c2" />
    <option name="selectedTheme" value="NIGHT_OWL" />
    <option name="userId" value="-6e49d91:16f73067aa6:-8000" />
    <option name="version" value="5.5.0" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
These instances happen oftentimes but do not cause any harm. I tried to pinpoint them but never managed to. In any case, this should not cause any issues other than an error in the console.

**Comment by PythonCoderAS** [comment]
> These instances happen oftentimes but do not cause any harm. I tried to pinpoint them but never managed to. In any case, this should not cause any issues other than an error in the console.

I seem to get them whenever using the find and replace window.

**Comment by dingo-d** [comment]
Yeah, can confirm those too on PhpStorm 2020.3.2, they seem to pop up from time to time, not sure why. But I just dismiss them and nothing seems to be broken 🤷🏼‍♂️
