### ISSUE TITLE
Exception while editing java code

### ISSUE THREAD

**Issue by anstarovoyt** [ChrisRM/material-theme-jetbrains#172]
Hi. I use the plugin with IDEA 2016.1. Regularly I see the exception:

Worker exited due to exception
java.lang.NullPointerException
	at com.chrisrm.idea.icons.VirtualFileInfo.getFileType(VirtualFileInfo.java:24)
	at com.chrisrm.idea.icons.TypeAssociation.matches(TypeAssociation.java:9)
	at com.chrisrm.idea.icons.Associations.findAssociationForFile(Associations.java:47)
	at com.chrisrm.idea.icons.MTFileIconProvider.getIcon(MTFileIconProvider.java:25)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:122)
	at com.intellij.psi.impl.ElementBase.access$000(ElementBase.java:51)
	at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:62)
	at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:55)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:287)
	at com.intellij.ui.DeferredIconImpl$2$1$1.run(DeferredIconImpl.java:158)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:122)
	at com.intellij.ui.DeferredIconImpl$2$1.run(DeferredIconImpl.java:155)

Do you have any plan to fix it? May be you need a PR?

**Comment by cdownard** [comment]
Get the same thing in webstorm :)

**Comment by zhyu** [comment]
just got the same issue in IDEA 2016.1

**Comment by f3yisayo** [comment]
Now I can't even get IDEA to start. Had to disable the plugin
