### ISSUE TITLE
NullPointerException when editing custom theme

### ISSUE THREAD

**Issue by Arjentix** [ChrisRM/material-theme-jetbrains#1725]
### Summary

I can't setup my custom theme. Clion just stops reacting on my actions after I click "Apply" button. After reopening project it shows error message about NullPointerException in Material UI Theme Plugin.

### Expected behavior

Working theme

### Actual behavior

Clion stops reacting on any actions. After closing window and opening again Clion shows message about occurred error:

```
java.lang.NullPointerException
	at com.intellij.ide.HelpTooltip.deriveDescriptionFont(HelpTooltip.java:551)
	at com.intellij.ide.HelpTooltip.createTipPanel(HelpTooltip.java:398)
	at com.intellij.ide.HelpTooltip.initPopupBuilder(HelpTooltip.java:335)
	at com.intellij.ide.HelpTooltip.installOn(HelpTooltip.java:302)
	at com.intellij.openapi.actionSystem.impl.ActionButton.updateToolTipText(ActionButton.java:386)
	at com.intellij.openapi.actionSystem.impl.ActionButton.update(ActionButton.java:282)
	at com.intellij.openapi.actionSystem.impl.ActionButton.addNotify(ActionButton.java:276)
	at com.jetbrains.rd.platform.codeWithMe.toolbar.CWMShowPopupAction$createCustomComponent$1.addNotify(CWMShowPopupAction.kt:156)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/java.awt.Container.add(Container.java:460)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.fillToolBar(ActionToolbarImpl.java:317)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.actionsUpdated(ActionToolbarImpl.java:1138)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.java:1118)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$2.updateActionsImpl(ActionToolbarImpl.java:175)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:151)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:70)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1097)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1092)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addNotify(ActionToolbarImpl.java:213)
	at com.intellij.ide.navigationToolbar.experimental.NewToolbarRootPaneExtension.addGroupComponent(NewToolbarRootPaneExtension.kt:75)
	at com.intellij.ide.navigationToolbar.experimental.NewToolbarRootPaneExtension.revalidate(NewToolbarRootPaneExtension.kt:107)
	at com.intellij.ide.navigationToolbar.experimental.NewToolbarRootPaneExtension.uiSettingsChanged(NewToolbarRootPaneExtension.kt:128)
	at com.intellij.openapi.wm.impl.IdeRootPane.uiSettingsChanged(IdeRootPane.java:365)
	at jdk.internal.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:123)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:86)
	at com.sun.proxy.$Proxy26.uiSettingsChanged(Unknown Source)
	at com.intellij.ide.ui.UISettings.fireUISettingsChanged(UISettings.kt:608)
	at com.intellij.ide.ui.laf.LafManagerImpl.updateEditorSchemeIfNecessary(LafManagerImpl.java:812)
	at com.intellij.ide.ui.laf.LafManagerImpl.setLookAndFeelImpl(LafManagerImpl.java:621)
	at com.intellij.ide.ui.laf.LafManagerImpl.setCurrentLookAndFeel(LafManagerImpl.java:593)
	at com.intellij.ide.ui.LafManager.setCurrentLookAndFeel(LafManager.java:41)
	at com.mallowigi.idea.MTThemeManager.setLookAndFeel(MTThemeManager.java:365)
	at com.mallowigi.idea.MTLafComponent.onSettingsChanged(MTLafComponent.java:213)
	at com.mallowigi.idea.MTLafComponent$1.configChanged(MTLafComponent.java:127)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:674)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:649)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:422)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:379)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:185)
	at com.sun.proxy.$Proxy183.configChanged(Unknown Source)
	at com.mallowigi.idea.MTConfig.fireChanged(MTConfig.java:289)
	at com.mallowigi.idea.MTConfig.applySettings(MTConfig.java:352)
	at com.mallowigi.idea.config.MTConfigurable.doApply(MTConfigurable.java:86)
	at com.mallowigi.idea.config.MTConfigurable.doApply(MTConfigurable.java:43)
	at com.mallowigi.idea.config.MTConfigurableBase.apply(MTConfigurableBase.java:113)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.apply(ConfigurableWrapper.java:179)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.apply(ConfigurableEditor.java:315)
	at com.intellij.openapi.options.newEditor.SettingsEditor$5.apply(SettingsEditor.java:181)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$2.actionPerformed(ConfigurableEditor.java:61)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at com.mallowigi.idea.ui.MTButtonUI$ButtonHighlighter.mouseReleased(MTButtonUI.java:435)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:797)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:436)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1702)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1661)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:90)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:55)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.lambda$initMacApplication$1(MacOSApplicationProvider.java:81)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.lambda$submit$8(MacOSApplicationProvider.java:181)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Steps to reproduce

1. Enable using custom material theme in settings
2. Customize the custom theme
3. Try to apply it

### Environment

CLion 2021.1
Build #CL-211.6693.114, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM (0.66), com.intellij.plugins.vscodekeymap (211.4961.30), com.mallowigi (36.0), com.markotanic.deleteVCSMessage (1.0.1), zielu.gittoolbox (203.5.3), com.chrisrm.idea.MaterialThemeUI (6.2.3)

material_theme.xml:

```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="compactMenus" value="true" />
    <option name="compactStatusBar" value="true" />
    <option name="compactTables" value="true" />
    <option name="compactDropdowns" value="true" />
    <option name="compactSidebar" value="true" />
    <option name="isCompactMenus" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="overrideAccentColor" value="false" />
    <option name="pristineConfig" value="false" />
    <option name="useMaterialWallpapers" value="true" />
    <option name="leftTreeIndent" value="2" />
    <option name="accentColor" value="ab47bc" />
    <option name="selectedTheme" value="CUSTOM" />
    <option name="userId" value="5c648845:177ca28a60f:-8000" />
    <option name="version" value="5.5.0" />
  </component>
</application>
```

material_custom_theme.xml:

```xml
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="excludedColor" value="3c4150ff" />
    <option name="accentColor" value="2979ffff" />
    <option name="notificationsColor" value="282c34ff" />
    <option name="treeSelectionColor" value="3a3f4b80" />
    <option name="highlightColor" value="383d48ff" />
    <option name="secondBorderColor" value="282c34ff" />
    <option name="tableSelectedColor" value="383e49ff" />
    <option name="contrastColor" value="21252bff" />
    <option name="disabledColor" value="6b727dff" />
    <option name="secondaryBackgroundColor" value="2f333dff" />
    <option name="buttonColor" value="3a3f4bff" />
    <option name="selectionForegroundColor" value="ffffffff" />
    <option name="selectionBackgroundColor" value="4d515dff" />
    <option name="textColor" value="979fadff" />
    <option name="foregroundColor" value="979fadff" />
    <option name="backgroundColor" value="282c34ff" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
should be fixed on 6.3.0
