### ISSUE TITLE
IDE Fatal Error on PyCharm

### ISSUE THREAD

**Issue by RecNes** [ChrisRM/material-theme-jetbrains#1731]
### Summary

IDE Fatal error reported by PyCharm 2021.1 after Material Theme UI updated and IDE restarted.

This error reported by IDE every time when IDE has restarted.

### Environment

PyCharm 2021.1 (Professional Edition)
Build #PY-211.6693.115, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-72-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: ide.intellij.laf.enable.animation=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: FridayMario (0.1.6 beta), Rider UI Theme Pack (0.8), aishwarya18102000.starlight (1.0.0), color.scheme.Derwish Theme13 (0.3), color.scheme.Monokai Materialized (1.1), com.alayouni.ansiHighlight (1.2.4), com.arcticicestudio.nord.jetbrains (0.13.0), com.fernandojimenez.mattecarbon.theme (3.0.0), com.github.adamwojszczyk.sepiaTheme (0.2.4), com.ludditelabs.autodocintellij.plugin (0.2.0), com.mallowigi (36.0), com.mallowigi.idea (13.1), com.malvery.yaruDarkTheme (0.2), com.markskelton.one-dark-theme (5.1.5), com.vecheslav.darculaDarkerTheme (1.2.0), com.vermouthx.idea (1.11.3), com.wakatime.intellij.plugin (12.0.7), com.xinkun.theme.md (1.7.12), com.yemreak.DarkCode-Theme (1.1), design.verybeautiful.onedarkmonokai (0.1.8), io.eightpigs.intellij.darktheme (1.0.4), net.antelle.intellij-xcode-dark-theme (1.2.2), net.seesharpsoft.intellij.plugins.csv (2.15.1), mobi.hsz.idea.gitignore (4.1.0), com.atlassian.bitbucket.references (2021.1.163), com.chrisrm.idea.MaterialThemeUI (6.3.3), ru.adelf.idea.dotenv (2021.1), ru.meanmail.plugin.requirements (2021.3-211)
Current Desktop: MATE

### Stack trace

com.intellij.diagnostic.PluginException: ID "MTDarkerTheme" is already taken by action "Darker Theme (Material darker)" (Plugin: Material Theme UI Lite). Action "Darker Theme (Material darker)" (Plugin: Material Theme UI) cannot use the same ID [Plugin: com.chrisrm.idea.MaterialThemeUI]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:389)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:384)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerChameleon(ActionManagerImpl.java:1308)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.addToMap(ActionManagerImpl.java:1278)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1247)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerOrReplaceActionInner(ActionManagerImpl.java:732)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionElement(ActionManagerImpl.java:705)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processGroupElement(ActionManagerImpl.java:859)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.java:517)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerActions(ActionManagerImpl.java:197)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:174)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:771)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:49)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:37)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:64)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:488)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:471)
	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:30)
	at com.jetbrains.python.PyCharmCorePluginConfigurator.componentsInitialized(PyCharmCorePluginConfigurator.java:61)
	at com.intellij.idea.ApplicationLoader$callAppInitialized$2$1.run(ApplicationLoader.kt:488)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

[material-confs.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/6348886/material-confs.zip)
![Screenshot at 2021-04-21 10-25-56](https://user-images.githubusercontent.com/7573523/115514603-f1283f80-a28c-11eb-91e3-67b9895d61f7.png)

**Comment by mallowigi** [comment]
You can't use Material Theme UI and Material Theme UI Lite together. However, you have a good point in a way that I should print a message when there is such a case.

**Comment by RecNes** [comment]
Oooh! I didn't realized both plugin's are installed. Thank you.
