### ISSUE TITLE
null pointer exception

### ISSUE THREAD

**Issue by pfn** [ChrisRM/material-theme-jetbrains#175]
```
Worker exited due to exception
java.lang.NullPointerException
	at com.chrisrm.idea.icons.VirtualFileInfo.getFileType(VirtualFileInfo.java:24)
	at com.chrisrm.idea.icons.TypeAssociation.matches(TypeAssociation.java:9)
	at com.chrisrm.idea.icons.Associations.findAssociationForFile(Associations.java:47)
	at com.chrisrm.idea.icons.MTFileIconProvider.getIcon(MTFileIconProvider.java:25)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:122)
	at com.intellij.psi.impl.ElementBase.access$000(ElementBase.java:51)
	at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:62)
	at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:55)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:287)
	at com.intellij.ui.DeferredIconImpl$2$1$1.run(DeferredIconImpl.java:158)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:122)
	at com.intellij.ui.DeferredIconImpl$2$1.run(DeferredIconImpl.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$2.run(ProgressIndicatorUtils.java:80)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$5.run(ProgressIndicatorUtils.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:77)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:102)
	at com.intellij.ui.DeferredIconImpl$2.run(DeferredIconImpl.java:152)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pfn** [comment]
probably a dupe of #172
