### ISSUE TITLE
PhpStorm 2021.2/IDEA 2021.2 throws exception: java.util.MissingResourceException: Registry key ide.new.stripes.ui is not defined

### ISSUE THREAD

**Issue by MaXal** [ChrisRM/material-theme-jetbrains#1757]
Reproduced on version `6.5.0`.

The 2021.2 EAP for IntelliJ-based IDEs will start soon and the following exception will be thrown on each app exit:
```
java.util.MissingResourceException: Registry key ide.new.stripes.ui is not defined
	at com.intellij.openapi.util.registry.Registry.getBundleValue(Registry.java:156)
	at com.intellij.openapi.util.registry.RegistryValue.resetToDefault(RegistryValue.java:283)
	at com.mallowigi.idea.MTThemeManager.cleanRegistry(MTThemeManager.java:753)
	at com.mallowigi.idea.MTApplicationComponent.cleanRegistry(MTApplicationComponent.java:90)
	at com.mallowigi.idea.MTApplicationComponent.disposeComponent(MTApplicationComponent.java:86)
	at com.mallowigi.idea.MTApplicationComponent.appClosing(MTApplicationComponent.java:82)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:642)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy34.appClosing(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:615)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:595)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:575)
```

**Comment by mallowigi** [comment]
Which version is it ?

**Comment by mallowigi** [comment]
Is there a way i can test it before the release?

**Comment by mallowigi** [comment]
nvm found it

**Comment by mallowigi** [comment]
@MaXal I used
IntelliJ IDEA 2021.2 EAP (Ultimate Edition)
Build #IU-212.3116.5, built on May 20, 2021

But I couldn't reproduce.
