### ISSUE TITLE
An exception is thrown when I click File->Invalidate Caches->Invalidate and Restart

### ISSUE THREAD

**Issue by jmatias** [ChrisRM/material-theme-jetbrains#1771]
An exception is thrown when I click File->Invalidate Caches->Invalidate and Restart

```
java.util.MissingResourceException: Registry key ide.new.stripes.ui is not defined
	at com.intellij.openapi.util.registry.Registry.getBundleValue(Registry.java:156)
	at com.intellij.openapi.util.registry.RegistryValue.resetToDefault(RegistryValue.java:283)
	at com.mallowigi.idea.MTThemeManager.cleanRegistry(MTThemeManager.java:753)
	at com.mallowigi.idea.MTApplicationComponent.cleanRegistry(MTApplicationComponent.java:90)
	at com.mallowigi.idea.MTApplicationComponent.disposeComponent(MTApplicationComponent.java:86)
```
<details>
<summary>
Expand this block for the full stacktrace
</summary>

```stacktrace
java.util.MissingResourceException: Registry key ide.new.stripes.ui is not defined
	at com.intellij.openapi.util.registry.Registry.getBundleValue(Registry.java:156)
	at com.intellij.openapi.util.registry.RegistryValue.resetToDefault(RegistryValue.java:283)
	at com.mallowigi.idea.MTThemeManager.cleanRegistry(MTThemeManager.java:753)
	at com.mallowigi.idea.MTApplicationComponent.cleanRegistry(MTApplicationComponent.java:90)
	at com.mallowigi.idea.MTApplicationComponent.disposeComponent(MTApplicationComponent.java:86)
	at com.mallowigi.idea.MTApplicationComponent.appClosing(MTApplicationComponent.java:82)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:642)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy49.appClosing(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:574)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:554)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:543)
	at com.intellij.openapi.application.ex.ApplicationEx.exit(ApplicationEx.java:73)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.lambda$initMacApplication$3(MacOSApplicationProvider.java:86)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.lambda$submit$8(MacOSApplicationProvider.java:180)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:793)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:349)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:905)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:435)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:793)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:483)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

</details>

### Environment

```
IntelliJ IDEA 2021.2 EAP (Ultimate Edition)
Build #IU-212.3724.25, built on June 4, 2021
Expiration date: July 4, 2021
Runtime version: 11.0.11+9-b1481.1 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry: actionSystem.cache.data=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.fwdekker.randomness (2.7.0), com.intellij.plugins.macoskeymap (211.6432.7), com.jetbrains.plugins.ini4idea (212.3724.3), com.kagof.pokeprogress (1.5.0), com.mallowigi (37.0), de.netnexus.camelcaseplugin (3.0.8), net.seesharpsoft.intellij.plugins.csv (2.16.4), org.intellij.RegexpTester (1.0.8), org.intellij.plugins.hcl (0.7.10), org.jetbrains.plugins.go-template (212.3724.3), com.microsoft.vso.idea (1.161.1), mobi.hsz.idea.gitignore (4.1.1), name.kropp.intellij.makefile (212.3724.3), org.jetbrains.plugins.vagrant (212.3724.3), socrates.tabshifter (0.30), com.intellij.kubernetes (212.3724.25), com.godwin.json.parser (1.4.2), lermitage.intellij.extra.icons (1.55.0.203), Pythonid (212.3724.25), org.jetbrains.plugins.ruby (212.3724.21), org.jetbrains.plugins.go (212.3724.21), org.jfrog.idea (1.8.1), org.intellij.scala (2021.2.9), com.intellij.bigdatatools (212.3724.8), izhangzhihao.rainbow.brackets (6.17), nl.rubensten.texifyidea (0.7.7), com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.11.1)
Kotlin: 212-1.4.32-release-IJ3724.25
``` 

Plugin configuration (`material_theme.xml`)

```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="compactMenus" value="true" />
    <option name="compactStatusBar" value="true" />
    <option name="compactTables" value="true" />
    <option name="contrastMode" value="true" />
    <option name="highContrast" value="true" />
    <option name="styledDirectories" value="true" />
    <option name="borderedButtons" value="true" />
    <option name="compactDropdowns" value="true" />
    <option name="compactSidebar" value="true" />
    <option name="isCompactMenus" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="isStyledDirectories" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="rightTreeIndent" value="6" />
    <option name="settingsSelectedTab" value="2" />
    <option name="tabsHeight" value="42" />
    <option name="accentColor" value="2979ff" />
    <option name="selectedTheme" value="ONE_DARK" />
    <option name="userId" value="xxxxxx" />
    <option name="version" value="6.4.2.1" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
I've already fixed that. Please update to the latest version

**Comment by jmatias** [comment]
@mallowigi  My apologies. I think I gave you an outdated version of the `material_theme.xml`.  I actually have the latest version.

![image](https://user-images.githubusercontent.com/1302269/120884052-bf560880-c5ae-11eb-80ac-ae5ded40e970.png)

**Comment by mallowigi** [comment]
Weird that it doesn't propose you the latest version. It should be 6.5.2-2021.2

https://plugins.jetbrains.com/plugin/8006-material-theme-ui/versions

**Comment by jmatias** [comment]
@mallowigi 

![image](https://user-images.githubusercontent.com/1302269/120894925-cac62580-c5e8-11eb-9e0e-833694b2f730.png)

**Comment by mallowigi** [comment]
> Weird that it doesn't propose you the latest version. It should be **6.5.2-2021.2**
> 
> [plugins.jetbrains.com/plugin/8006-material-theme-ui/versions](https://plugins.jetbrains.com/plugin/8006-material-theme-ui/versions)

**Comment by ashleysommer** [comment]
I'm seeing this same exception in v6.6.0
(let me know if this is actually a different exception)
![image](https://user-images.githubusercontent.com/402468/132143898-83c88627-24a8-420e-a2c0-c547c36ea35f.png)

**Comment by mallowigi** [comment]
You're using an outdated version

**Comment by ashleysommer** [comment]
Yeah, I got the update for 6.8.1 today, thanks. Issue is no longer appearing.
