### ISSUE TITLE
Error when opening DataGrip

### ISSUE THREAD

**Issue by matiux** [ChrisRM/material-theme-jetbrains#1779]
Immediately after opening the program, this error occurs. I don't even have time to click anywhere:

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.ide.ui.laf.darcula.DarculaLaf.applySystemFonts(DarculaLaf.java:163)
	at com.intellij.ide.ui.laf.darcula.DarculaLaf.getDefaults(DarculaLaf.java:134)
	at com.mallowigi.idea.lafs.MTDarkLaf.getDefaults(MTDarkLaf.java:87)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:592)
	at com.mallowigi.idea.themes.themes.MTAbstractTheme.setLookAndFeel(MTAbstractTheme.java:136)
	at com.mallowigi.idea.themes.themes.MTAbstractTheme.activate(MTAbstractTheme.java:127)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.java:356)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.java:325)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.java:340)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.java:99)
	at com.mallowigi.idea.MTLafComponent.lambda$initComponent$0(MTLafComponent.java:121)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:793)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$7(ApplicationImpl.java:450)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:905)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:435)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:793)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:483)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException
	at java.desktop/com.sun.java.swing.plaf.gtk.GTKLookAndFeel.initSystemColorDefaults(GTKLookAndFeel.java:1311)
	at java.desktop/com.sun.java.swing.plaf.gtk.GTKLookAndFeel.getDefaults(GTKLookAndFeel.java:271)
	... 45 more
```

DataGrip 2021.2 EAP
Build #DB-212.3724.3, built on June 1, 2021
DataGrip EAP User
Expiration date: July 1, 2021
Runtime version: 11.0.11+9-b1481.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.12.9-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.intellij.laf.enable.animation=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI (6.6.0-2021.2), com.mallowigi (37.0), org.intellij.plugins.markdown (212.3724.3)
Current Desktop: KDE

**Comment by mallowigi** [comment]
Can you provide more information, such as which theme are you using?
