### ISSUE TITLE
 java.lang.NoClassDefFoundError after Installation

### ISSUE THREAD

**Issue by reesz** [ChrisRM/material-theme-jetbrains#179]
This is in addition to: #135 
After trying to install the build 0.1.8 via zip or repository, I'm getting this new error in PHPStorm 7.1.4:

> Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart PhpStorm.
>  java.lang.NoClassDefFoundError: com/intellij/util/ui/JBUI
>     at com.chrisrm.idea.MTLaf.patchStyledEditorKit(MTLaf.java:140)
>     at com.chrisrm.idea.MTLaf.getDefaults(MTLaf.java:88)
>     at javax.swing.UIManager.setLookAndFeel(UIManager.java:520)
>     at com.chrisrm.idea.actions.MTSwitchTheme.setTheme(MTSwitchTheme.java:25)
>     at com.chrisrm.idea.MTColorScheme.initComponent(MTColorScheme.java:19)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:548)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:590)
>     at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:225)
>     at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:212)
>     at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:199)
>     at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:121)
>     at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:372)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:112)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:89)
>     at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:87)
>     at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:509)
>     at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:150)
>     at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:59)
>     at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
>     at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
>     at java.awt.EventQueue.access$400(EventQueue.java:82)
>     at java.awt.EventQueue$2.run(EventQueue.java:676)
>     at java.awt.EventQueue$2.run(EventQueue.java:674)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
>     at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
>     at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
>     at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
>     at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
>     at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
>     at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
>     at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
>     at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
> Caused by: java.lang.ClassNotFoundException: com.intellij.util.ui.JBUI PluginClassLoader[com.chrisrm.idea.MaterialThemeUI, 0.1.8]
>     at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
>     ... 36 more<

Is there a way to fix this error? Thanks.

**Comment by sicdigital** [comment]
I have the exact same issue

**Comment by lbaroVPG** [comment]
Same issue for me too...

**Comment by aelor** [comment]
+1

**Comment by ChrisRM** [comment]
Can you try the newest build and let me know?

**Comment by reesz** [comment]
Here's what I got after updating from within the Plugins-Section:

> Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.NoClassDefFoundError: com/intellij/util/ui/JBUI
    at com.chrisrm.idea.MTLaf.patchStyledEditorKit(MTLaf.java:143)
    at com.chrisrm.idea.MTLaf.getDefaults(MTLaf.java:95)
    at javax.swing.UIManager.setLookAndFeel(UIManager.java:520)
    at com.chrisrm.idea.actions.MTSwitchTheme.setTheme(MTSwitchTheme.java:25)
    at com.chrisrm.idea.MTColorScheme.initComponent(MTColorScheme.java:19)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:548)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:590)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:225)
    at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:212)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:199)
    at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:121)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:372)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:112)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:89)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:87)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:509)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:150)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:59)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.ui.JBUI PluginClassLoader[com.chrisrm.idea.MaterialThemeUI, 0.2.0]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 36 more

**Comment by ChrisRM** [comment]
What version of the IDE are you running?

**Comment by reesz** [comment]
I'm using PHPStorm 7.1.5.

**Comment by sicdigital** [comment]
This is what I got after update. **Webstorm 9.0.4**

`Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart WebStorm.

java.lang.NoClassDefFoundError: com/intellij/util/ui/JBUI
    at com.chrisrm.idea.MTLaf.patchStyledEditorKit(MTLaf.java:143)
    at com.chrisrm.idea.MTLaf.getDefaults(MTLaf.java:95)
    at javax.swing.UIManager.setLookAndFeel(UIManager.java:520)
    at com.chrisrm.idea.actions.MTSwitchTheme.setTheme(MTSwitchTheme.java:25)
    at com.chrisrm.idea.MTColorScheme.initComponent(MTColorScheme.java:19)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:567)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:609)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:236)
    at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:223)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:210)
    at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:124)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:358)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:115)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:110)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:511)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:493)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:158)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:66)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:364)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.ui.JBUI PluginClassLoader[com.chrisrm.idea.MaterialThemeUI, 0.2.0]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 35 more
`

**Comment by stevematdavies** [comment]
Latest webstorm 2017.2 this is also an issue

**Comment by mallowigi** [comment]
which version of the theme?

**Comment by stevematdavies** [comment]
Latest

**Comment by mallowigi** [comment]
can you post here the list of plugins you use?

**Comment by stevematdavies** [comment]
Not presently, it's a company setup. I've removed the material ui theme for
now, I don't have time to be hacking UIs. I'll get back to it when I have
more time

**Comment by mallowigi** [comment]
https://github.com/mallowigi/material-theme-jetbrains-eap/issues/112
