### ISSUE TITLE
Code With Me not launching due to Material Theme exception

### ISSUE THREAD

**Issue by sebastiaanluca** [ChrisRM/material-theme-jetbrains#1832]
### Summary

When I try to launch Code With Me via the Tools menu, it throws an exception saying it can't find a Material Theme icon.

### Expected behavior

It launches Code With Me.

### Actual behavior

It doesn't launch Code With Me and nothing happens. It doesn't show the exception either, I have to find it manually via the log.

<details>
<summary>The exception in the log</summary>

```
2021-09-21 14:22:23,154 [  31589]  ERROR - ctionSystem.impl.ActionUpdater - PhpStorm 2021.2.2  Build #PS-212.5284.49 
2021-09-21 14:22:23,154 [  31589]  ERROR - ctionSystem.impl.ActionUpdater - JDK: 11.0.12; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-09-21 14:22:23,154 [  31589]  ERROR - ctionSystem.impl.ActionUpdater - OS: Mac OS X 
2021-09-21 14:22:23,154 [  31589]  ERROR - ctionSystem.impl.ActionUpdater - Plugin to blame: Material Theme UI version: 6.8.2 
2021-09-21 14:22:23,154 [  31589]  ERROR - ctionSystem.impl.ActionUpdater - Last Action: CWMHostShowPopupAction 
2021-09-21 14:22:23,155 [  31590]  ERROR - ctionSystem.impl.ActionUpdater - Exception 'java.lang.NullPointerException: icon must not be null' was reported 20 times 
2021-09-21 14:22:23,155 [  31590]  ERROR - ctionSystem.impl.ActionUpdater - update failed for AnAction(com.mallowigi.idea.actions.MTHighContrastAction, id=MTHighContrastAction) with text=Toggle High Contrast 
java.lang.NullPointerException: icon must not be null
	at com.mallowigi.idea.actions.MTToggleAction.update(MTToggleAction.kt:58)
	at com.mallowigi.idea.actions.MTHighContrastAction.update(MTHighContrastAction.kt:44)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:130)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:144)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:584)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$7(ActionUpdater.java:132)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$9(ActionUpdater.java:187)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$10(ActionUpdater.java:185)
	at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:45)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupFastTrack$3(Utils.java:221)
	at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:524)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupFastTrack(Utils.java:219)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:149)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:243)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenuInner(ActionMenu.java:345)
	at com.intellij.openapi.actionSystem.impl.Utils.performWithRetries(Utils.java:564)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:324)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:287)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.stateChanged(ActionMenu.java:225)
	at java.desktop/javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:352)
	at java.desktop/javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:234)
	at java.desktop/javax.swing.JMenu.setSelected(JMenu.java:291)
	at java.desktop/com.apple.laf.ScreenMenu$2.run(ScreenMenu.java:137)
	at java.desktop/sun.lwawt.macosx.LWCToolkit$CancelableRunnable.run(LWCToolkit.java:677)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/sun.awt.AWTThreading$4.dispatch(AWTThreading.java:218)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-09-21 14:22:23,155 [  31590]  ERROR - ctionSystem.impl.ActionUpdater - PhpStorm 2021.2.2  Build #PS-212.5284.49 
2021-09-21 14:22:23,155 [  31590]  ERROR - ctionSystem.impl.ActionUpdater - JDK: 11.0.12; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-09-21 14:22:23,155 [  31590]  ERROR - ctionSystem.impl.ActionUpdater - OS: Mac OS X 
2021-09-21 14:22:23,156 [  31591]  ERROR - ctionSystem.impl.ActionUpdater - Plugin to blame: Material Theme UI version: 6.8.2 
2021-09-21 14:22:23,156 [  31591]  ERROR - ctionSystem.impl.ActionUpdater - Last Action: CWMHostShowPopupAction 
2021-09-21 14:22:36,794 [  45229]  ERROR - ctionSystem.impl.ActionUpdater - Exception 'java.lang.NullPointerException: icon must not be null' was reported 10 times 
2021-09-21 14:22:36,795 [  45230]  ERROR - ctionSystem.impl.ActionUpdater - Exception 'java.lang.NullPointerException: icon must not be null' was reported 10 times 
2021-09-21 14:22:36,803 [  45238]  ERROR - ctionSystem.impl.ActionUpdater - Exception 'java.lang.NullPointerException: icon must not be null' was reported 10 times 
2021-09-21 14:22:36,804 [  45239]  ERROR - ctionSystem.impl.ActionUpdater - Exception 'java.lang.NullPointerException: icon must not be null' was reported 10 times 
```

</details>

### Steps to reproduce (if needed)

1. Click Tools in the menu
2. Click on Code With Me

### Environment

PhpStorm 2021.2.2
Build #PS-212.5284.49, built on September 16, 2021
Runtime version: 11.0.12+7-b1504.28 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: ParNew, ConcurrentMarkSweep
Memory: 12221M
Cores: 8
Registry: ide.mac.message.dialogs.as.sheets=false, search.everywhere.toolwindows=false, run.processes.with.pty=TRUE, search.everywhere.configurations=false, ide.allow.merge.buttons=false, ide.tooltip.initialDelay=0, ide.balloon.shadow.size=0, ide.images.show.chessboard=true

**Comment by mallowigi** [comment]
Please open issues in the new repository
