### ISSUE TITLE
An exception is thrown when I open DataSpell-EAP with Material UI enabled

### ISSUE THREAD

**Issue by jmatias** [ChrisRM/material-theme-jetbrains#1833]
### Summary

Exceptions are thrown when I open DataSpell-EAP with Material UI enabled.

#### First exception:

```
java.lang.NullPointerException: inStream parameter is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.util.Properties.load(Properties.java:406)
	at com.mallowigi.idea.lafs.MTDarculaLaf.loadDefaults(MTDarculaLaf.java:107)
	at com.intellij.ide.ui.laf.darcula.DarculaLaf.initIdeaDefaults(DarculaLaf.java:194)
	at com.intellij.ide.ui.laf.darcula.DarculaLaf.getDefaults(DarculaLaf.java:126)
	at com.mallowigi.idea.lafs.MTDarculaLaf.getDefaults(MTDarculaLaf.java:88)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:592)
	at com.mallowigi.idea.themes.themes.MTNativeTheme.setLookAndFeel(MTNativeTheme.java:146)
        ...
```
<details>
<summary>
Expand this block for the full stacktrace
</summary>

```stacktrace
java.lang.NullPointerException: inStream parameter is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.util.Properties.load(Properties.java:406)
	at com.mallowigi.idea.lafs.MTDarculaLaf.loadDefaults(MTDarculaLaf.java:107)
	at com.intellij.ide.ui.laf.darcula.DarculaLaf.initIdeaDefaults(DarculaLaf.java:194)
	at com.intellij.ide.ui.laf.darcula.DarculaLaf.getDefaults(DarculaLaf.java:126)
	at com.mallowigi.idea.lafs.MTDarculaLaf.getDefaults(MTDarculaLaf.java:88)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:592)
	at com.mallowigi.idea.themes.themes.MTNativeTheme.setLookAndFeel(MTNativeTheme.java:146)
	at com.mallowigi.idea.themes.themes.MTAbstractTheme.activate(MTAbstractTheme.java:127)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.java:358)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.java:327)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.java:103)
	at com.mallowigi.idea.MTLafComponent.lambda$initComponent$0(MTLafComponent.java:123)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:797)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$7(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:797)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
</details>

<img width="859" alt="image" src="https://user-images.githubusercontent.com/1302269/135049763-016d4304-382b-434e-9177-772890f3b740.png">

### Environment

```
DataSpell 2021.3 EAP 18.1
Build #PD-213.2094.12, built on September 9, 2021
JetBrains DataSpell EAP User
Expiration date: November 8, 2021
Runtime version: 11.0.12+7-b1626.3 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 12
Registry:
    ide.balloon.shadow.size=0
    python.scientific.show_help_window=false
    python.scientific.always_use_sci_view=true

Non-Bundled Plugins:
    net.seesharpsoft.intellij.plugins.csv (2.17.1)
    name.kropp.intellij.makefile (213.2094.12)
    lermitage.intellij.extra.icons (1.62.0.203)
    com.samvtran.plugins.macosforallkeymap (2.0.0)
    com.jetbrains.plugins.ini4idea (213.2094.12)
    com.chrisrm.idea.MaterialThemeUI (6.9.0)
    String Manipulation (8.15.203.000.3)
    izhangzhihao.rainbow.brackets (6.21)
    mobi.hsz.idea.gitignore (4.2.0)
    com.mallowigi (41.1.0)
    Docker (213.2094.12)


``` 

Plugin configuration (`material_theme.xml`)

```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="premium" value="true" />
    <option name="accentColor" value="416a9b" />
    <option name="selectedTheme" value="NATIVE" />
    <option name="userId" value="-1da22da5:17c10b613cf:-8000" />
    <option name="version" value="6.9.0" />
  </component>
</application>

**Comment by mallowigi** [comment]
Please open issues on in the `material-theme-issues` repository.

**Comment by jmatias** [comment]
@mallowigi  Done.

https://github.com/mallowigi/material-theme-issues/issues/25
