### ISSUE TITLE
Exception after updating to version 42.0.0

### ISSUE THREAD

**Issue by yonifra** [ChrisRM/material-theme-jetbrains#1835]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, first, read the README and check if this is a known issue.

Then, check on the Github issues if a similar issue has been posted.

If nothing of the sort, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary

Got a `java.lang.ClassCastException` upon updating to version 42.0.0 in latest WebStorm IDE

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce (if needed)

1. Just use the update arrow in the top right corner of WebStorm, and you'll get the exception

Stack trace:
```
java.lang.ClassCastException: class com.mallowigi.config.AtomFileIconsConfig cannot be cast to class com.mallowigi.config.AtomFileIconsConfig (com.mallowigi.config.AtomFileIconsConfig is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @6e40a105; com.mallowigi.config.AtomFileIconsConfig is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @4fa933b9)
	at com.mallowigi.config.AtomFileIconsConfig$Companion.getInstance(AtomFileIconsConfig.kt:404)
	at com.mallowigi.icons.HiddenIconProvider.getIcon(HiddenIconProvider.kt:46)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:222)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.java:155)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.lambda$updateFileIconAsynchronously$7(EditorsSplitters.java:430)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:407)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)```
```

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac) Mac
* IntelliJ Product + version (IDEA, RubyMine...) WebStorm 2021.2.2
Build #WS-212.5284.41, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: ParNew, ConcurrentMarkSweep
Memory: 4112M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.intellij.plugins.vscodekeymap (212.3116.29), mobi.hsz.idea.gitignore (4.2.0), com.mallowigi (42.0.0), com.chrisrm.idea.MaterialThemeUI (6.9.0), izhangzhihao.rainbow.brackets (6.21)
* Plugin version 42.0.0
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

Note that not providing any of the required info will result of your issue being closed.

**Comment by yonifra** [comment]
Sorry, this is for another repo, not this one, closing
