### ISSUE TITLE
In rider and webstorm im getting Read access is allowed from inside read-action

### ISSUE THREAD

**Issue by khsd** [ChrisRM/material-theme-jetbrains#1841]
In rider and webstorm both latest stable version im getting the following exception random:
Details: Current thread: Thread[JetBrains.Debugger.Worker32c.exe,4,main] 717316106
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1465602746

java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:969)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.disableIndexUpToDateCheckInEdt(UniqueVFilePathBuilderImpl.java:182)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.lambda$getFilenameIndexModificationTracker$2(UniqueVFilePathBuilderImpl.java:126)
	at com.intellij.util.CachedValueBase.getTimeStamp(CachedValueBase.java:145)
	at com.intellij.psi.impl.PsiCachedValue.getTimeStamp(PsiCachedValue.java:132)
	at com.intellij.util.CachedValueBase.isDependencyOutOfDate(CachedValueBase.java:124)
	at com.intellij.psi.impl.PsiCachedValue.isDependencyOutOfDate(PsiCachedValue.java:112)
	at com.intellij.util.CachedValueBase.isUpToDate(CachedValueBase.java:114)
	at com.intellij.psi.impl.PsiCachedValue.isUpToDate(PsiCachedValue.java:106)
	at com.intellij.util.CachedValueBase.checkUpToDate(CachedValueBase.java:97)
	at com.intellij.util.CachedValueBase.getUpToDateOrNull(CachedValueBase.java:93)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:217)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFileNameBuilder(UniqueVFilePathBuilderImpl.java:99)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:70)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:40)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:46)
	at com.mallowigi.idea.tabs.MTEditorUpperTabs.getEditorTabTitle(MTEditorUpperTabs.java:155)
	at com.intellij.openapi.fileEditor.impl.EditorTabTitleProvider.getEditorTabTitle(EditorTabTitleProvider.java:22)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getEditorTabTitle(EditorTabPresentationUtil.java:21)
	at com.intellij.openapi.vfs.newvfs.VfsPresentationUtil.lambda$getPresentableNameForUI$0(VfsPresentationUtil.java:29)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:146)
	at com.intellij.openapi.vfs.newvfs.VfsPresentationUtil.getPresentableNameForUI(VfsPresentationUtil.java:29)
	at com.intellij.openapi.wm.impl.PlatformFrameTitleBuilder.getFileTitle(PlatformFrameTitleBuilder.java:43)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.titleLabel.ClassTitlePane.updatePath(ClassTitlePane.kt:38)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.titleLabel.SelectedEditorFilePath.updatePath(SelectedEditorFilePath.kt:258)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.titleLabel.SelectedEditorFilePath.updateTitlePaths(SelectedEditorFilePath.kt:121)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.titleLabel.SelectedEditorFilePath.updateProjectPath(SelectedEditorFilePath.kt:63)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.titleLabel.CustomDecorationPath$titleChangeListener$1.propertyChange(CustomDecorationPath.kt:58)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:334)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8754)
	at java.desktop/java.awt.Frame.setTitle(Frame.java:526)
	at com.intellij.openapi.wm.impl.IdeFrameImpl.doSetTitle(IdeFrameImpl.java:111)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper.updateTitle(ProjectFrameHelper.java:310)
	at com.intellij.openapi.wm.impl.WindowManagerImpl$2.configurationChanged(WindowManagerImpl.kt:107)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:642)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy81.configurationChanged(Unknown Source)
	at com.intellij.openapi.wm.impl.TitleInfoProvider$Companion.fireConfigurationChanged(TitleInfoProvider.kt:32)
	at com.intellij.openapi.wm.impl.simpleTitleParts.SimpleTitleInfoProvider.updateNotify(SimpleTitleInfoProvider.kt:39)
	at com.intellij.xdebugger.impl.ui.DebuggerTitleInfoProvider.access$updateNotify(DebuggerTitleInfoProvider.kt:15)
	at com.intellij.xdebugger.impl.ui.DebuggerTitleInfoProvider$DebuggerTitleInfoProviderService.checkState(DebuggerTitleInfoProvider.kt:69)
	at com.intellij.xdebugger.impl.ui.DebuggerTitleInfoProvider$DebuggerTitleInfoProviderService$addSubscription$1.currentSessionChanged(DebuggerTitleInfoProvider.kt:94)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy208.currentSessionChanged(Unknown Source)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.onActiveSessionChanged(XDebuggerManagerImpl.java:317)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.removeSession(XDebuggerManagerImpl.java:297)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.lambda$stopImpl$7(XDebugSessionImpl.java:945)
	at org.jetbrains.concurrency.DonePromise.onSuccess(promise.kt:349)
	at org.jetbrains.concurrency.DonePromise.onSuccess(promise.kt:318)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.stopImpl(XDebugSessionImpl.java:922)
	at com.intellij.xdebugger.impl.XDebugSessionImpl$1.processTerminated(XDebugSessionImpl.java:282)
	at jdk.internal.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:247)
	at com.sun.proxy.$Proxy8.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.lambda$notifyTerminated$2(ProcessHandler.java:205)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:280)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:188)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:184)
	at com.jetbrains.rider.debugger.DebuggerWorkerProcessHandler.access$notifyProcessTerminated(DebuggerWorkerProcessHandler.kt:22)
	at com.jetbrains.rider.debugger.DebuggerWorkerProcessHandler$2.processTerminated(DebuggerWorkerProcessHandler.kt:83)
	at jdk.internal.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:247)
	at com.sun.proxy.$Proxy8.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.lambda$notifyTerminated$2(ProcessHandler.java:205)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:280)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:188)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:184)
	at com.intellij.execution.process.KillableProcessHandler.notifyProcessTerminated(KillableProcessHandler.java:139)
	at com.jetbrains.rider.run.TerminalProcessHandler.notifyProcessTerminated(TerminalProcessHandler.kt:18)
	at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:61)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:205)
	at com.intellij.execution.process.BaseOSProcessHandler$1.lambda$startNotified$0(BaseOSProcessHandler.java:99)
	at com.intellij.execution.process.ProcessWaitFor.lambda$new$0(ProcessWaitFor.java:45)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.execution.process.ProcessWaitFor.lambda$new$1(ProcessWaitFor.java:23)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by mallowigi** [comment]
I know about this issue but this is not something that bothers day to day work so i'm closing it. Besides please use the material-theme-issues from now on, thanks.
