### ISSUE TITLE
IDE Fatal Error

### ISSUE THREAD

**Issue by pipnoz** [ChrisRM/material-theme-jetbrains#1843]
hi,
I have upgraded the community version of PyCharm 2021.3 EAP and now, every time I open the app this Ide Fatal Error appear.

Follows the entire error:

java.lang.NullPointerException: inStream parameter is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.util.Properties.load(Properties.java:406)
	at com.mallowigi.idea.lafs.MTDarculaLaf.loadDefaults(MTDarculaLaf.java:107)
	at com.intellij.ide.ui.laf.darcula.DarculaLaf.initIdeaDefaults(DarculaLaf.java:194)
	at com.intellij.ide.ui.laf.darcula.DarculaLaf.getDefaults(DarculaLaf.java:126)
	at com.mallowigi.idea.lafs.MTDarculaLaf.getDefaults(MTDarculaLaf.java:88)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:592)
	at com.mallowigi.idea.themes.themes.MTNativeTheme.setLookAndFeel(MTNativeTheme.java:146)
	at com.mallowigi.idea.themes.themes.MTAbstractTheme.activate(MTAbstractTheme.java:127)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.java:358)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.java:327)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.java:103)
	at com.mallowigi.idea.MTLafComponent.lambda$initComponent$0(MTLafComponent.java:123)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$7(ApplicationImpl.java:450)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at 
![pycharm_error](https://user-images.githubusercontent.com/6382511/140610123-8b219ba1-50bd-40af-bffb-4ebc697c5770.png)
com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by mallowigi** [comment]
Please stop opening issues here.
