### ISSUE TITLE
Error in Log  when Rider for UE starts under Linux 

### ISSUE THREAD

**Issue by LaurentOngaro** [ChrisRM/material-theme-jetbrains#1856]
The following message is shown in the Event log when Rider for UE starts under Linux 
The plugin seems to run fine

System: Linux Manjaro Gnome (Arch based) up to date
Rider version: Build #RDCPPP-213.5744.303, built on December 10, 2021
Material theme version: 6.12.2

`
java.lang.Throwable: 'ScrollBar.Transparent.hoverThumbBorderColor' is not found in java.util.PropertyResourceBundle@449f3738(messages.MaterialThemeBundle)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.BundleBase.useDefaultValue(BundleBase.java:167)
	at com.intellij.BundleBase.messageOrDefault(BundleBase.java:106)
	at com.intellij.AbstractBundle.getMessage(AbstractBundle.java:47)
	at com.mallowigi.idea.messages.MaterialThemeBundle.message(MaterialThemeBundle.kt:64)
	at com.mallowigi.idea.config.MTScrollbarsPage$Companion.addColorDescriptor(MTScrollbarsPage.kt:119)
	at com.mallowigi.idea.config.MTScrollbarsPage$Companion.access$addColorDescriptor(MTScrollbarsPage.kt:98)
	at com.mallowigi.idea.config.MTScrollbarsPage.<clinit>(MTScrollbarsPage.kt:110)
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:482)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:830)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.instantiateClass(XmlExtensionAdapter.java:99)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:116)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:66)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:489)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:437)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:264)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:35)
	at com.jetbrains.rd.platform.daemon.TextAttributesKeysStorage.n(TextAttributesKeysStorage.kt:36)
	at com.jetbrains.rd.platform.daemon.TextAttributesKeysStorage.register(TextAttributesKeysStorage.kt:27)
	at com.jetbrains.rd.platform.daemon.TextAttributesRegistrationHost.getTextAttributesKey(TextAttributesRegistrationHost.kt:39)
	at com.jetbrains.rdclient.daemon.components.FrontendHighlighterRegistrationHost.m(FrontendHighlighterRegistrationHost.kt:159)
	at com.jetbrains.rdclient.daemon.components.FrontendHighlighterRegistrationHost.access$patchIdeaColorsScheme(FrontendHighlighterRegistrationHost.kt:37)
	at com.jetbrains.rdclient.daemon.components.FrontendHighlighterRegistrationHost$handleDefaultRegistry$1.invoke(FrontendHighlighterRegistrationHost.kt:79)
	at com.jetbrains.rdclient.daemon.components.FrontendHighlighterRegistrationHost$handleDefaultRegistry$1.invoke(FrontendHighlighterRegistrationHost.kt:37)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.framework.impl.RdSignal.onWireReceived(RdSignal.kt:42)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:55)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:97)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:18)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:23)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

**Comment by mallowigi** [comment]
Please open issues in the new repository.

**Comment by LaurentOngaro** [comment]
Done!
I've followed the link to the plugin repo from the jetbrains message window (when you click on the event). 
IMO, the link should be fixed to avoid this kind of mistake

**Comment by mallowigi** [comment]
Thanks for the heads up, it was always bugging me how did people end up adding issues to the repository even though I changed it in the plugin page. I need to figure out why JB still has the old link.

--
Elior

**Comment by LaurentOngaro** [comment]
I'm happy to help!
