### ISSUE TITLE
NPE loading IDE

### ISSUE THREAD

**Issue by neclimdul** [ChrisRM/material-theme-jetbrains#1859]
### Summary
Got a NPE while loading my IDE today. restarting fixed everything so maybe some race condition?

```
java.lang.NullPointerException: getBorder(LIST_FOCUSED_S…CTION_BACKGROUND_PAINTER) must not be null
	at com.mallowigi.idea.utils.MTUI$List.getListFocusedSelectionPainter(MTUI.kt:201)
	at com.mallowigi.idea.ui.MTRowPainter.paint(MTRowPainter.kt:122)
	at com.intellij.ui.tree.ui.DefaultTreeUI.paint(DefaultTreeUI.java:254)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:800)
	at com.intellij.ui.treeStructure.Tree.paintComponent(Tree.java:330)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1077)
	at com.intellij.ui.treeStructure.Tree.paint(Tree.java:244)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:237)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5270)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1654)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1629)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1566)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:262)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1063)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:115)
	at java.desktop/java.awt.Container.paint(Container.java:2002)
	at java.desktop/java.awt.Window.paint(Window.java:3958)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.paint(DialogWrapperPeerImpl.java:803)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Expected behavior
Error free startup! :rofl:

### Actual behavior
Crash in log and half themed IDE.

### Steps to reproduce (if needed)
Don't have anything since it only happened once. Sorry.

### Environment
```
PhpStorm 2021.3.1
Build #PS-213.6461.83, built on December 29, 2021
Licensed to American Productivity & Quality Center / James Gilliland
Subscription is active until August 18, 2022.
Runtime version: 11.0.13+7-b1751.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.0-27-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1978M
Cores: 16
Registry:
    debugger.watches.in.variables=false
    search.everywhere.recent.at.top=false
    run.processes.with.pty=TRUE
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    some.awesome (1.14)
    nb-mind-map-idea (1.5.0)
    com.jetbrains.webstorm.web-assembly-plugin (1.4.213)
    org.intellij.plugins.hcl (0.7.14)
    com.intellij.ideolog (203.0.27.0)
    com.alayouni.ansiHighlight (1.2.4)
    mobi.hsz.idea.gitignore (4.3.0)
    de.espend.idea.php.phpunit (6.2)
    de.espend.idea.php.annotation (8.0.0)
    fr.adrienbrault.idea.symfony2plugin (0.23.213)
    de.espend.idea.php.drupal (0.5.1)
    de.espend.idea.laravel (0.15.4)
    NEON support (0.5.1)
    com.dmarcotte.handlebars (213.5744.190)
    com.chrisrm.idea.MaterialThemeUI (6.12.2)
    org.jetbrains.plugins.node-remote-interpreter (213.6461.6)
    ru.adelf.idea.dotenv (2021.3.0.213)

Current Desktop: GNOME
```

Config:
```
<application>
<component name="MaterialThemeConfig">
<option name="premium" value="true"/>
<option name="allowDataCollection" value="true"/>
<option name="accentColor" value="416a9b"/>
<option name="selectedTheme" value="NATIVE"/>
<option name="userId" value="-7e627b24:174b4285c67:-8000"/>
<option name="version" value="6.4.0.3"/>
</component>
</application>
```

note: JetBrains stores config in a new location so the instructions are out of date. Mine was at `.config/JetBrains/PhpStorm2021.3/options`

**Comment by mallowigi** [comment]
Light theme?

**Comment by mallowigi** [comment]
Please open issues in the new repository thank you.
