### ISSUE TITLE
intellij fails to launch when using dark theme and Version Control changes was last used

### ISSUE THREAD

**Issue by robertfreund** [ChrisRM/material-theme-jetbrains#187]
When opening IDE and Version Control is active start fails with below exception. This only affects Dark theme. I prefer the dark theme.

Current workaround I use is to remove Material Theme dir from plugins and launch intellij with Default theme.

intellij Ultimate 2016.1

2016-05-05 09:01:21,577 [ 354914]   INFO - roject.impl.ProjectManagerImpl - Fatal error initializing 'com.intellij.openapi.vcs.changes.ChangesViewI' 
com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.vcs.changes.ChangesViewI'
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:254)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:540)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:184)
	at com.intellij.lifecycle.PeriodicalTasksCloser.safeGetComponent(PeriodicalTasksCloser.java:52)
	at com.intellij.openapi.vcs.changes.ChangesViewManager.getInstance(ChangesViewManager.java:108)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.<init>(ChangeListManagerImpl.java:142)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:499)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at org.picocontainer.defaults.BasicComponentParameter.resolveInstance(BasicComponentParameter.java:77)
	at org.picocontainer.defaults.ComponentParameter.resolveInstance(ComponentParameter.java:114)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getConstructorArguments(ConstructorInjectionComponentAdapter.java:257)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:217)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:499)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at org.picocontainer.defaults.BasicComponentParameter.resolveInstance(BasicComponentParameter.java:77)
	at org.picocontainer.defaults.ComponentParameter.resolveInstance(ComponentParameter.java:114)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getConstructorArguments(ConstructorInjectionComponentAdapter.java:257)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:217)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:499)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:282)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:231)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$300(ProjectManagerImpl.java:68)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$8.compute(ProjectManagerImpl.java:531)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$8.compute(ProjectManagerImpl.java:527)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:198)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1424)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1644)
	at javax.swing.text.html.StyleSheet.getResolvedStyle(StyleSheet.java:1273)
	at javax.swing.text.html.StyleSheet.getRule(StyleSheet.java:276)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1424)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1503)
	at javax.swing.text.html.StyleSheet.getResolvedStyle(StyleSheet.java:1261)
	at javax.swing.text.html.StyleSheet.getRule(StyleSheet.java:253)
	at javax.swing.text.html.StyleSheet$ViewAttributeSet.<init>(StyleSheet.java:2673)
	at javax.swing.text.html.StyleSheet.getViewAttributes(StyleSheet.java:348)
	at javax.swing.text.html.ParagraphView.setPropertiesFromAttributes(ParagraphView.java:101)
	at javax.swing.text.ParagraphView.<init>(ParagraphView.java:59)
	at javax.swing.text.html.ParagraphView.<init>(ParagraphView.java:54)
	at javax.swing.text.html.HTMLEditorKit$HTMLFactory.create(HTMLEditorKit.java:1148)
	at javax.swing.text.CompositeView.loadChildren(CompositeView.java:112)
	at javax.swing.text.CompositeView.setParent(CompositeView.java:139)
	at javax.swing.text.html.BlockView.setParent(BlockView.java:72)
	at javax.swing.text.html.HTMLEditorKit$HTMLFactory$BodyBlockView.setParent(HTMLEditorKit.java:1327)
	at javax.swing.text.CompositeView.replace(CompositeView.java:217)
	at javax.swing.text.BoxView.replace(BoxView.java:181)
	at javax.swing.text.CompositeView.loadChildren(CompositeView.java:114)
	at javax.swing.text.CompositeView.setParent(CompositeView.java:139)
	at javax.swing.text.html.BlockView.setParent(BlockView.java:72)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setView(BasicTextUI.java:1328)
	at javax.swing.plaf.basic.BasicTextUI.setView(BasicTextUI.java:693)
	at javax.swing.plaf.basic.BasicTextUI.modelChanged(BasicTextUI.java:682)
	at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.propertyChange(BasicTextUI.java:1794)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8430)
	at javax.swing.text.JTextComponent.setDocument(JTextComponent.java:443)
	at javax.swing.JEditorPane.setEditorKit(JEditorPane.java:1058)
	at com.intellij.ui.components.JBLabel.setCopyable(JBLabel.java:268)
	at com.intellij.diff.util.DiffUtil.createMessagePanel(DiffUtil.java:297)
	at com.intellij.diff.impl.DiffRequestProcessor.<init>(DiffRequestProcessor.java:143)
	at com.intellij.diff.impl.DiffRequestProcessor.<init>(DiffRequestProcessor.java:104)
	at com.intellij.diff.impl.CacheDiffRequestProcessor.<init>(CacheDiffRequestProcessor.java:55)
	at com.intellij.openapi.vcs.changes.CacheChangeProcessor.<init>(CacheChangeProcessor.java:46)
	at com.intellij.openapi.vcs.changes.ChangesViewManager$MyChangeProcessor.<init>(ChangesViewManager.java:556)
	at com.intellij.openapi.vcs.changes.ChangesViewManager.<init>(ChangesViewManager.java:118)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:499)
	... 57 more

**Comment by robertfreund** [comment]
I just noticed this may be a duplicate of #184 . My Stacktrace is attached.

**Comment by ChrisRM** [comment]
Perfect @robertfreund, I was unable to reproduce this, but the stacktrace should make it easier to find out what's wrong. I'll push an update asap.

**Comment by ChrisRM** [comment]
@robertfreund Can you try [this build](https://github.com/ChrisRM/material-theme-jetbrains/raw/bug/184/Material%20Theme.zip)? Go to `Plugins` - `Install plugin from disk...` and select the zip you downloaded. #184

**Comment by robertfreund** [comment]
@ChrisRM  this one did not work with what appears to be same issue.

2016-05-05 12:40:42,781 [   1762]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: ASP (0.1), Android Support (10.1.5), Ant Support (1.0), Application Servers View (0.2.0), AspectJ Support (1.2), Bytecode Viewer (0.1), CFML Support (3.53), CSS Support (145.SNAPSHOT), CVS Integration (11), ClearCase Integration (2.0), Cloud Foundry integration (1.0), CloudBees integration (1.0), CoffeeScript (2.0), Copyright (8.1), Coverage (145.SNAPSHOT), Cucumber for Groovy (999.999), Cucumber for Java (999.999), DSM Analysis (1.0.0), Database Tools and SQL (1.0), Eclipse Integration (3.0), EditorConfig (145.597.3), Emma (145.SNAPSHOT), Flash/Flex Support (1.0), FreeMarker support (1.0), GWT Support (1.0), Geronimo Integration (1.0), Gherkin (999.999), Git Integration (8.1), GitHub (145.597.3), GlassFish Integration (1.0), Google App Engine Integration (1.1.4), Gradle (145.597.3), Grails (9.0), Groovy (9.0), Guice (8.0), HAML (145.SNAPSHOT), HTML Tools (2.0), Heroku integration (1.0), Hibernate Support (1.0), I18n for Java (145.597.3), IDEA CORE (145.SNAPSHOT), IntelliLang (8.0), J2ME (1.0), JBoss Arquillian Support (1.0), JBoss Drools Support (1.0), JBoss Integration (1.0), JBoss Seam Pageflow Support (1.0), JBoss Seam Pages Support (1.0), JBoss Seam Support (1.0), JBoss Support (1.0), JBoss jBPM (2.0.0), JSR45 Integration (1.0), JUnit (1.0), Java Bytecode Decompiler (145.SNAPSHOT), Java EE: Batch Applications (1.0), Java EE: Bean Validation Support (1.1), Java EE: Contexts and Dependency Injection (1.1), Java EE: EJB, JPA, Servlets (1.0), Java EE: JMS, JSON Processing, Concurrency, Transaction  (1.0), Java EE: Java Server Faces (2.2.X.), Java EE: RESTful Web Services (JAX-RS) (1.0), Java EE: Web Services (JAX-WS) (1.9), Java EE: WebSockets (1.0), Java Server Pages (JSP) Integration (1.0), JavaFX (1.0), JavaScript Debugger (1.0), JavaScript Intention Power Pack (0.9.4), JavaScript Support (1.0), Jetty Integration (1.0), Kotlin (1.0.1-release-IJ143-32), LESS support (145.SNAPSHOT), Maven Integration (145.597.3), Maven Integration Extension (145.SNAPSHOT), OpenShift integration (1.0), Osmorc (1.4.8), Perforce Integration (2.0), Persistence Frameworks Support (1.0), Playframework Support (1.0), Plugin DevKit (1.0), Properties Support (145.SNAPSHOT), QuirksMode (145.SNAPSHOT), REST Client (145.SNAPSHOT), Refactor-X (2.01), Remote Hosts Access (0.1), Resin Integration (8.1), SASS support (145.SNAPSHOT), SSH Remote Run (0.1), Settings Repository (145.597.3), Spring AOP/@AspectJ (1.0), Spring Batch (1.0), Spring Boot (1.0), Spring Data (1.0), Spring Integration Patterns (1.0), Spring MVC (1.0), Spring OSGi (1.0), Spring Security (1.0), Spring Support (1.0), Spring Web Flow (1.0), Spring Web Services (1.0), Spring WebSocket (1.0), Spy-js (145.SNAPSHOT), Struts 1.x (2.0), Struts 2 (1.0), Stylus support (999.999), Subversion Integration (1.1), TFS Integration (999.999), Tapestry support (1.0), Task Management (1.0), Terminal (0.1), TestNG-J (8.0), Thymeleaf (1.0), Time Tracking (1.0), Tomcat and TomEE Integration (1.0), UI Designer (145.597.3), UML Support (1.0), Vaadin Support (1.0), Velocity support (1.0), W3C Validators (2.0), WebLogic Integration (1.0), WebSphere Integration (1.0), XPathView + XSLT Support (4), XSLT-Debugger (1.4), YAML (145.SNAPSHOT), ZKM-Unscramble (1.0), dmServer Support (0.9.5), hg4idea (10.0) 
2016-05-05 12:40:42,781 [   1762]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: .ignore (1.3.3), AWS CloudFormation support (0.4.22), AWS Manager (1.0.5), AngularJS (145.596.9), Apache config (.htaccess) support (145.258.2), BashSupport (1.5.5.145), Docker integration (2.2.0), File Watchers (145.28), Go (0.11.1337), Google Protocol Buffers support (0.5.9), JavaScript.next Support Plugin (1.2.0), LiveEdit (145.9), Markdown (0.9.7), Material Theme UI (0.1.8), Python (2016.1.145.86), Thrift Support (0.9.5) 
2016-05-05 12:40:42,781 [   1762]   INFO - llij.ide.plugins.PluginManager - Disabled plugins: C/C++ (0.8 build 8) 
2016-05-05 12:40:43,338 [   2319]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=500; buffer=10; max=705 
2016-05-05 12:40:43,406 [   2387]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: /Applications/IntelliJ IDEA.app/Contents/bin/fsnotifier 
2016-05-05 12:40:43,413 [   2394]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2016-05-05 12:40:44,122 [   3103]   INFO -     #com.intellij.util.ui.JBUI - UI scale factor changed: 1.25 
2016-05-05 12:40:44,316 [   3297]   INFO -   #com.intellij.AbstractBundle - Cannot load resource bundle from *.properties file, falling back to slow class loading: com.intellij.javaee.heroku.cloud.HerokuBundle 
2016-05-05 12:40:44,362 [   3343]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2016-05-05 12:40:44,391 [   3372]   INFO - gs.impl.UpdateCheckerComponent - channel: release 
2016-05-05 12:40:45,856 [   4837]   INFO - plication.impl.ApplicationImpl - 112 application components initialized in 3746 ms 
2016-05-05 12:40:45,875 [   4856]   INFO - .intellij.idea.IdeaApplication - App initialization took 5329 ms 
2016-05-05 12:40:46,206 [   5187]   INFO - ellij.project.impl.ProjectImpl - 27 project components initialized in 268 ms 
2016-05-05 12:40:46,207 [   5188]   INFO - le.impl.ModuleManagerComponent - 0 module(s) loaded in 0 ms 
2016-05-05 12:40:46,810 [   5791]   WARN - om.intellij.util.ProfilingUtil - Profiling agent is not enabled. Add -agentlib:yjpagent to idea.vmoptions if necessary to profile IDEA. 
2016-05-05 12:40:46,949 [   5930]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.openapi.actionSystem.impl.ActionPreloader@43fe8201 
2016-05-05 12:40:47,794 [   6775]   INFO - roject.impl.ProjectManagerImpl - Fatal error initializing 'com.intellij.openapi.vcs.changes.ChangesViewI' 
com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.vcs.changes.ChangesViewI'
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:254)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:540)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:184)
	at com.intellij.lifecycle.PeriodicalTasksCloser.safeGetComponent(PeriodicalTasksCloser.java:52)
	at com.intellij.openapi.vcs.changes.ChangesViewManager.getInstance(ChangesViewManager.java:108)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.<init>(ChangeListManagerImpl.java:142)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:499)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at org.picocontainer.defaults.BasicComponentParameter.resolveInstance(BasicComponentParameter.java:77)
	at org.picocontainer.defaults.ComponentParameter.resolveInstance(ComponentParameter.java:114)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getConstructorArguments(ConstructorInjectionComponentAdapter.java:257)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:217)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:499)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at org.picocontainer.defaults.BasicComponentParameter.resolveInstance(BasicComponentParameter.java:77)
	at org.picocontainer.defaults.ComponentParameter.resolveInstance(ComponentParameter.java:114)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getConstructorArguments(ConstructorInjectionComponentAdapter.java:257)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:217)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:499)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:282)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:231)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$300(ProjectManagerImpl.java:68)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$8.compute(ProjectManagerImpl.java:531)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$8.compute(ProjectManagerImpl.java:527)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:198)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1424)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1644)
	at javax.swing.text.html.StyleSheet.getResolvedStyle(StyleSheet.java:1273)
	at javax.swing.text.html.StyleSheet.getRule(StyleSheet.java:276)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1424)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1503)
	at javax.swing.text.html.StyleSheet.getResolvedStyle(StyleSheet.java:1261)
	at javax.swing.text.html.StyleSheet.getRule(StyleSheet.java:253)
	at javax.swing.text.html.StyleSheet$ViewAttributeSet.<init>(StyleSheet.java:2673)
	at javax.swing.text.html.StyleSheet.getViewAttributes(StyleSheet.java:348)
	at javax.swing.text.html.ParagraphView.setPropertiesFromAttributes(ParagraphView.java:101)
	at javax.swing.text.ParagraphView.<init>(ParagraphView.java:59)
	at javax.swing.text.html.ParagraphView.<init>(ParagraphView.java:54)
	at javax.swing.text.html.HTMLEditorKit$HTMLFactory.create(HTMLEditorKit.java:1148)
	at javax.swing.text.CompositeView.loadChildren(CompositeView.java:112)
	at javax.swing.text.CompositeView.setParent(CompositeView.java:139)
	at javax.swing.text.html.BlockView.setParent(BlockView.java:72)
	at javax.swing.text.html.HTMLEditorKit$HTMLFactory$BodyBlockView.setParent(HTMLEditorKit.java:1327)
	at javax.swing.text.CompositeView.replace(CompositeView.java:217)
	at javax.swing.text.BoxView.replace(BoxView.java:181)
	at javax.swing.text.CompositeView.loadChildren(CompositeView.java:114)
	at javax.swing.text.CompositeView.setParent(CompositeView.java:139)
	at javax.swing.text.html.BlockView.setParent(BlockView.java:72)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setView(BasicTextUI.java:1328)
	at javax.swing.plaf.basic.BasicTextUI.setView(BasicTextUI.java:693)
	at javax.swing.plaf.basic.BasicTextUI.modelChanged(BasicTextUI.java:682)
	at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.propertyChange(BasicTextUI.java:1794)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8430)
	at javax.swing.text.JTextComponent.setDocument(JTextComponent.java:443)
	at javax.swing.JEditorPane.setEditorKit(JEditorPane.java:1058)
	at com.intellij.ui.components.JBLabel.setCopyable(JBLabel.java:268)
	at com.intellij.diff.util.DiffUtil.createMessagePanel(DiffUtil.java:297)
	at com.intellij.diff.impl.DiffRequestProcessor.<init>(DiffRequestProcessor.java:143)
	at com.intellij.diff.impl.DiffRequestProcessor.<init>(DiffRequestProcessor.java:104)
	at com.intellij.diff.impl.CacheDiffRequestProcessor.<init>(CacheDiffRequestProcessor.java:55)
	at com.intellij.openapi.vcs.changes.CacheChangeProcessor.<init>(CacheChangeProcessor.java:46)
	at com.intellij.openapi.vcs.changes.ChangesViewManager$MyChangeProcessor.<init>(ChangesViewManager.java:556)
	at com.intellij.openapi.vcs.changes.ChangesViewManager.<init>(ChangesViewManager.java:118)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:499)
	... 57 more

**Comment by ChrisRM** [comment]
This is a different error. Not sure what causes this tbh

**Comment by robertfreund** [comment]
@ChrisRM After seeing the build work someone with PHPStorm I gave it a shot again with Intellij ultimate. I get the same error as indicated above. This only happens when using Dark Theme. Using Default theme does not have this issue.

**Comment by robertfreund** [comment]
@ChrisRM when I test this using the Plugin Dev Kit it works fine. I built latest and packaged it up and same error as above. Any other thoughts on what to try?

**Comment by ChrisRM** [comment]
Could it be that some of your other plugins is incompatible with this one? Can you try a clean installation of IntelliJ and see if that works? Make sure you open the same project as before, with VCS enabled.

**Comment by robertfreund** [comment]
Mac 10.11.4. Thanks, Ill give that a shot.

**Comment by robertfreund** [comment]
@ChrisRM Please find PR for what what finally worked for me. thanks again! Awesome job with this plugin.
