### ISSUE TITLE
IllegalStateException @getLookAndFeelInfo must not return null

### ISSUE THREAD

**Issue by Solotov** [ChrisRM/material-theme-jetbrains#1876]
After pressing "Ctrl+Space" for the first time in a PHP file, I got this exception.
in previous versions this error does not happen.

### Summary
```
java.lang.IllegalStateException: @NotNull method com/mallowigi/idea/MTHackLafProvider.getLookAndFeelInfo must not return null
	at com.mallowigi.idea.MTHackLafProvider.$$$reportNull$$$0(MTHackLafProvider.java)
	at com.mallowigi.idea.MTHackLafProvider.getLookAndFeelInfo(MTHackLafProvider.java:61)
	at com.intellij.ide.ui.laf.LafManagerImpl.lambda$computeLafList$4(LafManagerImpl.java:194)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:34)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:46)
	at com.intellij.ide.ui.laf.LafManagerImpl.computeLafList(LafManagerImpl.java:193)
	at com.intellij.ide.ui.laf.LafManagerImpl.lambda$new$0(LafManagerImpl.java:105)
	at com.intellij.util.concurrency.SynchronizedClearableLazy.getValue(SynchronizedClearableLazy.kt:37)
	at com.intellij.ide.ui.laf.LafManagerImpl.findLaf(LafManagerImpl.java:381)
	at com.intellij.ide.ui.laf.LafManagerImpl.loadLafState(LafManagerImpl.java:364)
	at com.intellij.ide.ui.laf.LafManagerImpl.loadState(LafManagerImpl.java:345)
	at com.intellij.ide.ui.laf.LafManagerImpl.loadState(LafManagerImpl.java:74)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:441)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:373)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:119)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:536)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:55)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.ide.ui.LafManager.getInstance(LafManager.java:17)
	at com.intellij.idea.ApplicationLoader$initApplication$block$3$2.run(ApplicationLoader.kt:156)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:393)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### Expected behavior
`no comments`
### Actual behavior

`the error occurs at the first start of PHPSTORM with one or more code files open After pressing "Ctrl+Space".`

### Steps to reproduce (if needed)

1. open phpstorm (optional: with administrative permissions) with one or more .php files open.
2. click on a file.
3. then "Ctrl+Space".

![exception-shot](https://user-images.githubusercontent.com/4804666/172516520-033030b3-40f9-4b21-9379-def37ac49103.jpg)

### Environment

```
Windows 10
PhpStorm 2022.1
Build #PS-221.5080.224, built on April 13, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
    run.processes.with.pty=TRUE
    debugger.valueTooltipAutoShowOnSelection=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.unger1984.npmdependencychecker (0.0.3)
    com.intellij.ideolog (203.0.30.0)
    com.github.copilot (1.1.24.1610)
    com.andrey4623.rainbowcsv (2.0.2)
    de.espend.idea.php.annotation (8.2.1)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    dev.nybroe.collector (0.4.0)
    izhangzhihao.rainbow.brackets (6.23)
    dev.ekvedaras.laravelquery (3.2.1)
    com.chrisrm.idea.MaterialThemeUI (7.5.1)
    com.mallowigi (64.0.0)
    ru.adelf.idea.dotenv (2022.1)
    com.laravel_idea.plugin (5.4.0.221)
```

I can't find the configuration file you indicated.

**Comment by mallowigi** [comment]
Duplicate, and please don't open issues here.
