### ISSUE TITLE
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled

### ISSUE THREAD

**Issue by ghost** [ChrisRM/material-theme-jetbrains#1881]
how to fix ? 

android studio canary 2022.2.1 2
jdk 11

Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled. Please restart Android Studio.

java.lang.UnsupportedClassVersionError: com/mallowigi/idea/MTHackComponent has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
    at java.base/java.lang.ClassLoader.defineClass2(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1109)
    at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:253)
    at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:114)
    at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:63)
    at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:246)
    at com.intellij.util.lang.ClassPath.findClassWithoutCache(ClassPath.java:235)
    at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:202)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:403)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:239)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:211)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:449)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:370)
    at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:55)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:251)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
    at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt:148)
    at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
    at com.intellij.idea.ApplicationLoader$initApplication$block$2.execute(ApplicationLoader.kt:142)
    at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1069)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by mallowigi** [comment]
Please use the version from the JetBrains Toolbox

**Comment by sibgutiapp** [comment]
JetBrains Toolbox 1.26.0.13072, Windows 10.0

**Comment by ghost** [comment]
I am using the version from  the JetBrains Toolbox

**Comment by mallowigi** [comment]
I am working on making it available for JDK11 if possible.

But don't use this repo thanks.
