### ISSUE TITLE
Error on IntelliJ last version

### ISSUE THREAD

**Issue by antonio-petricca** [ChrisRM/material-theme-jetbrains#1883]
After starting latest IntelliJ release I get this error:

`java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
	at com.mallowigi.idea.utils.StaticPatcher.setFinalStatic(StaticPatcher.kt:67)
	at com.mallowigi.idea.UIReplacer.patchCompletionPopup(UIReplacer.kt:340)
	at com.mallowigi.idea.UIReplacer.patchUI(UIReplacer.kt:89)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:325)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:268)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:291)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:104)
	at com.mallowigi.idea.MTLafComponent.initComponent$lambda-2(MTLafComponent.kt:124)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:95)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
`

**Comment by mallowigi** [comment]
Please download version 7.11.0

**Comment by antonio-petricca** [comment]
I am using the following:

![image](https://user-images.githubusercontent.com/6660386/194043679-3a492235-c006-4ccd-9541-5dbb78b80531.png)

**Comment by mallowigi** [comment]
> Please download version 7.11.0

**Comment by antonio-petricca** [comment]
Ok

**Comment by antonio-petricca** [comment]
Well, the 7.11.0 works, thank you!

Should we wait for 7.13.0 before upgrade it?

**Comment by mallowigi** [comment]
No. 7.12.0 is a mistake: https://plugins.jetbrains.com/plugin/8006-material-theme-ui/versions/stable/231262 it should not be downloadable

**Comment by antonio-petricca** [comment]
Sorry, I missed my question, so: should we wait for the 7.13.0 before upgrade it? :)

**Comment by mallowigi** [comment]
There won't be a version 7.13.0. The last version in the marketplace should be 7.11.0, so you shouldn't be able to upgrade. If that's the case, please send me a screenshot so that i can report it to JetBrains.
![CleanShot 2022-10-05 at 14 00 51](https://user-images.githubusercontent.com/5015756/194045542-7568d4e1-cb67-4e7a-a297-f9b4c5ce9ac6.png)

**Comment by antonio-petricca** [comment]
I just got the:

![image](https://user-images.githubusercontent.com/6660386/194045716-fc63d636-d448-43a4-a364-3aa03a74b3b2.png)

Thank you again!

**Comment by mallowigi** [comment]
Yep, that's for 2022.3 IDEs. It's only for EAP though at this time.

**Comment by antonio-petricca** [comment]
Unfortunately again with latest update 7.13.1. :(
