### ISSUE TITLE
Exception in plugin Material Theme UI (7.14.2)

### ISSUE THREAD

**Issue by pncsoares** [ChrisRM/material-theme-jetbrains#1887]
Hi,
Thanks in advance for the assistance and time spent.

Some details:
- I am using a MacBook Pro 13 with M2 chip
- Rider from JetBrains (2022.2.4)
- Material Theme UI (7.14.2)

![image](https://user-images.githubusercontent.com/37508158/201188078-faef9c0c-35c6-4fef-8b1d-0f7cb52e8aaa.png)

Each time I open an instance of Rider, I get the following error 👇

java.lang.NullPointerException: Cannot invoke "com.intellij.ide.projectView.impl.AbstractProjectViewPane.getTree()" because "$this$refreshProjectViews_u24lambda_u241_u24lambda_u240" is null
	at com.mallowigi.idea.utils.MTUtils.refreshProjectViews(MTUtils.kt:108)
	at com.mallowigi.idea.utils.MTUiUtils.installMaterialTree(MTUiUtils.java:953)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:325)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:251)
	at com.mallowigi.idea.MTLafComponent.activateTheme(MTLafComponent.kt:213)
	at com.mallowigi.idea.MTLafComponent.onSettingsChanged(MTLafComponent.kt:181)
	at com.mallowigi.idea.MTLafComponent$initComponent$2.configChanged(MTLafComponent.kt:130)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:625)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:399)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:378)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:437)
	at jdk.proxy3/jdk.proxy3.$Proxy172.configChanged(Unknown Source)
	at com.mallowigi.idea.config.application.MTConfig.fireChanged(MTConfig.java:371)
	at com.mallowigi.idea.config.application.MTConfig.activateFreePlan(MTConfig.java:554)
	at com.mallowigi.idea.license.MTLicenseManager.switchToFreePlan$lambda$0(MTLicenseManager.kt:120)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

![image](https://user-images.githubusercontent.com/37508158/201188033-893e27a6-9c2b-42da-8b6b-ae0ffbfd1d69.png)

**Comment by mallowigi** [comment]
This repository is archived.

**Comment by pncsoares** [comment]
@mallowigi where should I register this issue?
