### ISSUE TITLE
Crash on VirtualBox

### ISSUE THREAD

**Issue by VixikHD** [ChrisRM/material-theme-jetbrains#1890]
### Summary
Plugin crashes on start on Virtual Box, but the theme is set and works

### Expected behavior
The crash should not happen

### Actual behavior
...

### Steps to reproduce (if needed)
1. Start Linux on Virtual Box on windows
2. Run CLion
3. Check the error

You can also add Screenshots for a better understanding.
![image](https://user-images.githubusercontent.com/40556088/228537423-ce2c6dbc-7401-478f-a67f-47fd78dc8aee.png)
(Right Down Corner)

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac): Arch Linux (on Virtual Box)
* IntelliJ Product + version (IDEA, RubyMine...) CLion 2022.3.2 Build #CL-223.8617.54, built on January 25, 2023
* Runtime version: 19.0.2+7-44 amd64
* VM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
* Plugin version: 8.4.1
* Plugin configuration (found in material_theme.xml): [material_theme.xml.txt](https://github.com/ChrisRM/material-theme-jetbrains/files/11100915/material_theme.xml.txt)

Stack trace:
```
java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.mallowigi.idea.utils.FieldHelper.makeNonFinal(FieldHelper.kt:52)
	at com.mallowigi.idea.utils.StaticPatcher.setFinalStatic(StaticPatcher.kt:64)
	at com.mallowigi.idea.UIReplacer.patchCompletionPopup(UIReplacer.kt:341)
	at com.mallowigi.idea.UIReplacer.patchUI(UIReplacer.kt:90)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:321)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:264)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:287)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:100)
	at com.mallowigi.idea.MTLafComponent.initComponent$lambda$2(MTLafComponent.kt:122)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWrite
[material_theme.xml.txt](https://github.com/ChrisRM/material-theme-jetbrains/files/11100914/material_theme.xml.txt)
ActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:97)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by mallowigi** [comment]
The plugin is not supported on JVM 11 anymore. Please download JetBrains Toolbox and run it from there.
