### ISSUE TITLE
Broken on Android Studio

### ISSUE THREAD

**Issue by AlstonLin** [ChrisRM/material-theme-jetbrains#220]
Installed on Android Studio 2.1.2 on Ubuntu 16.04. After restarting it, Android Studio crashed and gave this error message

```
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart Android Studio.

java.lang.NoSuchMethodError: com.intellij.util.ui.UIUtil.getSystemLookAndFeelClassName()Ljava/lang/String;
    at com.chrisrm.idea.MTLaf.applySystemFonts(MTLaf.java:118)
    at com.chrisrm.idea.MTLaf.getDefaults(MTLaf.java:105)
    at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
    at com.chrisrm.idea.actions.MTSwitchTheme.setTheme(MTSwitchTheme.java:25)
    at com.chrisrm.idea.MTColorScheme.initComponent(MTColorScheme.java:19)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:518)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
    at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:91)
    at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:497)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:512)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:455)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:447)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:197)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Also breaks when I tried installing the 0.1.9 and 0.1.8 by downloading the jars. Seems to be system specific since it doesn't break on my other computer.

**Comment by AlstonLin** [comment]
##### Workaround

- Download a copy of the 0.1.9 release zip file
- Inside the zip file, in /material-theme-jetbrains-0.1.9/src/com/chrisrm/idea/MTLaf.java replace line 118 with `String e = javax.swing.UIManager.getSystemLookAndFeelClassName();`
- Apply the workaround described here: #142

**Comment by Liker777** [comment]
cannot find MTLaf.java...
I am on latest version, error still is in place ..(
