### ISSUE TITLE
crash when using "File Structure" in kotlin

### ISSUE THREAD

**Issue by apouche** [ChrisRM/material-theme-jetbrains#238]
The "Navigation -> File Structure" is not working on kotlin and produces the following crash every time:

```
java/util/Objects
java.lang.NoClassDefFoundError: java/util/Objects
	at com.chrisrm.idea.icons.VirtualFileInfo.getFileType(VirtualFileInfo.java:24)
	at com.chrisrm.idea.icons.TypeAssociation.matches(TypeAssociation.java:9)
	at com.chrisrm.idea.icons.Associations.findAssociationForFile(Associations.java:55)
	at com.chrisrm.idea.icons.MTFileIconProvider.getIcon(MTFileIconProvider.java:27)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at org.jetbrains.kotlin.idea.structureView.KotlinStructureElementPresentation.getElementIcon(KotlinStructureElementPresentation.java:117)
	at org.jetbrains.kotlin.idea.structureView.KotlinStructureElementPresentation.<init>(KotlinStructureElementPresentation.java:61)
	at org.jetbrains.kotlin.idea.structureView.KotlinStructureViewElement.getPresentation(KotlinStructureViewElement.java:97)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.update(TreeElementWrapper.java:41)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure$FilteringNode.doUpdate(FilteringTreeStructure.java:231)
	at com.intellij.ui.treeStructure.SimpleNode.update(SimpleNode.java:103)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.updateNodeDescriptor(AbstractTreeBuilder.java:577)
	at com.intellij.ide.util.treeView.AbstractTreeUi$22.perform(AbstractTreeUi.java:944)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:940)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:863)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$1600(AbstractTreeUi.java:62)
	at com.intellij.ide.util.treeView.AbstractTreeUi$15.perform(AbstractTreeUi.java:715)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeUi.initRootNodeNowIfNeeded(AbstractTreeUi.java:770)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateSubtreeNow(AbstractTreeUi.java:1062)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater$3.perform(AbstractTreeUpdater.java:258)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater.performUpdate(AbstractTreeUpdater.java:254)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater$2.run(AbstractTreeUpdater.java:215)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2361)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:283)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1$1.run(Alarm.java:346)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)



java.lang.NoClassDefFoundError: java/util/Objects
	at com.chrisrm.idea.icons.VirtualFileInfo.getFileType(VirtualFileInfo.java:24)
	at com.chrisrm.idea.icons.TypeAssociation.matches(TypeAssociation.java:9)
	at com.chrisrm.idea.icons.Associations.findAssociationForFile(Associations.java:55)
	at com.chrisrm.idea.icons.MTFileIconProvider.getIcon(MTFileIconProvider.java:27)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at org.jetbrains.kotlin.idea.structureView.KotlinStructureElementPresentation.getElementIcon(KotlinStructureElementPresentation.java:117)
	at org.jetbrains.kotlin.idea.structureView.KotlinStructureElementPresentation.<init>(KotlinStructureElementPresentation.java:61)
	at org.jetbrains.kotlin.idea.structureView.KotlinStructureViewElement.getPresentation(KotlinStructureViewElement.java:97)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.update(TreeElementWrapper.java:41)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure$FilteringNode.doUpdate(FilteringTreeStructure.java:231)
	at com.intellij.ui.treeStructure.SimpleNode.update(SimpleNode.java:103)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.updateNodeDescriptor(AbstractTreeBuilder.java:577)
	at com.intellij.ide.util.treeView.AbstractTreeUi$22.perform(AbstractTreeUi.java:944)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:940)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:863)
	at com.intellij.ide.util.treeView.AbstractTreeUi.doUpdateChildren(AbstractTreeUi.java:1251)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$3100(AbstractTreeUi.java:62)
	at com.intellij.ide.util.treeView.AbstractTreeUi$26$1.perform(AbstractTreeUi.java:1182)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$2500(AbstractTreeUi.java:62)
	at com.intellij.ide.util.treeView.AbstractTreeUi$26.perform(AbstractTreeUi.java:1179)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildren(AbstractTreeUi.java:1174)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateSubtreeNow(AbstractTreeUi.java:1080)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater$3.perform(AbstractTreeUpdater.java:258)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater.performUpdate(AbstractTreeUpdater.java:254)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater$2.run(AbstractTreeUpdater.java:215)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2361)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:283)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1$1.run(Alarm.java:346)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by apouche** [comment]
This might have been a JB issue, as it has been fixed in Android Studio 2.2. Closing
