### ISSUE TITLE
Webstorm 2016.3 not boot

### ISSUE THREAD

**Issue by cdanyl** [ChrisRM/material-theme-jetbrains#245]
Under Windows, Webstorm 2016.3 EAP not boot !

anyone?

**Comment by Izopi4a** [comment]
everyone ... hopefully someone will make a proper material theme ever or at least maintain it more often. Last 5 issues are about this tho ...

**Comment by DevVersion** [comment]
I created a fork my self to target the EAP versions better (but I don't have time to maintain it etc.) but here is a quick diff, which fixed the boot problems.

<details>
```diff
diff --git a/resources/properties/darker/mt-darker_windows.properties b/resources/properties/darker/mt-darker_windows.properties
index e633a34..aaf0fcb 100644
--- a/resources/properties/darker/mt-darker_windows.properties
+++ b/resources/properties/darker/mt-darker_windows.properties
@@ -9,7 +9,7 @@ InternalFrameUI=com.intellij.ide.ui.laf.darcula.ui.DarculaInternalFrameUI
 InternalFrame.border=com.intellij.ide.ui.laf.darcula.ui.DarculaInternalBorder
 RootPaneUI=com.intellij.ide.ui.laf.darcula.ui.DarculaRootPaneUI
 
-InternalFrame.closeIcon=AllIcons.Windows.Close
-InternalFrame.iconifyIcon=AllIcons.Windows.Iconify
-InternalFrame.maximizeIcon=AllIcons.Windows.Maximize
-InternalFrame.minimizeIcon=AllIcons.Windows.Minimize
+InternalFrame.closeIcon=AllIcons.Windows.CloseInactive
+InternalFrame.iconifyIcon=AllIcons.Windows.MinimizeInactive
+InternalFrame.maximizeIcon=AllIcons.Windows.MaximizeInactive
+InternalFrame.minimizeIcon=AllIcons.Windows.RestoreInactive
\ No newline at end of file
diff --git a/resources/properties/default/mt-default_windows.properties b/resources/properties/default/mt-default_windows.properties
index e633a34..aaf0fcb 100644
--- a/resources/properties/default/mt-default_windows.properties
+++ b/resources/properties/default/mt-default_windows.properties
@@ -9,7 +9,7 @@ InternalFrameUI=com.intellij.ide.ui.laf.darcula.ui.DarculaInternalFrameUI
 InternalFrame.border=com.intellij.ide.ui.laf.darcula.ui.DarculaInternalBorder
 RootPaneUI=com.intellij.ide.ui.laf.darcula.ui.DarculaRootPaneUI
 
-InternalFrame.closeIcon=AllIcons.Windows.Close
-InternalFrame.iconifyIcon=AllIcons.Windows.Iconify
-InternalFrame.maximizeIcon=AllIcons.Windows.Maximize
-InternalFrame.minimizeIcon=AllIcons.Windows.Minimize
+InternalFrame.closeIcon=AllIcons.Windows.CloseInactive
+InternalFrame.iconifyIcon=AllIcons.Windows.MinimizeInactive
+InternalFrame.maximizeIcon=AllIcons.Windows.MaximizeInactive
+InternalFrame.minimizeIcon=AllIcons.Windows.RestoreInactive
\ No newline at end of file
diff --git a/resources/properties/lighter/mt-lighter_windows.properties b/resources/properties/lighter/mt-lighter_windows.properties
index e633a34..aaf0fcb 100644
--- a/resources/properties/lighter/mt-lighter_windows.properties
+++ b/resources/properties/lighter/mt-lighter_windows.properties
@@ -9,7 +9,7 @@ InternalFrameUI=com.intellij.ide.ui.laf.darcula.ui.DarculaInternalFrameUI
 InternalFrame.border=com.intellij.ide.ui.laf.darcula.ui.DarculaInternalBorder
 RootPaneUI=com.intellij.ide.ui.laf.darcula.ui.DarculaRootPaneUI
 
-InternalFrame.closeIcon=AllIcons.Windows.Close
-InternalFrame.iconifyIcon=AllIcons.Windows.Iconify
-InternalFrame.maximizeIcon=AllIcons.Windows.Maximize
-InternalFrame.minimizeIcon=AllIcons.Windows.Minimize
+InternalFrame.closeIcon=AllIcons.Windows.CloseInactive
+InternalFrame.iconifyIcon=AllIcons.Windows.MinimizeInactive
+InternalFrame.maximizeIcon=AllIcons.Windows.MaximizeInactive
+InternalFrame.minimizeIcon=AllIcons.Windows.RestoreInactive
\ No newline at end of file
diff --git a/src/com/chrisrm/idea/MTLaf.java b/src/com/chrisrm/idea/MTLaf.java
index fb4f1ad..5ce0bfc 100644
--- a/src/com/chrisrm/idea/MTLaf.java
+++ b/src/com/chrisrm/idea/MTLaf.java
@@ -192,10 +192,4 @@ protected void loadDefaults(UIDefaults defaults) {
         }
     }
 
-    @SuppressWarnings("UnusedParameters")
-    private static void log(Exception e) {
-        e.printStackTrace();
-    }
-
-
 }
\ No newline at end of file
```
</details>

**Comment by cdanyl** [comment]
Sound good, have you a repo or zip version ?

**Comment by Komayo** [comment]
When fix will be added to repository?

**Comment by DevVersion** [comment]
I have a jar for it, which can be installed in Webstorm (but I might be still bugging around) - just fixed the bugs I've noticed yet.

> http://en.file-upload.net/download-11954349/MdThemeJetbrains.jar.html

I also have a repo for it, but I made it private because I consider it as weird to publish a forked project.

**Comment by izhangzhihao** [comment]
thanks for your excellent job  @DevVersion  . I am in China , I can't download it from http://en.file-upload.net ,can you use OneDrive or GoogleDrive ?

**Comment by izhangzhihao** [comment]
@DevVersion there is a exception:

null
com.chrisrm.idea.MTTabsPainterPatcher$MTTabsPainter$$EnhancerByCGLIB$$f267a4fd.doPaintInactive(<generated>)
	at com.intellij.ui.tabs.impl.JBEditorTabs.doPaintInactive(JBEditorTabs.java:155)
	at com.intellij.ui.tabs.impl.JBTabsImpl.paintNonSelected(JBTabsImpl.java:2042)
	at com.intellij.ui.tabs.impl.JBTabsImpl.paintNonSelectedTabs(JBTabsImpl.java:2009)
	at com.intellij.ui.tabs.impl.JBTabsImpl.paintComponent(JBTabsImpl.java:1688)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at com.intellij.ui.tabs.impl.JBTabsImpl.paint(JBTabsImpl.java:2311)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at com.intellij.openapi.wm.impl.ToolWindowsPane.paintChildren(ToolWindowsPane.java:184)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5217)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paint(JComponent.java:1042)
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
	at java.awt.Container.paint(Container.java:1975)
	at java.awt.Window.paint(Window.java:3904)
	at com.intellij.openapi.wm.impl.IdeFrameImpl.paint(IdeFrameImpl.java:537)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	... 24 more
Caused by: java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at com.chrisrm.idea.MTTabsPainterPatcher$MTTabsPainter.getProperties(MTTabsPainterPatcher.java:129)
	at com.chrisrm.idea.MTTabsPainterPatcher$MTTabsPainter.getDefaultTabColor(MTTabsPainterPatcher.java:113)
	at com.chrisrm.idea.MTTabsPainterPatcher$MTTabsPainter.getInactiveMaskColor(MTTabsPainterPatcher.java:120)
	at com.intellij.ui.tabs.impl.DefaultEditorTabsPainter.doPaintInactive(DefaultEditorTabsPainter.java:43)
	... 71 more

**Comment by LeoLozes** [comment]
Doesn't boot with Intellij Idea 2016.3 EAP either. 

```
2016-10-14 09:42:18,869 [   9615]  ERROR - llij.ide.plugins.PluginManager - java.lang.NullPointerException 
java.lang.RuntimeException: java.lang.NullPointerException
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:74)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at javax.swing.SwingUtilities.getWindowAncestor(SwingUtilities.java:135)
	at javax.swing.plaf.metal.MetalRootPaneUI.installWindowListeners(MetalRootPaneUI.java:220)
	at javax.swing.plaf.metal.MetalRootPaneUI.installClientDecorations(MetalRootPaneUI.java:275)
```

**Comment by otravers** [comment]
Replicated in PhpStorm 2016.3 EAP 163.6110.10

**Comment by mallowigi** [comment]
Thanks @DevVersion !

**Comment by karlpatrickespiritu** [comment]
I'm having this issue. Reinstalled webstorm 2016.3 several times. But every time I add a plugin (material theme, to be specific), and restart, it loads and gets stuck.
