### ISSUE TITLE
It works well on webstorm but failed  on pycharm and intellij idea

### ISSUE THREAD

**Issue by wandergis** [ChrisRM/material-theme-jetbrains#29]
**Just like the image below.**
The new version  0.1.4 cause the problem.

tips:
I love this theme so much, it is more beautiful than the sublime material theme,thank you so much。

**Comment by wandergis** [comment]
sorry the image uploads failed,this is the problem image.![cd593305-4802-4446-a705-03ed9438b543](https://cloud.githubusercontent.com/assets/5799374/10383971/43f97eb8-6e68-11e5-9fc9-58ed81783e87.png)

**Comment by chrismcguirehootsuite** [comment]
Confirm above error

**Comment by rashidul0405** [comment]
Same error with PHPStorm. May be it's due to java version or may be not. When I tried earlier build, it was ok but this version producing this error.

Environment:
Mac OS X Yosemite
java version "1.6.0_65"

**Comment by aminblog** [comment]
Same error with PHPStorm 10
java is update
win7

Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.ClassNotFoundException: com.chrisrm.idea.MTColorScheme PluginClassLoader[com.chrisrm.idea.MaterialThemeUI, 0.1.7]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:408)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:454)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:446)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:63)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:360)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
