### ISSUE TITLE
Can't open quick documentation

### ISSUE THREAD

**Issue by Loong-T** [ChrisRM/material-theme-jetbrains#30]
IDE: Android Studio 1.4
Every time use quick documentation, I get a NullPointerException.

```
null
java.lang.NullPointerException
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1424)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1644)
	at javax.swing.text.html.StyleSheet.getResolvedStyle(StyleSheet.java:1273)
	at javax.swing.text.html.StyleSheet.getRule(StyleSheet.java:276)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1424)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1503)
	at javax.swing.text.html.StyleSheet.getResolvedStyle(StyleSheet.java:1261)
	at javax.swing.text.html.StyleSheet.getRule(StyleSheet.java:253)
	at javax.swing.text.html.StyleSheet$ViewAttributeSet.<init>(StyleSheet.java:2673)
	at javax.swing.text.html.StyleSheet.getViewAttributes(StyleSheet.java:348)
	at javax.swing.text.html.ParagraphView.setPropertiesFromAttributes(ParagraphView.java:101)
	at javax.swing.text.ParagraphView.<init>(ParagraphView.java:59)
	at javax.swing.text.html.ParagraphView.<init>(ParagraphView.java:54)
	at javax.swing.text.html.HTMLEditorKit$HTMLFactory.create(HTMLEditorKit.java:1148)
	at javax.swing.text.CompositeView.loadChildren(CompositeView.java:112)
	at javax.swing.text.CompositeView.setParent(CompositeView.java:139)
	at javax.swing.text.html.BlockView.setParent(BlockView.java:72)
	at javax.swing.text.html.HTMLEditorKit$HTMLFactory$BodyBlockView.setParent(HTMLEditorKit.java:1327)
	at javax.swing.text.CompositeView.replace(CompositeView.java:217)
	at javax.swing.text.BoxView.replace(BoxView.java:181)
	at javax.swing.text.CompositeView.loadChildren(CompositeView.java:114)
	at javax.swing.text.CompositeView.setParent(CompositeView.java:139)
	at javax.swing.text.html.BlockView.setParent(BlockView.java:72)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setView(BasicTextUI.java:1328)
	at javax.swing.plaf.basic.BasicTextUI.setView(BasicTextUI.java:693)
	at javax.swing.plaf.basic.BasicTextUI.modelChanged(BasicTextUI.java:682)
	at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.propertyChange(BasicTextUI.java:1794)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8422)
	at javax.swing.text.JTextComponent.setDocument(JTextComponent.java:443)
	at com.intellij.codeInsight.documentation.DocumentationComponent$2.setDocument(DocumentationComponent.java:203)
	at javax.swing.JEditorPane.setEditorKit(JEditorPane.java:1058)
	at com.intellij.codeInsight.documentation.DocumentationComponent.<init>(DocumentationComponent.java:219)
	at com.intellij.codeInsight.documentation.DocumentationComponent.<init>(DocumentationComponent.java:381)
	at com.intellij.codeInsight.documentation.DocumentationManager.showInPopup(DocumentationManager.java:435)
	at com.intellij.codeInsight.documentation.DocumentationManager.doShowJavaDocInfo(DocumentationManager.java:426)
	at com.intellij.codeInsight.documentation.DocumentationManager.showJavaDocInfo(DocumentationManager.java:367)
	at com.intellij.codeInsight.documentation.DocumentationManager.showJavaDocInfo(DocumentationManager.java:288)
	at com.intellij.codeInsight.documentation.actions.ShowQuickDocInfoAction$1.invoke(ShowQuickDocInfoAction.java:52)
	at com.intellij.codeInsight.actions.CodeInsightAction$1$1.run(CodeInsightAction.java:62)
	at com.intellij.codeInsight.actions.CodeInsightAction$1.run(CodeInsightAction.java:69)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:54)
	at com.intellij.codeInsight.documentation.actions.ShowQuickDocInfoAction.actionPerformed(ShowQuickDocInfoAction.java:138)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:593)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:644)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:483)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ChrisRM** [comment]
Not what causes this. Try the newest build

**Comment by ChrisRM** [comment]
Fixed. Tested in Android Studio 1.4
