### ISSUE TITLE
Not compatible with 2017 EAP

### ISSUE THREAD

**Issue by Kurre** [ChrisRM/material-theme-jetbrains#302]
It seems that commit https://github.com/ChrisRM/material-theme-jetbrains/commit/db014f6b3fc09cf4b94396c44bafb221117f4b1f by @mallowigi isn't compatible with 2017 EAPs

They have refactored the JBUI and removed `setScaleFactor` method with this commit https://github.com/JetBrains/intellij-community/commit/70b17e8788e568a924871ea1392a9b07b3082a8a#diff-b5e2d17f066b77030f3d40ecbd9ded0e

```
java.lang.NoSuchMethodError: com.intellij.util.ui.JBUI.setScaleFactor(F)V
    at com.chrisrm.idea.MTTheme.activate(MTTheme.java:92)
    at com.chrisrm.idea.MTColorScheme.initComponent(MTColorScheme.java:10)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:501)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:466)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:181)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:587)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:166)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:473)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:425)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:411)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:200)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:70)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mallowigi** [comment]
Yes I've seen this. I've released a fix though in my fork, you should have version 0.2.4.1

**Comment by Kurre** [comment]
It doesn't seem to be fixed in version 0.2.4.1 (I reinstalled it just to be sure)?

Still getting same error with PHPStorm 2017.1 EAP
```
PhpStorm 2017.1 EAP
Build #PS-171.2613.13, built on January 25, 2017
PhpStorm EAP User
Expiration date: February 24, 2017
JRE: 1.8.0_102-b14 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation
```

```
Plugin 'com.chrisrm.idea.MaterialThemeUIFork' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.NoSuchMethodError: com.intellij.util.ui.JBUI.setScaleFactor(F)V
    at com.chrisrm.idea.MTTheme.activate(MTTheme.java:92)
```

and seems that that call to removed method is still there https://github.com/mallowigi/material-theme-jetbrains/blob/master/src/main/java/com/chrisrm/idea/MTTheme.java#L92

Or maybe I'm missing something? 🙂

**Comment by mallowigi** [comment]
I see. You're right. I've fixed it but I didn't deploy a new version since I didn't tested it on all platforms yet. I will issue a fix as soon as I have the time. I also need to update this plugin too.

**Comment by Kurre** [comment]
Yeah, the hotfix solves the problem with 2017 EAP. Thanks 👍
