### ISSUE TITLE
Tab Issue - IntelliJ 17.1

### ISSUE THREAD

**Issue by JohnPucciarelli** [ChrisRM/material-theme-jetbrains#311]
Get the following error when running the plugin on IntelliJ 17.1 EAP:

```
com.intellij.ui.tabs.impl.DefaultEditorTabsPainter: method <init>()V not found
java.lang.NoSuchMethodError: com.intellij.ui.tabs.impl.DefaultEditorTabsPainter: method <init>()V not found
	at com.chrisrm.idea.MTTabsPainter.<init>(MTTabsPainter.java:13)
	at com.chrisrm.idea.MTTabsPainterPatcher.patchPainter(MTTabsPainterPatcher.java:76)
	at com.chrisrm.idea.MTTabsPainterPatcher.access$000(MTTabsPainterPatcher.java:32)
	at com.chrisrm.idea.MTTabsPainterPatcher$1.selectionChanged(MTTabsPainterPatcher.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
...
```

Tab rendering also appears to be affected as a result (still darcula instead of material). I tried adding a default constructor to `MTTabsPainter` but that didn't seem to fix it.

Any ideas @mallowigi?

**Comment by mallowigi** [comment]
For now please use my fork. One day I'll ask the owner to merge the changes to this repo.
