### ISSUE TITLE
Type info action is not working  with Scala plugin

### ISSUE THREAD

**Issue by cool-hazcker** [ChrisRM/material-theme-jetbrains#358]
I am using Material theme with default color theme and Type Info Action doesn't seem to work (Ctrl+ Shift+ P for Mac). Most of the time it just doesn't output anything. 
On a related note, when one hovers a mouse over a definition holding Cmd, Idea shows the type info of selected statement. With Material Theme while doing it I have weird glitches like this:
![image](https://user-images.githubusercontent.com/3353419/27239238-f4d7cd50-5284-11e7-82ad-2e5ec8f9e367.png)

I am using Intellij IDEA 2017.1.4 and Scala plugin version 2017.1.19

**Comment by mallowigi** [comment]
Probably using Linux, amirite?

**Comment by cool-hazcker** [comment]
Nope, OS X El Capitan

**Comment by mallowigi** [comment]
Hmm... Never heard of that...

I will see what  I can do

**Comment by cool-hazcker** [comment]
It seems that the problem holds true only for the Scala plugin. Everything works fine when working with Java

**Comment by bsylla** [comment]
Same problem for me. Very annoying.

**Comment by mallowigi** [comment]
I'm not a Scala developer but I've dl'ed a SBT project to see if I can reproduce. I'm on Mac OSX Sierra and so far I couldn't. Type Info works well for me (though it does not give the results I've been expecting, but this is a bug related to the Scala plugin I assume).

Things related to UI glitches are usually something with OpenJDK. I remember having this issues when I was on Linux, so the problem might be related because you are on an older version of Mac?

In any case whenever those issues pop up, try to look into the logs (Help -> Show Log in Finder) and see if there was an error of any sort. If it's something related to the plugin, paste it here and I'll try to look at it.

**Comment by bsylla** [comment]
Here is what happens when I hit `ALT+=` to get type info. (Note that my config is at the beginning of the log): 
<pre><code>2017-06-23 16:03:26,552 [ 790477]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2017.1.4  Build #IC-171.4694.23 
2017-06-23 16:03:26,552 [ 790477]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_112-release 
2017-06-23 16:03:26,552 [ 790477]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2017-06-23 16:03:26,552 [ 790477]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2017-06-23 16:03:26,552 [ 790477]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2017-06-23 16:03:26,552 [ 790477]  ERROR - llij.ide.plugins.PluginManager - Last Action: Scala.TypeInfo 
2017-06-23 16:03:27,706 [ 791631]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
	at org.jetbrains.plugins.scala.lang.breadcrumbs.ScalaBreadcrumbsPresentationProvider$.org$jetbrains$plugins$scala$lang$breadcrumbs$ScalaBreadcrumbsPresentationProvider$$calculateColorLuminance(ScalaBreadcrumbsPresentationProvider.scala:90)
	at org.jetbrains.plugins.scala.lang.breadcrumbs.ScalaBreadcrumbsPresentationProvider$MyCrumbPresentation.getBackgroundColor(ScalaBreadcrumbsPresentationProvider.scala:52)
	at com.intellij.xml.breadcrumbs.BreadcrumbsComponent$ButtonSettings.getBackgroundColor(BreadcrumbsComponent.java:664)
	at com.intellij.xml.breadcrumbs.BreadcrumbsComponent$DefaultPainter.paint(BreadcrumbsComponent.java:706)
	at com.intellij.xml.breadcrumbs.BreadcrumbsComponent$Crumb.paint(BreadcrumbsComponent.java:533)
	at com.intellij.xml.breadcrumbs.BreadcrumbsComponent$PagedImage.repaint(BreadcrumbsComponent.java:410)
	at com.intellij.xml.breadcrumbs.BreadcrumbsComponent$PagedImage.paintPage(BreadcrumbsComponent.java:420)
	at com.intellij.xml.breadcrumbs.BreadcrumbsComponent.paint(BreadcrumbsComponent.java:194)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at com.intellij.ui.tabs.impl.JBTabsImpl.paintChildren(JBTabsImpl.java:2306)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at com.intellij.ui.tabs.impl.JBTabsImpl.paint(JBTabsImpl.java:2301)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at com.intellij.openapi.wm.impl.ToolWindowsPane.paintChildren(ToolWindowsPane.java:184)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)</code></pre>

**Comment by mallowigi** [comment]
This doesn't look like something related to the plugin, but since the Tabs component is altered at some point, it might be related.

Did you check before installing the plugin and didn't see any issues?

**Comment by bsylla** [comment]
Yes, I checked before. And when I remove it, everything works fine.

**Comment by mallowigi** [comment]
Hmm... Okay what are the conditions for this to happen? Just pressing Alt + = ? It it a Class? Interface? 

I could not reproduce before so it will be a little hard troubleshooting.

**Comment by bsylla** [comment]
It happens when I place the caret on a given value or method of a Singleton object and press Alt + =.

**Comment by cool-hazcker** [comment]
im on OS X Sierra now and pressing type info shortcut gives the following logs:
```
2017-06-23 11:19:06,066 [297715384]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2017.1.4  Build #IC-171.4694.23 
2017-06-23 11:19:06,066 [297715384]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_112-release 
2017-06-23 11:19:06,066 [297715384]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2017-06-23 11:19:06,066 [297715384]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2017-06-23 11:19:06,066 [297715384]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2017-06-23 11:19:06,066 [297715384]  ERROR - llij.ide.plugins.PluginManager - Last Action: Scala.TypeInfo 
2017-06-23 11:19:07,019 [297716337]  ERROR - llij.ide.plugins.PluginManager - Argument for @NotNull parameter 'color' of com/intellij/ui/ColorUtil.brighter must not be null 
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'color' of com/intellij/ui/ColorUtil.brighter must not be null
	at com.intellij.ui.ColorUtil.brighter(ColorUtil.java)
	at org.jetbrains.plugins.scala.lang.breadcrumbs.ScalaBreadcrumbsPresentationProvider$MyCrumbPresentation.getBackgroundColor(ScalaBreadcrumbsPresentationProvider.scala:48)
	at com.intellij.xml.breadcrumbs.BreadcrumbsComponent$ButtonSettings.getBackgroundColor(BreadcrumbsComponent.java:664)
	at com.intellij.xml.breadcrumbs.BreadcrumbsComponent$DefaultPainter.paint(BreadcrumbsComponent.java:706)
	at com.intellij.xml.breadcrumbs.BreadcrumbsComponent$Crumb.paint(BreadcrumbsComponent.java:533)
	at com.intellij.xml.breadcrumbs.BreadcrumbsComponent$PagedImage.repaint(BreadcrumbsComponent.java:410)
	at com.intellij.xml.breadcrumbs.BreadcrumbsComponent$PagedImage.paintPage(BreadcrumbsComponent.java:420)
	at com.intellij.xml.breadcrumbs.BreadcrumbsComponent.paint(BreadcrumbsComponent.java:194)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at com.intellij.openapi.wm.impl.ToolWindowsPane.paintChildren(ToolWindowsPane.java:184)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5217)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:306)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paint(JComponent.java:1042)
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
	at java.awt.Container.paint(Container.java:1975)
	at java.awt.Window.paint(Window.java:3904)
	at com.intellij.openapi.wm.impl.IdeFrameImpl.paint(IdeFrameImpl.java:539)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mallowigi** [comment]
https://github.com/JetBrains/intellij-scala/commit/16212cb9bdbb26250899fbb89ae4699d76c2621d

So yeah it was the plugin's fault. This explains why I didn't have the issue (I use the EAP)

But don't worry though I have a quick fix that does not depend on the IDE version :)

**Comment by bsylla** [comment]
Works now ! Thanks a lot @mallowigi!

**Comment by cool-hazcker** [comment]
Works like a charm! Thank you so much @mallowigi
