### ISSUE TITLE
Index Out Of Bounds Errors

### ISSUE THREAD

**Issue by DmacMcgreg** [ChrisRM/material-theme-jetbrains#376]
Hi, 
Thank you for this theme. 
I wanted to alert you to constant issues I've been seeing with your Jetbrains plugin

`Index: 3, Size: 3
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.intellij.ui.tabs.impl.JBTabsImpl.getTabAt(JBTabsImpl.java:1321)
	at com.chrisrm.idea.tabs.MTFileEditorListener.setBoldTabs(MTFileEditorListener.java:66)
	at com.chrisrm.idea.tabs.MTFileEditorListener.processActiveTab(MTFileEditorListener.java:50)
	at com.chrisrm.idea.tabs.MTFileEditorListener.selectionChanged(MTFileEditorListener.java:34)
	at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:437)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:380)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:373)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:44)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
	at com.sun.proxy.$Proxy101.selectionChanged(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:1548)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$5$1.run(FileEditorManagerImpl.java:1031)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.b(FocusManagerImpl.java:655)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.j(FocusManagerImpl.java:639)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.r(FocusManagerImpl.java:609)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:61)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:107)
	at com.intellij.openapi.util.EdtRunnable.lambda$run$0(EdtRunnable.java:27)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2632)
	at com.intellij.openapi.util.EdtRunnable.run(EdtRunnable.java:25)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

Cheers

**Comment by mallowigi** [comment]
This shouldnt happen. Do you have the latest version?

**Comment by DmacMcgreg** [comment]
I have version 0.4.1

**Comment by mallowigi** [comment]
So no

**Comment by DmacMcgreg** [comment]
Sorry, what is the latest version? I see no updates from within PhpStorm

**Comment by mallowigi** [comment]
Hmmm are you on PHPstorm 2017.1 or lower?

--
Elior

**Comment by mallowigi** [comment]
Anyway I'm on PHPstorm 1.4 and I see the latest version. If you aren't, you probably need to update your IDE so this is a non-issue.

**Comment by DmacMcgreg** [comment]
PHPStorm 1.4 ? Is this a new version?
I'm on 2017.1 and finally got all the updates from 0.4.1 until 0.5 this morning.

Cheers, and thanks again!
