### ISSUE TITLE
WebStorm 2107.2(RC) - Fails to initialize 

### ISSUE THREAD

**Issue by peet** [ChrisRM/material-theme-jetbrains#388]
Launching WebStorm 2017.2 with the plugin enabled causes a Plugin Error dialog to pop up, with the message `Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart WebStorm.` and a stack trace (see below).

<details>
<summary>Stack Trace</summary>

```
java.lang.AssertionError
    at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:102)
    at com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:66)
    at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:234)
    at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:188)
    at com.intellij.configurationStore.KotlinAwareBeanBinding.deserialize(xmlSerializer.kt:184)
    at com.intellij.configurationStore.XmlSerializer.deserialize(xmlSerializer.kt:79)
    at com.intellij.configurationStore.DefaultStateSerializerKt.deserializeState(DefaultStateSerializer.kt:40)
    at com.intellij.configurationStore.StateStorageBase.deserializeState(StateStorageBase.kt:42)
    at com.intellij.configurationStore.StateGetter.getState(StorageBaseEx.kt:44)
    at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:316)
    at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:291)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:91)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:225)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
    at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:38)
    at com.chrisrm.idea.MTConfig.getInstance(MTConfig.java:65)
    at com.chrisrm.idea.MTLafComponent.installTheme(MTLafComponent.java:64)
    at com.chrisrm.idea.MTLafComponent.initComponent(MTLafComponent.java:26)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:492)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:475)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:482)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:434)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:420)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:67)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:345)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
</details>

**Comment by mallowigi** [comment]
IDE Version?
OS? 
Plugin version?

**Comment by peet** [comment]
IDE Version? WebStorm 2017.2 RC #WS-172.3317.48
OS? Windows 10 - 1703 (15063.483)
Plugin version? Latest in JetBrains repo - 0.3.0.1

**Comment by peet** [comment]
Installed `Material Theme UI EAP` version 0.5.3.5 instead and it works now.
