### ISSUE TITLE
Exception thrown on PhpStorm 2017.2 when editing remote host

### ISSUE THREAD

**Issue by matijakovacevic** [ChrisRM/material-theme-jetbrains#431]
### Summary

Username for remote host connection is forgotten on every restart.
And when I edit remote host again and enter username, on clickin OK button,
PhpStorm throws notification about exception in this plugin

Err message: Cannot save password database: /home/user/.PhpStorm2017.2/config
Details:
Cannot save password database: /home/user/.PhpStorm2017.2/config
java.nio.file.FileAlreadyExistsException: /home/user/.PhpStorm2017.2/config
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
        at java.nio.file.Files.createDirectories(Files.java:727)
        at com.intellij.util.io.PathKt.createDirectories(path.kt:31)
        at com.intellij.util.io.PathKt.outputStream(path.kt:37)
        at com.intellij.util.io.PathKt.writeSafe(path.kt:167)
        at com.intellij.credentialStore.KeePassCredentialStore.save(KeePassCredentialStore.kt:118)
        at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.save(PasswordSafeImpl.kt:91)
        at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:185)
        at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:46)
        at com.intellij.openapi.application.impl.ApplicationImpl.saveSettings(ApplicationImpl.java:1438)
        at com.intellij.openapi.application.impl.ApplicationImpl.saveAll(ApplicationImpl.java:1462)
        at com.intellij.openapi.options.newEditor.SettingsDialog.doOKAction(SettingsDialog.java:174)
        at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1867)
        at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1828)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at com.chrisrm.idea.ui.MTButtonUI$1.mouseReleased(MTButtonUI.java:127)
        at java.awt.Component.processMouseEvent(Component.java:6541)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6306)
        at java.awt.Container.processEvent(Container.java:2237)
        at java.awt.Component.dispatchEventImpl(Component.java:4897)
        at java.awt.Container.dispatchEventImpl(Container.java:2295)
        at java.awt.Component.dispatchEvent(Component.java:4719)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
        at java.awt.Container.dispatchEventImpl(Container.java:2281)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4719)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
        at java.awt.EventQueue.access$500(EventQueue.java:98)
        at java.awt.EventQueue$3.run(EventQueue.java:715)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
        at java.awt.EventQueue$4.run(EventQueue.java:737)
        at java.awt.EventQueue$4.run(EventQueue.java:735)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
        at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:821)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
        at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
        at java.awt.Dialog.show(Dialog.java:1084)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:736)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:458)
        at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1686)
        at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1635)
        at com.intellij.openapi.options.newEditor.SettingsDialog.a(SettingsDialog.java:83)
        at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
        at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:151)
        at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:83)
        at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1650)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:241)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.editConfigurable(ShowSettingsUtilImpl.java:207)
        at com.jetbrains.plugins.webDeployment.ui.config.DeploymentConfigurable.show(DeploymentConfigurable.java:131)
        at com.jetbrains.plugins.webDeployment.ui.WebServerCombo$3.actionPerformed(WebServerCombo.java:96)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at com.chrisrm.idea.ui.MTButtonUI$1.mouseReleased(MTButtonUI.java:127)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.Component.processMouseEvent(Component.java:6541)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6306)
        at java.awt.Container.processEvent(Container.java:2237)
        at java.awt.Component.dispatchEventImpl(Component.java:4897)
        at java.awt.Container.dispatchEventImpl(Container.java:2295)
        at java.awt.Component.dispatchEvent(Component.java:4719)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
        at java.awt.Container.dispatchEventImpl(Container.java:2281)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4719)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
        at java.awt.EventQueue.access$500(EventQueue.java:98)
        at java.awt.EventQueue$3.run(EventQueue.java:715)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
        at java.awt.EventQueue$4.run(EventQueue.java:737)
        at java.awt.EventQueue$4.run(EventQueue.java:735)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
        at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:821)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

### Expected behavior

Remember remote host username

### Actual behavior

Forgets remote host username on every restart

### Environment

PhpStorm 2017.2
Build #PS-172.3317.83, built on July 18, 2017

JRE: 1.8.0_152-release-915-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.8.0-59-generic

**Comment by mallowigi** [comment]
Can you provide me more info about your setting? Theme, Options...

**Comment by matijakovacevic** [comment]
can you tell me the specifics you need?

Theme is set to material theme, with active
-bold directories
-components (every option)

**Comment by mallowigi** [comment]
I think I fixed it in latest EAP. Try it and tell me the results.

**Comment by matijakovacevic** [comment]
updated, but not fixed :\

**Comment by matijakovacevic** [comment]
![screenshot_20170915_092943](https://user-images.githubusercontent.com/2469719/30471413-e9be0658-99f8-11e7-81b0-35b74f8afce4.png)

**Comment by mallowigi** [comment]
Fixed in latest EAP release

**Comment by matijakovacevic** [comment]
updated phpstorm to newest with plugin already updated and still the bug is present
