### ISSUE TITLE
Jetbrains WebStorm EAP 11 (Build WS143-88) 

### ISSUE THREAD

**Issue by vs0uz4** [ChrisRM/material-theme-jetbrains#45]
After installing the plugin and restart the IDE appears this exception. What can this occur?

***PicoPluginExtensionInitializationException***

com.chrisrm.idea.icons.Associations
com.intellij.openapi.extensions.impl.PicoPluginExtensionInitializationException: com.chrisrm.idea.icons.Associations
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:96)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:119)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:249)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:194)

**Comment by ChrisRM** [comment]
Can you try with the stable release? Support for EAP releases are limited.

**Comment by kisstkondoros** [comment]
fix in https://github.com/ChrisRM/material-theme-jetbrains/pull/44

**Comment by ChrisRM** [comment]
@vs0uz4 Can you give it a go now? Download the newest [build](https://github.com/ChrisRM/material-theme-jetbrains/blob/master/Material%20Theme.zip?raw=true) and install it.
