### ISSUE TITLE
[1.3.3] java.lang.NoClassDefFoundError: com/intellij/ide/HelpTooltip

### ISSUE THREAD

**Issue by arkste** [ChrisRM/material-theme-jetbrains#507]
updated to 1.3.3 today, now i get this error:

```
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.NoClassDefFoundError: com/intellij/ide/HelpTooltip
    at com.chrisrm.idea.utils.UIReplacer$Patcher.patchPanels(UIReplacer.java:124)
    at com.chrisrm.idea.utils.UIReplacer.patchUI(UIReplacer.java:70)
    at com.chrisrm.idea.MTLafComponent.initComponent(MTLafComponent.java:82)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:492)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:474)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:481)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:433)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:419)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:64)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:345)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.intellij.ide.HelpTooltip PluginClassLoader[com.chrisrm.idea.MaterialThemeUI, 1.3.3] com.intellij.ide.plugins.cl.PluginClassLoader@11cfdd65
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 36 more
```

```
PhpStorm 2017.2.4
Build #PS-172.4155.41, built on September 15, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-40-generic
```

reverted back to 1.3.2.2 and its working fine, so i guess the recent 1.3.3 update broke something.

**Comment by jeffreykrodgers** [comment]
Having the same issue with WebStorm

**Comment by dschwank** [comment]
+1

**Comment by mallowigi** [comment]
I guess its not a final API then... reverting.

**Comment by dschwank** [comment]
Thanks for the quick response! 1.3.3.1 works like a charm!

**Comment by arkste** [comment]
yup, well done!
