### ISSUE TITLE
Not able to open git commit window after update.

### ISSUE THREAD

**Issue by neohunter** [ChrisRM/material-theme-jetbrains#531]
### Summary

After update Dec 10 2017 I'm not able to open git commit window.

This error appear instead

```
null
java.lang.NullPointerException
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1424)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1644)
	at javax.swing.text.html.StyleSheet.getResolvedStyle(StyleSheet.java:1273)
	at javax.swing.text.html.StyleSheet.getRule(StyleSheet.java:276)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1424)
	at javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1503)
	at javax.swing.text.html.StyleSheet.getResolvedStyle(StyleSheet.java:1261)
	at javax.swing.text.html.StyleSheet.getRule(StyleSheet.java:253)
	at javax.swing.text.html.StyleSheet$ViewAttributeSet.<init>(StyleSheet.java:2676)
	at javax.swing.text.html.StyleSheet.getViewAttributes(StyleSheet.java:348)
	at javax.swing.text.html.ParagraphView.setPropertiesFromAttributes(ParagraphView.java:101)
	at javax.swing.text.ParagraphView.<init>(ParagraphView.java:59)
	at javax.swing.text.html.ParagraphView.<init>(ParagraphView.java:54)
	at javax.swing.text.html.HTMLEditorKit$HTMLFactory.create(HTMLEditorKit.java:1148)
	at javax.swing.text.CompositeView.loadChildren(CompositeView.java:112)
	at javax.swing.text.CompositeView.setParent(CompositeView.java:139)
	at javax.swing.text.html.BlockView.setParent(BlockView.java:72)
	at javax.swing.text.html.HTMLEditorKit$HTMLFactory$BodyBlockView.setParent(HTMLEditorKit.java:1327)
	at javax.swing.text.CompositeView.replace(CompositeView.java:217)
	at javax.swing.text.BoxView.replace(BoxView.java:181)
	at javax.swing.text.CompositeView.loadChildren(CompositeView.java:114)
	at javax.swing.text.CompositeView.setParent(CompositeView.java:139)
	at javax.swing.text.html.BlockView.setParent(BlockView.java:72)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setView(BasicTextUI.java:1328)
	at javax.swing.plaf.basic.BasicTextUI.setView(BasicTextUI.java:693)
	at javax.swing.plaf.basic.BasicTextUI.modelChanged(BasicTextUI.java:682)
	at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.propertyChange(BasicTextUI.java:1794)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8436)
	at javax.swing.text.JTextComponent.setDocument(JTextComponent.java:443)
	at javax.swing.JEditorPane.setEditorKit(JEditorPane.java:1055)
	at com.intellij.ui.components.JBLabel.setCopyable(JBLabel.java:266)
	at com.intellij.ui.components.JBLabel.updateUI(JBLabel.java:203)
	at com.intellij.util.IJSwingUtilities.updateComponentTreeUI(IJSwingUtilities.java:152)
	at com.intellij.ide.ui.laf.LafManagerImpl.a(LafManagerImpl.java:708)
	at com.intellij.ide.ui.laf.LafManagerImpl.updateUI(LafManagerImpl.java:465)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$1EditorColorSchemeProcessor.onCurrentSchemeSwitched(EditorColorsManagerImpl.java:112)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$1EditorColorSchemeProcessor.onCurrentSchemeSwitched(EditorColorsManagerImpl.java:85)
	at com.intellij.configurationStore.schemeManager.SchemeManagerBase.setCurrent(SchemeManagerBase.kt:33)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.setGlobalScheme(EditorColorsManagerImpl.java:330)
	at com.intellij.ide.ui.laf.darcula.DarculaInstaller.a(DarculaInstaller.java:60)
	at com.intellij.ide.ui.laf.darcula.DarculaInstaller.uninstall(DarculaInstaller.java:35)
	at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:348)
	at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:313)
	at com.chrisrm.idea.schemes.MTThemesComponent.activateTheme(MTThemesComponent.java:54)
	at com.chrisrm.idea.schemes.MTThemesComponent.lambda$initComponent$1(MTThemesComponent.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:448)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:409)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:398)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:379)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:45)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:231)
	at com.sun.proxy.$Proxy126.customConfigChanged(Unknown Source)
	at com.chrisrm.idea.MTCustomThemeConfig.fireChanged(MTCustomThemeConfig.java:86)
	at com.chrisrm.idea.config.MTCustomThemeConfigurable.doApply(MTCustomThemeConfigurable.java:99)
	at com.chrisrm.idea.config.MTCustomThemeConfigurable.doApply(MTCustomThemeConfigurable.java:36)
	at com.chrisrm.idea.config.MTConfigurableBase.apply(MTConfigurableBase.java:111)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.apply(ConfigurableWrapper.java:174)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.apply(ConfigurableEditor.java:316)
	at com.intellij.openapi.options.newEditor.SettingsEditor$5.apply(SettingsEditor.java:165)
	at com.intellij.openapi.options.newEditor.SettingsEditor.apply(SettingsEditor.java:321)
	at com.intellij.openapi.options.newEditor.SettingsDialog.doOKAction(SettingsDialog.java:173)
	at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1877)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1838)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at com.chrisrm.idea.ui.MTButtonUI$1.mouseReleased(MTButtonUI.java:126)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:734)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:456)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1696)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1645)
	at com.intellij.openapi.options.newEditor.SettingsDialog.a(SettingsDialog.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:83)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:97)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:63)
	at com.intellij.ide.MacOSApplicationProvider$Worker.a(MacOSApplicationProvider.java:118)
	at com.intellij.ide.MacOSApplicationProvider$Worker.a(MacOSApplicationProvider.java:212)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Expected behavior

The git window should be shown

### Actual behavior

Nothing happens, An exclamation icon appear at the bottom right of RubyMine.

### Steps to reproduce (if needed)

1. CMD + K

### Environment

RubyMine 2017.3
Build #RM-173.3727.132, built on November 28, 2017
Licensed to RubyMine Evaluator
Expiration date: January 5, 2018
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by mallowigi** [comment]
Please select an accent color and restart the ide
