### ISSUE TITLE
DELETE THE PLUGIN FROM THE FILE SYSTEM BEFORE UPGRADING TO 181.3494

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#631]

**Comment by xasx** [comment]
Do you mean because of this exception spamming?

```
2018-02-07 08:44:24,063 [  21111]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.ui.laf.darcula.ui.DarculaButtonUI.isDefaultButton(Ljavax/swing/JComponent;)Z 
java.lang.NoSuchMethodError: com.intellij.ide.ui.laf.darcula.ui.DarculaButtonUI.isDefaultButton(Ljavax/swing/JComponent;)Z
	at com.chrisrm.idea.ui.MTButtonUI.paintDecorations(MTButtonUI.java:266)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaButtonUI.paint(DarculaButtonUI.java:125)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaButtonUI.update(DarculaButtonUI.java:224)
```

And bringing down, e.g., Gnome shell? :laughing:
