### ISSUE TITLE
IDE don't start when Material Theme is installed

### ISSUE THREAD

**Issue by mumi** [ChrisRM/material-theme-jetbrains#671]
Hey guys, I have a fresh macOS 10.13.3 installation (hackintosh) and a fresh WebStorm (newest Version, without plugins or other changes) Installation. 

IDE Info:
Custom plugins: []
Disabled plugins:[]
Build version: WebStorm 2017.3.5 Build #WS-173.4674.32 March 5, 2018
Java version: 1.8.0_152-release-1024-b15x86_64
Operating System: Mac OS X (10.13.3, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

When I install the Material Theme Plugin and restart, this error window occurs:

![Screenshot](https://i.imgur.com/OONrEw0.jpg)

Internal error. Please report to http://jb.gg/ide/critical-startup-errors

java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:459)
    at java.util.Properties.setProperty(Properties.java:166)
    at com.intellij.ide.a.g.E.c(E.java:440)
    at com.intellij.ide.a.g.F.c(F.java:96)
    at com.intellij.ide.a.g.E.a(E.java:587)
    at com.intellij.ide.a.g.E.l(E.java:714)
    at com.intellij.ide.a.g.N.a(N.java:419)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
    at java.awt.Dialog.show(Dialog.java:1084)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:734)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:456)
    at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1696)
    at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1645)
    at com.intellij.openapi.ui.Messages$MessageDialog.show(Messages.java:1471)
    at com.intellij.openapi.ui.Messages.showDialog(Messages.java:288)
    at com.intellij.openapi.ui.Messages.showDialog(Messages.java:300)
    at com.intellij.openapi.ui.Messages.showOkCancelDialog(Messages.java:651)
    at com.chrisrm.idea.MTLafComponent.askResetCustomTheme(MTLafComponent.java:284)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
    at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
    at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
    at com.sun.proxy.$Proxy37.lookAndFeelChanged(Unknown Source)
    at com.intellij.ide.ui.laf.LafManagerImpl.updateUI(LafManagerImpl.java:468)
    at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:356)
    at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:316)
    at com.chrisrm.idea.schemes.MTThemesComponent.activateTheme(MTThemesComponent.java:54)
    at com.chrisrm.idea.schemes.MTThemesComponent.initComponent(MTThemesComponent.java:46)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:497)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:119)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:447)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:454)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:103)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:406)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:65)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mallowigi** [comment]
Probably the OptionButtonUI...

**Comment by mallowigi** [comment]
I really cannot reproduce. Is it happening to someone else? 

Which version of the plugin do you have?

**Comment by mumi** [comment]
The most recent one from the repository. Tried it with PhpStorm, same error.

**Comment by mallowigi** [comment]
1.6.1?

**Comment by mumi** [comment]
Yes. When i try to install manually the 1.8.2.2 Version, I'm getting a error that the Plugin is incompatible with my installation.

**Comment by mallowigi** [comment]
I can't reproduce, sorry. Maybe it has something to do with the fact that you're on a Hackintosh, but I am clueless here.

Maybe try to download previous versions to see if one works.

**Comment by mumi** [comment]
With the recent EAP Webstorm and Material Theme 1.8.2.2, it works
