### ISSUE TITLE
Icon cannot be found in '/icons/nodes/config.png',

### ISSUE THREAD

**Issue by durban89** [ChrisRM/material-theme-jetbrains#691]
### Summary

打开IDEA后提示错误信息，点开错误信息就提示了下面的错误信息

### Expected behavior
正常运行

### Environment

![image](https://user-images.githubusercontent.com/1449203/37821718-58468ac2-2ebf-11e8-8e44-7a0309c3afa7.png)

![image](https://user-images.githubusercontent.com/1449203/37821736-6649b932-2ebf-11e8-8482-0819c4404035.png)

Icon cannot be found in '/icons/nodes/config.png', aClass='class com.chrisrm.idea.icons.MTFileIconProvider'
java.lang.Throwable: Icon cannot be found in '/icons/nodes/config.png', aClass='class com.chrisrm.idea.icons.MTFileIconProvider'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:157)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:118)
	at com.chrisrm.idea.icons.MTFileIconProvider.loadIcon(MTFileIconProvider.java:170)
	at com.chrisrm.idea.icons.MTFileIconProvider.getIconForAssociation(MTFileIconProvider.java:154)
	at com.chrisrm.idea.icons.MTFileIconProvider.getIcon(MTFileIconProvider.java:95)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:118)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:278)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:163)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:139)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:85)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:162)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dudong0726** [comment]
插件版本是多少？

**Comment by durban89** [comment]
![image](https://user-images.githubusercontent.com/1449203/38164334-5236e880-3535-11e8-9664-9f9ab915d509.png)
@dudong0726

**Comment by xdlkc** [comment]
问下这个怎么解决的？
