### ISSUE TITLE
PHPStorm 2018.1 - missing icon opening wordpress project

### ISSUE THREAD

**Issue by Sartoric** [ChrisRM/material-theme-jetbrains#706]
### Summary

Error opening wordpress project after updating PHPStorm and Material Theme

### Actual behavior
Icon cannot be found in '/icons/svg/wp-content.svg', aClass='class com.chrisrm.idea.tree.MTProjectViewNodeDecorator'

### Steps to reproduce (if needed)

1. Open a wordpress site project

You can also add Screenshots for a better understanding.

Icon cannot be found in '/icons/svg/wp-content.svg', aClass='class com.chrisrm.idea.tree.MTProjectViewNodeDecorator'
java.lang.Throwable: Icon cannot be found in '/icons/svg/wp-content.svg', aClass='class com.chrisrm.idea.tree.MTProjectViewNodeDecorator'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:145)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:106)
	at com.chrisrm.idea.tree.MTProjectViewNodeDecorator.loadIcon(MTProjectViewNodeDecorator.java:180)
	at com.chrisrm.idea.tree.MTProjectViewNodeDecorator.getIconFromAssociation(MTProjectViewNodeDecorator.java:173)
	at com.chrisrm.idea.tree.MTProjectViewNodeDecorator.setDirectoryIcon(MTProjectViewNodeDecorator.java:138)
	at com.chrisrm.idea.tree.MTProjectViewNodeDecorator.setOpenOrClosedIcon(MTProjectViewNodeDecorator.java:111)
	at com.chrisrm.idea.tree.MTProjectViewNodeDecorator.decorate(MTProjectViewNodeDecorator.java:90)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.a(AbstractPsiBasedNode.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:897)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:127)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ui.tree.StructureTreeModel$Node.f(StructureTreeModel.java:280)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:262)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:256)
	at com.intellij.ui.tree.StructureTreeModel.b(StructureTreeModel.java:235)
	at com.intellij.ui.tree.StructureTreeModel.a(StructureTreeModel.java:139)
	at com.intellij.ui.tree.StructureTreeModel.isLeaf(StructureTreeModel.java:175)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.a(AsyncTreeModel.java:576)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:551)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:444)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:410)
	at com.intellij.util.concurrency.Command$Processor.a(Command.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:84)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:140)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:138)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:84)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:105)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:114)
	at com.intellij.util.concurrency.Invoker.a(Invoker.java:123)
	at com.intellij.util.concurrency.Invoker$BackgroundThread.b(Invoker.java:248)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:228)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

java.lang.Throwable: Icon cannot be found in '/icons/svg/wp-content.svg', aClass='class com.chrisrm.idea.tree.MTProjectViewNodeDecorator'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:145)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:106)
	at com.chrisrm.idea.tree.MTProjectViewNodeDecorator.loadIcon(MTProjectViewNodeDecorator.java:180)
	at com.chrisrm.idea.tree.MTProjectViewNodeDecorator.getIconFromAssociation(MTProjectViewNodeDecorator.java:173)
	at com.chrisrm.idea.tree.MTProjectViewNodeDecorator.setDirectoryIcon(MTProjectViewNodeDecorator.java:138)
	at com.chrisrm.idea.tree.MTProjectViewNodeDecorator.setOpenOrClosedIcon(MTProjectViewNodeDecorator.java:111)
	at com.chrisrm.idea.tree.MTProjectViewNodeDecorator.decorate(MTProjectViewNodeDecorator.java:90)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.a(AbstractPsiBasedNode.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:897)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:127)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ui.tree.StructureTreeModel$Node.f(StructureTreeModel.java:280)
	at com.intellij.ui.tree.StructureTreeModel$Node.access$900(StructureTreeModel.java:256)
	at com.intellij.ui.tree.StructureTreeModel.c(StructureTreeModel.java:157)
	at java.util.ArrayList.forEach(ArrayList.java:1251)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:157)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:549)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:444)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:410)
	at com.intellij.util.concurrency.Command$Processor.a(Command.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:84)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:140)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:138)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:84)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:105)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:114)
	at com.intellij.util.concurrency.Invoker.a(Invoker.java:76)
	at com.intellij.util.concurrency.Invoker$BackgroundThread.b(Invoker.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

### Environment

PhpStorm 2018.1
Build #PS-181.4203.565, built on March 28, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.9.5

**Comment by weinde** [comment]
After update of PHP storm the material theme doesent work for me too

**Comment by danielfonda** [comment]
Same here

**Comment by mallowigi** [comment]
Please disable the Project View Decorators for the time being, I’m gonna fix it asap

**Comment by Sartoric** [comment]
Thanks

**Comment by fearlex** [comment]
Same here :D
