### ISSUE TITLE
Project module does not load directories while using theme

### ISSUE THREAD

**Issue by MattMitchell90** [ChrisRM/material-theme-jetbrains#708]
### Summary
I am getting following error when opening a project. This was working but suddenly it stopped loading directories in Project module.

### Expected behavior
Project directories are loaded

### Actual behavior
Just shows Loading and this error is given:
null
java.lang.NullPointerException
at com.chrisrm.idea.icons.Associations.findAssociationForFile(Associations.java:65)
at com.chrisrm.idea.icons.MTFileIconProvider.getIcon(MTFileIconProvider.java:62)
at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:40)
at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:183)
at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:138)
at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:278)
at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:163)
at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:163)
at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:84)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:140)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:138)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:84)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:105)
at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:162)
at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

![idea64_2018-03-30_15-57-19](https://user-images.githubusercontent.com/25928813/38152372-78aefd6e-3435-11e8-8f01-591f9e1bcd38.png)

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
IntelliJ IDEA 2018.1 (Community Edition)
Build #IC-181.4203.550, built on March 26, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Material v2.1.4

**Comment by Artviewer** [comment]
This issue drives me crazy ....

**Comment by mallowigi** [comment]
There is a v2.1.5 out, try to see if it fixes it

**Comment by Artviewer** [comment]
I have tried 2.1.5.3 on  2018.1. Directories are still not appearing

**Comment by mallowigi** [comment]
Hum... may I ask you to give me a screenshot of the folders used ? There has to be some name that the decorated folders doesn’t support... on a side note, you can try to disable the project view decorators option

**Comment by Artviewer** [comment]
Please take a look - http://joxi.ru/nAykGZGFX1gJxm

**Comment by Artviewer** [comment]
I see this issue on different projects, everything was fine before phpstorm update 2018.1

**Comment by mallowigi** [comment]
Some people stated here that uninstalling and reinstalling the plugin helped, could you please try that?

**Comment by mallowigi** [comment]
I've found out though that the Kotlin plugin was causing issues. Try disabling it perhaps.

**Comment by Artviewer** [comment]
I don't use Kotlin. I have reinstalled theme plugin again - http://joxi.ru/KAgeayatgvO9am. I believe this is issue is to changes with separating sidebar(project/structure). Also I found that if I switch project scope to project files so directories are appearing perfectly - http://joxi.ru/82Q09g9i1O4Kdm. But on project it is still "loading..."

**Comment by mallowigi** [comment]
I still cannot reproduce. What kind of project was this? Symfony? Laravel?

**Comment by MattMitchell90** [comment]
It is a gradle project. Attached the idea.log @mallowigi 
[idea.log](https://github.com/ChrisRM/material-theme-jetbrains/files/1890669/idea.log)

**Comment by mallowigi** [comment]
I can't reproduce. Do you have by chance one of the projects in open source?

**Comment by Artviewer** [comment]
In my case this is Magento 1

**Comment by mallowigi** [comment]
I tried with all your open source repositories but to no avail. Nothing wrong is happening in my end.

Also try to update to the latest version, maybe it will fix itself.

**Comment by mallowigi** [comment]
bump

**Comment by mallowigi** [comment]
bump
