### ISSUE TITLE
javassist.NotFoundException when starting WebStorm

### ISSUE THREAD

**Issue by perqin** [ChrisRM/material-theme-jetbrains#724]
### Summary

After the splash window finishes loading, the application lags for seconds and the exception is thrown.

### Expected behavior

No error reported.

### Actual behavior

The following error is thrown:

```
perqin@archlinux ~/.local/opt/webstorm-eap $ ./bin/webstorm.sh
javassist.NotFoundException: init(..) is not found in com.intellij.openapi.wm.impl.InternalDecorator
	at javassist.CtClassType.getDeclaredMethod(CtClassType.java:1277)
	at com.chrisrm.idea.tabs.MTTabsPainterPatcherComponent.hackToolWindowHeader(MTTabsPainterPatcherComponent.java:129)
	at com.chrisrm.idea.tabs.MTTabsPainterPatcherComponent.initComponent(MTTabsPainterPatcherComponent.java:249)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:483)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:106)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:444)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:396)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:382)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:65)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:374)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Steps to reproduce (if needed)

1. Start WebStorm from Linux terminal (to see stacktrace).

### Environment

WebStorm 2018.1.1 EAP
Build #WS-181.4445.29, built on April 4, 2018
Licensed to Changqin Xie
Subscription is active until September 16, 2018
For educational use only.
JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.14-1-ARCH

The plugin version is 2.1.5.

**Comment by mallowigi** [comment]
Will be fixed in 2.1.6
