### ISSUE TITLE
Error Saving Plugin Settings in PyCharm 2018.1

### ISSUE THREAD

**Issue by atutrone** [ChrisRM/material-theme-jetbrains#747]
Seem to be getting the same error as in #441 in PyCharm 2018.1 Professional on macOS 10.13.4.  Steps to reproduce in the original ticket are the same.

Error:  Unable to save plugin settings: The plugin com.chrisrm.idea.MaterialThemeUI failed to save settings and has been disabled. Please restart PyCharm

If I disable Material, the IDE works without issues.

Running version 2.2.0.1

PyCharm 2018.1 (Professional Edition)
Build #PY-181.4203.547, built on March 26, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

**Comment by mallowigi** [comment]
can you provide the steps ?

**Comment by atutrone** [comment]
Sure:

1) Attempt to make a settings change pertaining to anything Material related in PyCharm preferences or anything in the Preferences.
2)Press Apply, then OK in the Preferences
3) Once the Preferences window closes, the error will appear in the Event Log:

`Unable to save plugin settings: The plugin com.chrisrm.idea.MaterialThemeUI failed to save settings and has been disabled. Please restart PyCharm`

4) After the IDE restarts, Material will be disabled and making changes in Preferences works without issue.

**Comment by mallowigi** [comment]
Can you provide the logs?

**Comment by mallowigi** [comment]
Looks like it is caused by some bad configuration in your Trello Task management WDYT?

Caused by: java.lang.IllegalStateException: @NotNull method com/intellij/tasks/trello/model/TrelloUser.getUsername must not return null
	at com.intellij.tasks.trello.model.TrelloUser.$$$reportNull$$$0(TrelloUser.java)
	at com.intellij.tasks.trello.model.TrelloUser.getUsername(TrelloUser.java:60)
	at com.intellij.tasks.trello.model.TrelloUser.getName(TrelloUser.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.xmlb.PropertyAccessor.read(PropertyAccessor.java:52)
	at com.intellij.util.xmlb.SkipDefaultsSerializationFilter.equal(SkipDefaultsSerializationFilter.java:20)
	at com.intellij.util.xmlb.BeanBinding.serializeInto(BeanBinding.java:83)
	at com.intellij.util.xmlb.BeanBinding.serialize(BeanBinding.java:64)
	at com.intellij.util.xmlb.OptionTagBinding.serialize(OptionTagBinding.java:62)
	at com.intellij.util.xmlb.BasePrimitiveBinding.serialize(BasePrimitiveBinding.java:41)
	at com.intellij.util.xmlb.BeanBinding.serializeInto(BeanBinding.java:103)
	at com.intellij.util.xmlb.BeanBinding.serialize(BeanBinding.java:64)
	at com.intellij.util.xmlb.AbstractCollectionBinding.serializeItem(AbstractCollectionBinding.java:198)
	at com.intellij.util.xmlb.AbstractCollectionBinding.serialize(AbstractCollectionBinding.java:132)
	at com.intellij.configurationStore.XmlSerializer.serialize(xmlSerializer.kt:54)

**Comment by atutrone** [comment]
Certainly seems to be behaving itself now. Thanks!
