### ISSUE TITLE
2018.2 bugs

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#777]
1. Help button width - **done**
2. Search components (windows) - **done**
3. Checkbox borders (oval is cut) - **done**
4. list tree selection background color is too transparent
5. comboboxes iconGap (?) -> (see in file encodings) - **done**
6. Some icons disappeared in the Material Theme Menus - **done**
7. Add tool window buttons hover color if possible - **no way**
8. JRootPane is wrong in Light Themes - **done**

**Comment by pahan35** [comment]
8. Broken icon on Reopen project modal https://youtrack.jetbrains.com/issue/IDEA-192281

**Comment by IceMan81** [comment]
Adding to the bug list here:
- Double window frame with the latest 2018.2 update
![image](https://user-images.githubusercontent.com/1093778/40392272-dc811e30-5dcf-11e8-9c4e-66bd1417b868.png)

**Comment by mallowigi** [comment]
What Look and feel are you using? I've never seen that frame before.

Looks like the old Windows Theme ?

**Comment by IceMan81** [comment]
I’m using the IntelliJ theme. 

That frame showed up after I updated to the latest 2018.2 EAP
https://www.jetbrains.com/idea/nextversion/

**Comment by mallowigi** [comment]
Maybe it's only on Windows 7? It shouldn't come from the theme anyway...

Sadly i don't have Windows 7 so i can't help you there.

**Comment by mallowigi** [comment]
never mind i managed to reproduce it

**Comment by IceMan81** [comment]
Not sure if this is related to the item 6 on the list but I get this exception often
`Can't find icon in '/com/intellij/ide/ui/laf/icons/win10/clear.png' near class com.intellij.util.ui.LafIconLookup
java.lang.RuntimeException: Can't find icon in '/com/intellij/ide/ui/laf/icons/win10/clear.png' near class com.intellij.util.ui.LafIconLookup
	at com.intellij.openapi.util.IconLoader.findIcon(IconLoader.java:191)
	at com.intellij.util.ui.LafIconLookup.findIcon(LafIconLookup.kt:40)
	at com.intellij.util.ui.LafIconLookup.getIcon(LafIconLookup.kt:15)
	at com.intellij.util.ui.LafIconLookup.getIcon$default(LafIconLookup.kt:14)
	at com.intellij.util.ui.LafIconLookup.getIcon(LafIconLookup.kt)
	at com.intellij.find.SearchTextArea$DefaultLafHelper.getClearIcon(SearchTextArea.java:559)
	at com.intellij.find.SearchTextArea$ClearAction.<init>(SearchTextArea.java:413)
	at com.intellij.find.SearchTextArea.<init>(SearchTextArea.java:205)
	at com.intellij.find.SearchTextArea.<init>(SearchTextArea.java:90)
	at com.intellij.find.impl.FindPopupPanel.initComponents(FindPopupPanel.java:599)
	at com.intellij.find.impl.FindPopupPanel.<init>(FindPopupPanel.java:155)
	at com.intellij.find.impl.FindUIHelper.getOrCreateUI(FindUIHelper.java:56)
	at com.intellij.find.impl.FindUIHelper.<init>(FindUIHelper.java:45)
	at com.intellij.find.impl.FindManagerImpl.showFindDialog(FindManagerImpl.java:196)
	at com.intellij.find.findInProject.FindInProjectManager.findInProject(FindInProjectManager.java:80)
	at com.intellij.find.actions.FindInPathAction.actionPerformed(FindInPathAction.java:45)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:668)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:520)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`
