### ISSUE TITLE
material theme UI causes intellij to crash on startup

### ISSUE THREAD

**Issue by evanthomas** [ChrisRM/material-theme-jetbrains#805]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, first, read the README and check if this is a known issue.

Then, check on the Github issues if a similar issue has been posted.

If nothing of the sort, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary

Exception in plugin when intellij for linux launches. I note it was updated recently so may not be a linux or intellij specific issue.

### Expected behavior

No exception and and plugin works. It works well in webstorm and intellij on my mac.

### Actual behavior
Intellij fails to start and disables the plugin. It starts once the plugin is disabled. Reinstalling the plugin did not help.

### Steps to reproduce (if needed)

Happens consistently when intellij starts. The plugin is disabled but when I reinstall it happens again.

Here is the stack trace

```
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
    at com.chrisrm.idea.MTConfig.asProperties(MTConfig.java:133)
    at com.chrisrm.idea.MTApplicationComponent.initComponent(MTApplicationComponent.java:46)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:483)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:106)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:437)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:444)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:396)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:382)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:195)
    at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:413)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper PluginClassLoader[com.chrisrm.idea.MaterialThemeUI, 2.4-2018.1] com.intellij.ide.plugins.cl.PluginClassLoader@26c1d7e5
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 31 more
```

### Environment

IntelliJ IDEA 2018.1 (Community Edition)
Build #IC-181.4203.550, built on March 27, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-43-generic

* Plugin version: Version: 2.4-2018.1

I can't find this file: material_theme.xml

**Comment by mallowigi** [comment]
Update to 2.4.0.1-2018.1

**Comment by evanthomas** [comment]
Now it hangs at the splash screen on startup. No error messages.
