### ISSUE TITLE
Missing icon on 2018.2 EAP?

### ISSUE THREAD

**Issue by Anahkiasen** [ChrisRM/material-theme-jetbrains#818]
Currently getting the following error opening any project using Composer, makes the project view never load. I tried disabling "Project View Decorators" as seen in another issue but that didn't seem to work so not sure. Also tried disabling icons and such but same thing, Project view is still stuck on "Loading...".

- PhpStorm 2018.2 EAP
- Material Theme UI 2.4.1.1

```
java.lang.Throwable: Icon cannot be found in 'icons/packagist.png', aClass='class org.psliwa.idea.composerJson.Icons$'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:148)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:109)
	at org.psliwa.idea.composerJson.Icons$.<init>(Icons.scala:9)
	at org.psliwa.idea.composerJson.Icons$.<clinit>(Icons.scala)
	at org.psliwa.idea.composerJson.intellij.filetype.ComposerJsonFileType.getIcon(ComposerJsonFileType.scala:14)
	at com.intellij.psi.impl.ElementBase.getBaseIcon(ElementBase.java:132)
	at com.intellij.psi.impl.ElementBase.computeBaseIcon(ElementBase.java:115)
	at com.intellij.psi.impl.ElementBase.lambda$computeIcon$1(ElementBase.java:93)
	at com.intellij.util.AstLoadingFilter.disableTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disableTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.psi.impl.ElementBase.computeIcon(ElementBase.java:93)
	at com.intellij.psi.impl.ElementBase.getIcon(ElementBase.java:74)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.a(AbstractPsiBasedNode.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:915)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:126)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ui.tree.StructureTreeModel$Node.f(StructureTreeModel.java:280)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:262)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:256)
	at com.intellij.ui.tree.StructureTreeModel.c(StructureTreeModel.java:235)
	at com.intellij.ui.tree.StructureTreeModel.a(StructureTreeModel.java:139)
	at com.intellij.ui.tree.StructureTreeModel.isLeaf(StructureTreeModel.java:175)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.a(AsyncTreeModel.java:575)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:550)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:442)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:408)
	at com.intellij.util.concurrency.Command$Processor.a(Command.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1151)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:84)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:137)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:126)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:84)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:105)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:114)
	at com.intellij.util.concurrency.Invoker.a(Invoker.java:76)
	at com.intellij.util.concurrency.Invoker$BackgroundThread.b(Invoker.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:212)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:205)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mallowigi** [comment]
Not related to Material Theme plugin
