### ISSUE TITLE
JetBrains Rider 2018.2 EAP. Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart JetBrains Rider.

### ISSUE THREAD

**Issue by rutriff** [ChrisRM/material-theme-jetbrains#836]
### Summary
An error after apply theme plugin in Rider EAP 2018.2 (Build #RD-182.3458.147, built on June 29, 2018).
...

### Expected behavior
Theme applied.
...

### Actual behavior
Error occured. Rider restarts after error message with previous theme.
...

### Steps to reproduce
1. Extract jar from zip
2. Open Rider Plugin manager
3. Browse extracted jar
4. Open it
5. Restart Rider
6. Got an error: **Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart JetBrains Rider.**

```
java.lang.NoClassDefFoundError: com/segment/analytics/messages/MessageBuilder
    at com.chrisrm.idea.MTApplicationComponent.initComponent(MTApplicationComponent.java:45)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:488)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:442)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:449)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:91)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:401)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:387)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:196)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java)
    at com.intellij.idea.MainImpl$1$1.lambda$proceed$0(MainImpl.java:71)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.segment.analytics.messages.MessageBuilder PluginClassLoader[com.chrisrm.idea.MaterialThemeUI, 2.5.0] com.intellij.ide.plugins.cl.PluginClassLoader@19be72f6
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 31 more

```

### Environment

JetBrains Rider 2018.2 EAP
Build #RD-182.3458.147, built on June 29, 2018
Rider EAP User
Expiration date: July 29, 2018
JRE: 1.8.0_152-release-1226-b7 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 8.1 6.3

**Comment by rutriff** [comment]
Install Theme by selecting **zip**, **do not extract** jar.
