### ISSUE TITLE
Plugin failed to initialize

### ISSUE THREAD

**Issue by bendikrb** [ChrisRM/material-theme-jetbrains#856]
```
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'str' of com/intellij/ui/ColorUtil.fromHex must not be null
```

### Summary
Fails to initialize after the most recent update of PhpStorm (or the plugin, as it also updated on first startup). PhpStorm was upgraded from build 182.3684.37 (EAP) to 182.3684.41 (RC).

### Log output
```
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'str' of com/intellij/ui/ColorUtil.fromHex must not be null
    at com.intellij.ui.ColorUtil.$$$reportNull$$$0(ColorUtil.java)
    at com.intellij.ui.ColorUtil.fromHex(ColorUtil.java)
    at com.chrisrm.idea.MTThemeManager.applyAccents(MTThemeManager.java:285)
    at com.chrisrm.idea.MTAbstractTheme.activate(MTAbstractTheme.java:142)
    at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:243)
    at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:223)
    at com.chrisrm.idea.schemes.MTThemesComponent.activateTheme(MTThemesComponent.java:62)
    at com.chrisrm.idea.schemes.MTThemesComponent.initComponent(MTThemesComponent.java:54)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:488)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:442)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:449)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:91)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:401)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:387)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:206)
    at com.intellij.idea.IdeaApplication.a(IdeaApplication.java:72)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Environment
PhpStorm 2018.2 EAP
Build #PS-182.3684.41, built on July 24, 2018
PhpStorm EAP User
Expiration date: August 23, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-29-generic

Material Theme version: 2.6.1

**Comment by mallowigi** [comment]
It looks like something scrambled your config, please paste the contents of the configuration file `material_theme.xml` (look at the doc for more information about config files)

**Comment by bendikrb** [comment]
Yup, thanks -- working fine with newly created config.
I had an empty value for `accentColor` (`<option name="accentColor" />`), so that was probably it..
