### ISSUE TITLE
Crash on 2018.2

### ISSUE THREAD

**Issue by luispabon** [ChrisRM/material-theme-jetbrains#863]
### Summary
Material Theme UI crashes phpstorm 2018.2 upon start after phpstorm update
...

### Expected behavior
It doesn't
...

### Actual behavior
```
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.NullPointerException
    at javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1679)
    at javax.swing.text.DefaultFormatter.positionCursorAtInitialLocation(DefaultFormatter.java:333)
    at javax.swing.text.DefaultFormatter.install(DefaultFormatter.java:126)
    at javax.swing.text.InternationalFormatter.install(InternationalFormatter.java:285)
    at javax.swing.JFormattedTextField.setFormatter(JFormattedTextField.java:464)
    at javax.swing.JFormattedTextField.setValue(JFormattedTextField.java:788)
    at javax.swing.JFormattedTextField.setFormatterFactory(JFormattedTextField.java:420)
    at javax.swing.JFormattedTextField.setValue(JFormattedTextField.java:499)
    at javax.swing.JSpinner$DefaultEditor.<init>(JSpinner.java:624)
    at javax.swing.JSpinner$NumberEditor.<init>(JSpinner.java:1207)
    at javax.swing.JSpinner$NumberEditor.<init>(JSpinner.java:1183)
    at javax.swing.JSpinner$NumberEditor.<init>(JSpinner.java:1158)
    at javax.swing.JSpinner.createEditor(JSpinner.java:250)
    at javax.swing.JSpinner.<init>(JSpinner.java:156)
    at javax.swing.JSpinner.<init>(JSpinner.java:167)
    at com.chrisrm.idea.wizard.steps.MTWizardAccentPanel.initComponents(MTWizardAccentPanel.java:99)
    at com.chrisrm.idea.wizard.steps.MTWizardAccentPanel.<init>(MTWizardAccentPanel.java:57)
    at com.chrisrm.idea.wizard.MTWizardStepsProvider.initSteps(MTWizardStepsProvider.java:42)
    at com.intellij.ide.customize.CustomizeIDEWizardDialog.<init>(CustomizeIDEWizardDialog.java:62)
    at com.chrisrm.idea.wizard.MTWizardDialog.<init>(MTWizardDialog.java:58)
    at com.chrisrm.idea.MTApplicationComponent.checkWizard(MTApplicationComponent.java:62)
    at com.chrisrm.idea.MTApplicationComponent.initComponent(MTApplicationComponent.java:49)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:488)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:442)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:449)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:91)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:401)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:387)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:206)
    at com.intellij.idea.IdeaApplication.a(IdeaApplication.java:72)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
...

### Steps to reproduce (if needed)

1. First step
Have a profile with phpstorm 2018.1.x with Material UI installed
2. Second step
Upgrade to phpstorm 2018.2
3. Third step
Crash!

This doesn't happen though if I create a new phpstorm profile, then install material. Happens upon profile upgrade.

![image](https://user-images.githubusercontent.com/6388823/43355870-d8090108-925c-11e8-9ed7-7ea8e411cb59.png)

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac)
Ubuntu Bionic
* IntelliJ Product + version (IDEA, RubyMine...)
PhpStorm 2018.2
* Plugin version 
2.7.0
* Plugin configuration (found in material_theme.xml)
```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.4.2-2018.1" />
    <option name="selectedTheme" value="DARKER" />
    <option name="highlightColor" value="80cbc4" />
    <option name="isContrastMode" value="true" />
    <option name="accentColor" value="c6ff00" />
    <option name="userId" value="3d6508da:163edca42ca:-7fff" />
    <option name="allowDataCollection" value="true" />
  </component>
</application>
```
```xml
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="treeSelectionColor" value="546e7a" />
    <option name="highlightColor" value="425b67" />
    <option name="secondBorderColor" value="2a373e" />
    <option name="contrastColor" value="1e272c" />
    <option name="secondaryBackgroundColor" value="32424a" />
    <option name="buttonColor" value="2e3c43" />
    <option name="selectionForegroundColor" value="ffffff" />
    <option name="selectionBackgroundColor" value="546e7a" />
    <option name="textColor" value="607d8b" />
    <option name="foregroundColor" value="b0bec5" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
That’s odd... what do you mean by phpstorm profile?

**Comment by luispabon** [comment]
The folder where phpstorm stores settings, plugins etc.

**Comment by mallowigi** [comment]
Ok, what if you disable Material theme then upgrade then reinstall it?

**Comment by mallowigi** [comment]
Well since i cant' reproduce this, it will be hard to debug. 

Try to install manually this and tell me if it solves the problem

[Material Theme-2.7.0.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/2238126/Material.Theme-2.7.0.zip)

**Comment by luispabon** [comment]
I will do this tonight 👍

**Comment by luispabon** [comment]
just to confirm, disable material before updating, then install the zip? or uninstall material before updating then install the zip?

**Comment by mallowigi** [comment]
no just use "install plugin from disk" and use the zip.

**Comment by luispabon** [comment]
Okay, I've managed to "fix it" by syncing my settings with my jetbrains account before the update, then upgrading without importing my old profile folder, then syncing mack from the jetbrains account.

**Comment by mallowigi** [comment]
Well sorry for your troubles. I've tried to reproduce but without avail. But this is so weird that it was actually causing an error because of your settings...

Can you show me your Editor Settings ? (Settings > Editor) A screenshot is sufficient

You could also have done "Export settings" from the Jetbrains

**Comment by mallowigi** [comment]
I've imported your settings and tried to reproduce on Windows, but no error whatsoever. I give up :/

**Comment by luispabon** [comment]
:'( thanks for trying though. I imagine by now more people would have reported if it was widespread in any way :+1:

**Comment by destinydriven** [comment]
I have been experiencing random crashes since upgrading to 2018.2 (MacOS) but it has nothing to do with Material Theme UI since I don't even have that installed.

**Comment by MaitreManuel** [comment]
The [Material.Theme-2.7.0.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/2238126/Material.Theme-2.7.0.zip) solves my problem to install Material UI on PHPStorm 2018.2, thank you ! :raised_hands:

**Comment by sweetld** [comment]
I have had exactly the same error as the OP, right down to the stack trace, ever since I upgraded from IntelliJ 2018.1 to 2018.2

Since then there have been two upgrades to Material UI Plugin, neither of which have actually resolved my issue.

I have Enterprise IntelliJ installed on a Windows 7 PC and two Linux PC's (One running Mint 18, the other running Ubuntu 18.04).

I have followed the same upgrade path for all these PC's, and only the Windows PC has been effected, both Linux PC's are working fine with 2018.2 and Material UI Plugin.

I am not using phpstorm to my knowledge, so not sure what I can do to overcome the issue.

Would be grateful for any suggestions.

**Comment by luispabon** [comment]
I imagine the issue is with the intellij platform overall, not specifically phpstorm and linux. I reckon this problem is related to the new set up wizard thing.

@sweetld I worked around the issue, posted how I did it a few posts up - essentially syncing my profile with jetbrains instead of importing the old profile.

**Comment by sweetld** [comment]
@luispabon You could well be correct regarding the setup wizard - it's certainly not a linux issue, as both my linux PC's worked fine, it was only my Windows PC that had the problem.

The IntelliJ version across them all is the same, however the configuration of the Windows IntelliJ is different to the two Linux IntelliJ setups, so I guess it's down to that somewhere along the line.

Unfortunately I could not use your workaround, possibly because I did not fully understand the bit around phpstorm - I don't think that I have that, so couldn't 

> remove phpstorm 2018.2 profile

I did look through for `.PhpStorm*` anywhere under the users directory on my Windows PC, but could not find anything...

Was hoping that someone might have another suggestion? I would really like to get Material UI working again, it's been fine the last two or three IntelliJ upgrades on that Windows PC, it's only when upgrading to 2018.2 that it stopped altogether.

**Comment by mallowigi** [comment]
If the wizard is the issue, you can disable it altogether by putting the property `isWizardShown` to true in the material config file

**Comment by nickmellor** [comment]
similar problem just now, Linux (CentOS), upgrading from 2018.1 to 2018.2. (I use the Darcula theme, and this stack trace is suggestive...)

java.lang.ClassCastException: java.lang.Boolean cannot be cast to com.intellij.openapi.actionSystem.ex.ComboBoxAction
	at com.intellij.ide.ui.laf.darcula.ui.DarculaButtonUI.getComboAction(DarculaButtonUI.java:75)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaButtonUI.getDarculaButtonSize(DarculaButtonUI.java:236)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaButtonUI.getPreferredSize(DarculaButtonUI.java:254)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1663)
	at com.vladsch.MissingInActions.util.ui.ComboBoxAction$ComboBoxButton.getPreferredSize(ComboBoxAction.java:463)
	at com.vladsch.MissingInActions.util.ui.ComboBoxAction$ComboBoxButton.updateButtonSize(ComboBoxAction.java:585)
	at com.vladsch.MissingInActions.util.ui.ComboBoxAction$ComboBoxButton.initButton(ComboBoxAction.java:387)
	at com.vladsch.MissingInActions.util.ui.ComboBoxAction$ComboBoxButton.addNotify(ComboBoxAction.java:380)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addImpl(Container.java:1122)
	at java.awt.Container.add(Container.java:417)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.fillToolBar(ActionToolbarImpl.java:320)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.java:1112)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:53)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$2.updateActionsImpl(ActionToolbarImpl.java:175)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:186)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:101)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:93)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1093)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addNotify(ActionToolbarImpl.java:213)
	at java.awt.Container.addImpl(Container.java:1122)
	at java.awt.Container.add(Container.java:467)
	at com.intellij.openapi.wm.impl.IdeRootPane.updateToolbar(IdeRootPane.java:190)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.init(ToolWindowManagerImpl.java:428)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$1.projectOpened(ToolWindowManagerImpl.java:154)
	at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:376)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:357)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:208)
	at com.sun.proxy.$Proxy25.projectOpened(Unknown Source)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:772)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$null$6(ProjectManagerImpl.java:390)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransactionAndWait$2(TransactionGuardImpl.java:165)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:864)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:205)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:588)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:250)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:203)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectUnderProgress(ProjectManagerImpl.java:439)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:414)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:245)
	at com.intellij.ide.RecentProjectsManagerBase.doOpenProject(RecentProjectsManagerBase.java:579)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:706)
	at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:748)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:376)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:357)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:208)
	at com.sun.proxy.$Proxy53.appStarting(Unknown Source)
	at com.intellij.idea.IdeaApplication$IdeStarter.lambda$main$1(IdeaApplication.java:374)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:372)
	at com.intellij.idea.IdeaApplication.lambda$run$1(IdeaApplication.java:212)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:212)
	at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:75)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by sweetld** [comment]
@mallowigi thanks very much for the pointer, once I had found which file to set this in, and where that file was, it worked a treat and overcame the issue.

I now have my Material Theme back again!
