### ISSUE TITLE
2018.3 issues

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#928]
This issue will regroup all issues from 2018.3 EAP

- Tab height ceased to work
- Random errors caused by the absence of some icons
- Random errors caused by the absence of some properties
- New plugin page background color
- Bad padding here and there

**Comment by pahan35** [comment]
I also noticed that there is missed theming in notification popups.
![image](https://user-images.githubusercontent.com/13823215/45479447-338d5580-b74f-11e8-9c82-ee485d67a541.png)

**Comment by pahan35** [comment]
@mallowigi also I noticed that in the last build active Material fonts looks too thin.
![image](https://user-images.githubusercontent.com/13823215/45481059-3ab66280-b753-11e8-8155-1675f9f1093d.png).

**Comment by pahan35** [comment]
@mallowigi that problem happens only after updating to last EAP today.

**Comment by pahan35** [comment]
Bad background in active options in in Commit window
![image](https://user-images.githubusercontent.com/13823215/45492298-99400880-b774-11e8-81b2-68632ce4ff17.png)

Not best active tab title in new search window
![image](https://user-images.githubusercontent.com/13823215/45492389-d73d2c80-b774-11e8-934c-26b54bfccccc.png)

**Comment by pahan35** [comment]
@mallowigi you were right about problems with Roboto fonts. There is no problem with this plugin. I'll solve it myself

**Comment by proteo** [comment]
Hi, please take a look to my comment regarding the border line color here:

https://github.com/ChrisRM/material-theme-jetbrains/issues/896#issuecomment-421107189

**Comment by mallowigi** [comment]
Need to fix menu borders and separators

**Comment by mallowigi** [comment]
BTW what do you think of this tweak of the new SE? 
![image](https://user-images.githubusercontent.com/5015756/46466846-00316a00-c7d5-11e8-824c-855a86731298.png)

**Comment by doublefx** [comment]
Hi, very nice plugin, I like it, thanks.

Here is the stack trace I keep getting in 2018.3 EAP:

`com.intellij.openapi.extensions.impl.PicoPluginExtensionInitializationException
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:90)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:113)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:245)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:178)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:196)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:45)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:26)
	at com.intellij.openapi.options.colors.pages.ColorSettingsPagesImpl.getRegisteredPages(ColorSettingsPagesImpl.java:28)
	at com.intellij.application.options.colors.ColorAndFontOptions.initPluggedDescriptions(ColorAndFontOptions.java:524)
	at com.intellij.application.options.colors.ColorAndFontOptions.initScheme(ColorAndFontOptions.java:516)
	at com.intellij.application.options.colors.ColorAndFontOptions.initAll(ColorAndFontOptions.java:506)
	at com.intellij.application.options.colors.ColorAndFontOptions.buildConfigurables(ColorAndFontOptions.java:370)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:95)
	at com.intellij.openapi.options.ex.ConfigurableWrapper$CompositeWrapper.getConfigurables(ConfigurableWrapper.java:253)
	at com.intellij.ide.ui.search.SearchUtil.addChildren(SearchUtil.java:552)
	at com.intellij.ide.ui.search.SearchUtil.addChildren(SearchUtil.java:555)
	at com.intellij.ide.ui.search.SearchUtil.expandGroup(SearchUtil.java:543)
	at com.intellij.ide.ui.search.SearchUtil.expand(SearchUtil.java:533)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.findPreselectedByDisplayName(ShowSettingsUtilImpl.java:142)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:137)
	at com.chrisrm.idea.status.MTStatusWidget.lambda$null$0(MTStatusWidget.java:63)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ExceptionInInitializerError
	at org.intellij.lang.batch.editor.colors.BatchColorPage.<init>(BatchColorPage.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:85)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:62)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:45)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:72)
	... 41 more
Caused by: java.lang.IllegalStateException: TextAttributeKey(name:'BATCH.BRACES', fallbackAttributeKey:'DEFAULT_BRACKETS')  was already registered with the other fallback attribute key: DEFAULT_BRACES
	at com.intellij.openapi.editor.colors.TextAttributesKey.mergeKeys(TextAttributesKey.java:212)
	at com.intellij.openapi.editor.colors.TextAttributesKey.lambda$getOrCreate$4(TextAttributesKey.java:198)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
	at com.intellij.openapi.editor.colors.TextAttributesKey.getOrCreate(TextAttributesKey.java:198)
	at com.intellij.openapi.editor.colors.TextAttributesKey.createTextAttributesKey(TextAttributesKey.java:185)
	at org.intellij.lang.batch.editor.BatchHighlighterColors.<clinit>(BatchHighlighterColors.java:46)
	... 51 more
Caused by:

java.lang.ExceptionInInitializerError
	at org.intellij.lang.batch.editor.colors.BatchColorPage.<init>(BatchColorPage.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:85)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:62)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:45)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:72)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:113)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:245)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:178)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:196)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:45)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:26)
	at com.intellij.openapi.options.colors.pages.ColorSettingsPagesImpl.getRegisteredPages(ColorSettingsPagesImpl.java:28)
	at com.intellij.application.options.colors.ColorAndFontOptions.initPluggedDescriptions(ColorAndFontOptions.java:524)
	at com.intellij.application.options.colors.ColorAndFontOptions.initScheme(ColorAndFontOptions.java:516)
	at com.intellij.application.options.colors.ColorAndFontOptions.initAll(ColorAndFontOptions.java:506)
	at com.intellij.application.options.colors.ColorAndFontOptions.buildConfigurables(ColorAndFontOptions.java:370)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:95)
	at com.intellij.openapi.options.ex.ConfigurableWrapper$CompositeWrapper.getConfigurables(ConfigurableWrapper.java:253)
	at com.intellij.ide.ui.search.SearchUtil.addChildren(SearchUtil.java:552)
	at com.intellij.ide.ui.search.SearchUtil.addChildren(SearchUtil.java:555)
	at com.intellij.ide.ui.search.SearchUtil.expandGroup(SearchUtil.java:543)
	at com.intellij.ide.ui.search.SearchUtil.expand(SearchUtil.java:533)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.findPreselectedByDisplayName(ShowSettingsUtilImpl.java:142)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:137)
	at com.chrisrm.idea.status.MTStatusWidget.lambda$null$0(MTStatusWidget.java:63)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalStateException: TextAttributeKey(name:'BATCH.BRACES', fallbackAttributeKey:'DEFAULT_BRACKETS')  was already registered with the other fallback attribute key: DEFAULT_BRACES
	at com.intellij.openapi.editor.colors.TextAttributesKey.mergeKeys(TextAttributesKey.java:212)
	at com.intellij.openapi.editor.colors.TextAttributesKey.lambda$getOrCreate$4(TextAttributesKey.java:198)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
	at com.intellij.openapi.editor.colors.TextAttributesKey.getOrCreate(TextAttributesKey.java:198)
	at com.intellij.openapi.editor.colors.TextAttributesKey.createTextAttributesKey(TextAttributesKey.java:185)
	at org.intellij.lang.batch.editor.BatchHighlighterColors.<clinit>(BatchHighlighterColors.java:46)
	... 51 more`

**Comment by mallowigi** [comment]
Which version of the plugin are you using?
